namespace GameHub.Forms
{
    partial class CheckoutForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerTitle = new System.Windows.Forms.Label();
            this.designerTitle.AutoSize = false;
            this.designerTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.designerTitle.Location = new System.Drawing.Point(28, 22);
            this.designerTitle.Name = "designerTitle";
            this.designerTitle.Size = new System.Drawing.Size(420, 42);
            this.designerTitle.Text = "Checkout";
            this.Controls.Add(this.designerTitle);
            this.designerSubtitle = new System.Windows.Forms.Label();
            this.designerSubtitle.AutoSize = false;
            this.designerSubtitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSubtitle.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSubtitle.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerSubtitle.Location = new System.Drawing.Point(30, 54);
            this.designerSubtitle.Name = "designerSubtitle";
            this.designerSubtitle.Size = new System.Drawing.Size(620, 28);
            this.designerSubtitle.Text = "Review your cart, membership discount and final payment.";
            this.Controls.Add(this.designerSubtitle);
            this.designerInvoice = new System.Windows.Forms.Panel();
            this.designerInvoice.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerInvoice.Location = new System.Drawing.Point(28, 94);
            this.designerInvoice.Name = "designerInvoice";
            this.designerInvoice.Size = new System.Drawing.Size(784, 292);
            this.Controls.Add(this.designerInvoice);
            this.designerInvoicePill = new System.Windows.Forms.Label();
            this.designerInvoicePill.AutoSize = false;
            this.designerInvoicePill.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerInvoicePill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerInvoicePill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerInvoicePill.Location = new System.Drawing.Point(18, 16);
            this.designerInvoicePill.Name = "designerInvoicePill";
            this.designerInvoicePill.Size = new System.Drawing.Size(72, 26);
            this.designerInvoicePill.Text = "INVOICE";
            this.designerInvoicePill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerInvoice.Controls.Add(this.designerInvoicePill);
            this._lblMeta = new System.Windows.Forms.Label();
            this._lblMeta.AutoSize = false;
            this._lblMeta.BackColor = System.Drawing.Color.Transparent;
            this._lblMeta.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this._lblMeta.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this._lblMeta.Location = new System.Drawing.Point(112, 20);
            this._lblMeta.Name = "_lblMeta";
            this._lblMeta.Size = new System.Drawing.Size(480, 24);
            this._lblMeta.Text = "3 items • Customer account";
            this.designerInvoice.Controls.Add(this._lblMeta);
            this._grid = new System.Windows.Forms.DataGridView();
            this._grid.AllowUserToAddRows = false;
            this._grid.AllowUserToDeleteRows = false;
            this._grid.BackgroundColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this._grid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._grid.ColumnHeadersHeight = 36;
            this._grid.Location = new System.Drawing.Point(18, 58);
            this._grid.Name = "_grid";
            this._grid.ReadOnly = true;
            this._grid.RowHeadersVisible = false;
            this._grid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._grid.Size = new System.Drawing.Size(748, 214);
            this.designerInvoice.Controls.Add(this._grid);
            this.designerPayment = new System.Windows.Forms.Panel();
            this.designerPayment.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerPayment.Location = new System.Drawing.Point(28, 406);
            this.designerPayment.Name = "designerPayment";
            this.designerPayment.Size = new System.Drawing.Size(350, 164);
            this.Controls.Add(this.designerPayment);
            this.designerPaymentTitle = new System.Windows.Forms.Label();
            this.designerPaymentTitle.AutoSize = false;
            this.designerPaymentTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerPaymentTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPaymentTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.designerPaymentTitle.Location = new System.Drawing.Point(18, 16);
            this.designerPaymentTitle.Name = "designerPaymentTitle";
            this.designerPaymentTitle.Size = new System.Drawing.Size(260, 28);
            this.designerPaymentTitle.Text = "Payment Method";
            this.designerPayment.Controls.Add(this.designerPaymentTitle);
            this.designerPaymentSub = new System.Windows.Forms.Label();
            this.designerPaymentSub.AutoSize = false;
            this.designerPaymentSub.BackColor = System.Drawing.Color.Transparent;
            this.designerPaymentSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerPaymentSub.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerPaymentSub.Location = new System.Drawing.Point(18, 42);
            this.designerPaymentSub.Name = "designerPaymentSub";
            this.designerPaymentSub.Size = new System.Drawing.Size(314, 28);
            this.designerPaymentSub.Text = "Wallet payments are charged atomically with the order.";
            this.designerPayment.Controls.Add(this.designerPaymentSub);
            this._cboMethod = new System.Windows.Forms.ComboBox();
            this._cboMethod.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._cboMethod.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._cboMethod.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._cboMethod.Location = new System.Drawing.Point(18, 74);
            this._cboMethod.Name = "_cboMethod";
            this._cboMethod.Size = new System.Drawing.Size(314, 28);
            this._cboMethod.Items.AddRange(new object[] { "Wallet", "Card (Simulated)", "bKash (Simulated)" });
            this._cboMethod.SelectedIndex = 0;
            this.designerPayment.Controls.Add(this._cboMethod);
            this.designerCancel = new System.Windows.Forms.Button();
            this.designerCancel.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerCancel.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerCancel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerCancel.Location = new System.Drawing.Point(18, 118);
            this.designerCancel.Name = "designerCancel";
            this.designerCancel.Size = new System.Drawing.Size(112, 32);
            this.designerCancel.Text = "← Back";
            this.designerCancel.UseVisualStyleBackColor = false;
            this.designerPayment.Controls.Add(this.designerCancel);
            this.designerTotals = new System.Windows.Forms.Panel();
            this.designerTotals.BackColor = System.Drawing.Color.FromArgb(74, 65, 220);
            this.designerTotals.Location = new System.Drawing.Point(398, 406);
            this.designerTotals.Name = "designerTotals";
            this.designerTotals.Size = new System.Drawing.Size(414, 164);
            this.Controls.Add(this.designerTotals);
            this.designerTotalsTitle = new System.Windows.Forms.Label();
            this.designerTotalsTitle.AutoSize = false;
            this.designerTotalsTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTotalsTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTotalsTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.designerTotalsTitle.Location = new System.Drawing.Point(18, 14);
            this.designerTotalsTitle.Name = "designerTotalsTitle";
            this.designerTotalsTitle.Size = new System.Drawing.Size(200, 28);
            this.designerTotalsTitle.Text = "Order Total";
            this.designerTotals.Controls.Add(this.designerTotalsTitle);
            this._lblTotals = new System.Windows.Forms.Label();
            this._lblTotals.AutoSize = false;
            this._lblTotals.BackColor = System.Drawing.Color.Transparent;
            this._lblTotals.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._lblTotals.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this._lblTotals.Location = new System.Drawing.Point(18, 42);
            this._lblTotals.Name = "_lblTotals";
            this._lblTotals.Size = new System.Drawing.Size(220, 104);
            this._lblTotals.Text = "Subtotal: Tk 5,997\r\nDiscount: Tk 600\r\nVAT: Tk 810\r\nTotal: Tk 6,207";
            this.designerTotals.Controls.Add(this._lblTotals);
            this._payButton = new System.Windows.Forms.Button();
            this._payButton.BackColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this._payButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this._payButton.ForeColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this._payButton.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this._payButton.Location = new System.Drawing.Point(244, 86);
            this._payButton.Name = "_payButton";
            this._payButton.Size = new System.Drawing.Size(152, 44);
            this._payButton.Text = "CONFIRM PAYMENT";
            this._payButton.UseVisualStyleBackColor = false;
            this._payButton.Click += new System.EventHandler(this.Pay_Click);
            this.designerTotals.Controls.Add(this._payButton);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(840, 600);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(840, 600);
            this.Name = "CheckoutForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - Checkout";
        }

        private System.Windows.Forms.Label designerTitle;
        private System.Windows.Forms.Label designerSubtitle;
        private System.Windows.Forms.Panel designerInvoice;
        private System.Windows.Forms.Label designerInvoicePill;
        private System.Windows.Forms.Panel designerPayment;
        private System.Windows.Forms.Label designerPaymentTitle;
        private System.Windows.Forms.Label designerPaymentSub;
        private System.Windows.Forms.Button designerCancel;
        private System.Windows.Forms.Panel designerTotals;
        private System.Windows.Forms.Label designerTotalsTitle;
    }
}
