namespace GameHub.Forms
{
    partial class CustomerDashboardForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerSidebar = new System.Windows.Forms.Panel();
            this.designerSidebar.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerSidebar.Location = new System.Drawing.Point(0, 0);
            this.designerSidebar.Name = "designerSidebar";
            this.designerSidebar.Size = new System.Drawing.Size(238, 760);
            this.Controls.Add(this.designerSidebar);
            this.designerLogo = new System.Windows.Forms.Panel();
            this.designerLogo.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerLogo.Location = new System.Drawing.Point(20, 20);
            this.designerLogo.Name = "designerLogo";
            this.designerLogo.Size = new System.Drawing.Size(52, 52);
            this.designerSidebar.Controls.Add(this.designerLogo);
            this.designerLogoText = new System.Windows.Forms.Label();
            this.designerLogoText.AutoSize = false;
            this.designerLogoText.BackColor = System.Drawing.Color.Transparent;
            this.designerLogoText.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerLogoText.Font = new System.Drawing.Font("Segoe UI", 19F, System.Drawing.FontStyle.Bold);
            this.designerLogoText.Location = new System.Drawing.Point(0, 5);
            this.designerLogoText.Name = "designerLogoText";
            this.designerLogoText.Size = new System.Drawing.Size(52, 36);
            this.designerLogoText.Text = "G";
            this.designerLogoText.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerLogo.Controls.Add(this.designerLogoText);
            this.designerBrand = new System.Windows.Forms.Label();
            this.designerBrand.AutoSize = false;
            this.designerBrand.BackColor = System.Drawing.Color.Transparent;
            this.designerBrand.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBrand.Font = new System.Drawing.Font("Segoe UI", 13.5F, System.Drawing.FontStyle.Bold);
            this.designerBrand.Location = new System.Drawing.Point(82, 21);
            this.designerBrand.Name = "designerBrand";
            this.designerBrand.Size = new System.Drawing.Size(145, 31);
            this.designerBrand.Text = "GameHub";
            this.designerSidebar.Controls.Add(this.designerBrand);
            this.designerBrandSub = new System.Windows.Forms.Label();
            this.designerBrandSub.AutoSize = false;
            this.designerBrandSub.BackColor = System.Drawing.Color.Transparent;
            this.designerBrandSub.ForeColor = System.Drawing.Color.FromArgb(116, 126, 158);
            this.designerBrandSub.Font = new System.Drawing.Font("Segoe UI", 7F, System.Drawing.FontStyle.Bold);
            this.designerBrandSub.Location = new System.Drawing.Point(83, 50);
            this.designerBrandSub.Name = "designerBrandSub";
            this.designerBrandSub.Size = new System.Drawing.Size(145, 18);
            this.designerBrandSub.Text = "DESKTOP LAUNCHER";
            this.designerSidebar.Controls.Add(this.designerBrandSub);
            this.designerBrowse = new System.Windows.Forms.Label();
            this.designerBrowse.AutoSize = false;
            this.designerBrowse.BackColor = System.Drawing.Color.Transparent;
            this.designerBrowse.ForeColor = System.Drawing.Color.FromArgb(116, 126, 158);
            this.designerBrowse.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerBrowse.Location = new System.Drawing.Point(22, 106);
            this.designerBrowse.Name = "designerBrowse";
            this.designerBrowse.Size = new System.Drawing.Size(120, 22);
            this.designerBrowse.Text = "BROWSE";
            this.designerSidebar.Controls.Add(this.designerBrowse);
            this.designerBrowseNav1 = new System.Windows.Forms.Button();
            this.designerBrowseNav1.BackColor = System.Drawing.Color.FromArgb(74, 65, 220);
            this.designerBrowseNav1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBrowseNav1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBrowseNav1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBrowseNav1.Location = new System.Drawing.Point(18, 134);
            this.designerBrowseNav1.Name = "designerBrowseNav1";
            this.designerBrowseNav1.Size = new System.Drawing.Size(202, 44);
            this.designerBrowseNav1.Text = "   Home";
            this.designerBrowseNav1.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerBrowseNav1);
            this.designerBrowseNav2 = new System.Windows.Forms.Button();
            this.designerBrowseNav2.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerBrowseNav2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBrowseNav2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBrowseNav2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBrowseNav2.Location = new System.Drawing.Point(18, 184);
            this.designerBrowseNav2.Name = "designerBrowseNav2";
            this.designerBrowseNav2.Size = new System.Drawing.Size(202, 44);
            this.designerBrowseNav2.Text = "   Store";
            this.designerBrowseNav2.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerBrowseNav2);
            this.designerBrowseNav3 = new System.Windows.Forms.Button();
            this.designerBrowseNav3.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerBrowseNav3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBrowseNav3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBrowseNav3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBrowseNav3.Location = new System.Drawing.Point(18, 234);
            this.designerBrowseNav3.Name = "designerBrowseNav3";
            this.designerBrowseNav3.Size = new System.Drawing.Size(202, 44);
            this.designerBrowseNav3.Text = "   Library";
            this.designerBrowseNav3.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerBrowseNav3);
            this.designerBrowseNav4 = new System.Windows.Forms.Button();
            this.designerBrowseNav4.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerBrowseNav4.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBrowseNav4.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBrowseNav4.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBrowseNav4.Location = new System.Drawing.Point(18, 284);
            this.designerBrowseNav4.Name = "designerBrowseNav4";
            this.designerBrowseNav4.Size = new System.Drawing.Size(202, 44);
            this.designerBrowseNav4.Text = "   Wishlist";
            this.designerBrowseNav4.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerBrowseNav4);
            this.designerAccount = new System.Windows.Forms.Label();
            this.designerAccount.AutoSize = false;
            this.designerAccount.BackColor = System.Drawing.Color.Transparent;
            this.designerAccount.ForeColor = System.Drawing.Color.FromArgb(116, 126, 158);
            this.designerAccount.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerAccount.Location = new System.Drawing.Point(22, 348);
            this.designerAccount.Name = "designerAccount";
            this.designerAccount.Size = new System.Drawing.Size(120, 22);
            this.designerAccount.Text = "ACCOUNT";
            this.designerSidebar.Controls.Add(this.designerAccount);
            this.designerAccountNav1 = new System.Windows.Forms.Button();
            this.designerAccountNav1.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerAccountNav1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerAccountNav1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerAccountNav1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerAccountNav1.Location = new System.Drawing.Point(18, 382);
            this.designerAccountNav1.Name = "designerAccountNav1";
            this.designerAccountNav1.Size = new System.Drawing.Size(202, 44);
            this.designerAccountNav1.Text = "   Wallet";
            this.designerAccountNav1.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerAccountNav1);
            this.designerAccountNav2 = new System.Windows.Forms.Button();
            this.designerAccountNav2.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerAccountNav2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerAccountNav2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerAccountNav2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerAccountNav2.Location = new System.Drawing.Point(18, 432);
            this.designerAccountNav2.Name = "designerAccountNav2";
            this.designerAccountNav2.Size = new System.Drawing.Size(202, 44);
            this.designerAccountNav2.Text = "   Subscription";
            this.designerAccountNav2.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerAccountNav2);
            this.designerAccountNav3 = new System.Windows.Forms.Button();
            this.designerAccountNav3.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerAccountNav3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerAccountNav3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerAccountNav3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerAccountNav3.Location = new System.Drawing.Point(18, 482);
            this.designerAccountNav3.Name = "designerAccountNav3";
            this.designerAccountNav3.Size = new System.Drawing.Size(202, 44);
            this.designerAccountNav3.Text = "   Profile";
            this.designerAccountNav3.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerAccountNav3);
            this.designerUserCard = new System.Windows.Forms.Panel();
            this.designerUserCard.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerUserCard.Location = new System.Drawing.Point(18, 580);
            this.designerUserCard.Name = "designerUserCard";
            this.designerUserCard.Size = new System.Drawing.Size(202, 82);
            this.designerSidebar.Controls.Add(this.designerUserCard);
            this.designerAvatar = new System.Windows.Forms.Panel();
            this.designerAvatar.BackColor = System.Drawing.Color.FromArgb(58, 159, 255);
            this.designerAvatar.Location = new System.Drawing.Point(12, 14);
            this.designerAvatar.Name = "designerAvatar";
            this.designerAvatar.Size = new System.Drawing.Size(48, 48);
            this.designerUserCard.Controls.Add(this.designerAvatar);
            this.designerAvatarText = new System.Windows.Forms.Label();
            this.designerAvatarText.AutoSize = false;
            this.designerAvatarText.BackColor = System.Drawing.Color.Transparent;
            this.designerAvatarText.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerAvatarText.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold);
            this.designerAvatarText.Location = new System.Drawing.Point(0, 5);
            this.designerAvatarText.Name = "designerAvatarText";
            this.designerAvatarText.Size = new System.Drawing.Size(48, 36);
            this.designerAvatarText.Text = "G";
            this.designerAvatarText.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerAvatar.Controls.Add(this.designerAvatarText);
            this.designerUserName = new System.Windows.Forms.Label();
            this.designerUserName.AutoSize = false;
            this.designerUserName.BackColor = System.Drawing.Color.Transparent;
            this.designerUserName.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerUserName.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.designerUserName.Location = new System.Drawing.Point(72, 14);
            this.designerUserName.Name = "designerUserName";
            this.designerUserName.Size = new System.Drawing.Size(116, 24);
            this.designerUserName.Text = "Customer";
            this.designerUserCard.Controls.Add(this.designerUserName);
            this.designerOnline = new System.Windows.Forms.Label();
            this.designerOnline.AutoSize = false;
            this.designerOnline.BackColor = System.Drawing.Color.Transparent;
            this.designerOnline.ForeColor = System.Drawing.Color.FromArgb(72, 201, 154);
            this.designerOnline.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerOnline.Location = new System.Drawing.Point(72, 41);
            this.designerOnline.Name = "designerOnline";
            this.designerOnline.Size = new System.Drawing.Size(110, 20);
            this.designerOnline.Text = "●  Online";
            this.designerUserCard.Controls.Add(this.designerOnline);
            this.designerLogout = new System.Windows.Forms.Button();
            this.designerLogout.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerLogout.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerLogout.ForeColor = System.Drawing.Color.FromArgb(238, 93, 111);
            this.designerLogout.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerLogout.Location = new System.Drawing.Point(20, 682);
            this.designerLogout.Name = "designerLogout";
            this.designerLogout.Size = new System.Drawing.Size(198, 42);
            this.designerLogout.Text = "↪   Logout";
            this.designerLogout.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerLogout);
            this.designerMain = new System.Windows.Forms.Panel();
            this.designerMain.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.designerMain.Location = new System.Drawing.Point(238, 0);
            this.designerMain.Name = "designerMain";
            this.designerMain.Size = new System.Drawing.Size(1042, 760);
            this.Controls.Add(this.designerMain);
            this.designerTopbar = new System.Windows.Forms.Panel();
            this.designerTopbar.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerTopbar.Location = new System.Drawing.Point(0, 0);
            this.designerTopbar.Name = "designerTopbar";
            this.designerTopbar.Size = new System.Drawing.Size(1042, 64);
            this.designerMain.Controls.Add(this.designerTopbar);
            this.designerLive = new System.Windows.Forms.Label();
            this.designerLive.AutoSize = false;
            this.designerLive.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerLive.ForeColor = System.Drawing.Color.FromArgb(72, 201, 154);
            this.designerLive.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerLive.Location = new System.Drawing.Point(24, 19);
            this.designerLive.Name = "designerLive";
            this.designerLive.Size = new System.Drawing.Size(82, 26);
            this.designerLive.Text = "SQL LIVE";
            this.designerLive.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerTopbar.Controls.Add(this.designerLive);
            this.designerQuickStore = new System.Windows.Forms.Button();
            this.designerQuickStore.BackColor = System.Drawing.Color.FromArgb(74, 65, 220);
            this.designerQuickStore.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerQuickStore.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerQuickStore.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerQuickStore.Location = new System.Drawing.Point(816, 14);
            this.designerQuickStore.Name = "designerQuickStore";
            this.designerQuickStore.Size = new System.Drawing.Size(90, 36);
            this.designerQuickStore.Text = "STORE";
            this.designerQuickStore.UseVisualStyleBackColor = false;
            this.designerTopbar.Controls.Add(this.designerQuickStore);
            this.designerCustomerPill = new System.Windows.Forms.Label();
            this.designerCustomerPill.AutoSize = false;
            this.designerCustomerPill.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerCustomerPill.ForeColor = System.Drawing.Color.FromArgb(64, 214, 216);
            this.designerCustomerPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerCustomerPill.Location = new System.Drawing.Point(918, 19);
            this.designerCustomerPill.Name = "designerCustomerPill";
            this.designerCustomerPill.Size = new System.Drawing.Size(98, 26);
            this.designerCustomerPill.Text = "CUSTOMER";
            this.designerCustomerPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerTopbar.Controls.Add(this.designerCustomerPill);
            this.designerContent = new System.Windows.Forms.Panel();
            this.designerContent.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.designerContent.Location = new System.Drawing.Point(24, 82);
            this.designerContent.Name = "designerContent";
            this.designerContent.Size = new System.Drawing.Size(994, 650);
            this.designerMain.Controls.Add(this.designerContent);
            this.designerHomeTitle = new System.Windows.Forms.Label();
            this.designerHomeTitle.AutoSize = false;
            this.designerHomeTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerHomeTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerHomeTitle.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.designerHomeTitle.Location = new System.Drawing.Point(0, 0);
            this.designerHomeTitle.Name = "designerHomeTitle";
            this.designerHomeTitle.Size = new System.Drawing.Size(650, 44);
            this.designerHomeTitle.Text = "Welcome back to GameHub";
            this.designerContent.Controls.Add(this.designerHomeTitle);
            this.designerHomeSub = new System.Windows.Forms.Label();
            this.designerHomeSub.AutoSize = false;
            this.designerHomeSub.BackColor = System.Drawing.Color.Transparent;
            this.designerHomeSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerHomeSub.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this.designerHomeSub.Location = new System.Drawing.Point(2, 46);
            this.designerHomeSub.Name = "designerHomeSub";
            this.designerHomeSub.Size = new System.Drawing.Size(760, 28);
            this.designerHomeSub.Text = "Your games, store, wishlist, wallet and membership in one launcher.";
            this.designerContent.Controls.Add(this.designerHomeSub);
            this.designerHero = new System.Windows.Forms.Panel();
            this.designerHero.BackColor = System.Drawing.Color.FromArgb(74, 65, 220);
            this.designerHero.Location = new System.Drawing.Point(0, 94);
            this.designerHero.Name = "designerHero";
            this.designerHero.Size = new System.Drawing.Size(994, 170);
            this.designerContent.Controls.Add(this.designerHero);
            this.designerHeroPill = new System.Windows.Forms.Label();
            this.designerHeroPill.AutoSize = false;
            this.designerHeroPill.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerHeroPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerHeroPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerHeroPill.Location = new System.Drawing.Point(24, 20);
            this.designerHeroPill.Name = "designerHeroPill";
            this.designerHeroPill.Size = new System.Drawing.Size(86, 26);
            this.designerHeroPill.Text = "FEATURED";
            this.designerHeroPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerHero.Controls.Add(this.designerHeroPill);
            this.designerHeroTitle = new System.Windows.Forms.Label();
            this.designerHeroTitle.AutoSize = false;
            this.designerHeroTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerHeroTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerHeroTitle.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.designerHeroTitle.Location = new System.Drawing.Point(24, 56);
            this.designerHeroTitle.Name = "designerHeroTitle";
            this.designerHeroTitle.Size = new System.Drawing.Size(600, 42);
            this.designerHeroTitle.Text = "Continue your next adventure";
            this.designerHero.Controls.Add(this.designerHeroTitle);
            this.designerHeroSub = new System.Windows.Forms.Label();
            this.designerHeroSub.AutoSize = false;
            this.designerHeroSub.BackColor = System.Drawing.Color.Transparent;
            this.designerHeroSub.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerHeroSub.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this.designerHeroSub.Location = new System.Drawing.Point(26, 104);
            this.designerHeroSub.Name = "designerHeroSub";
            this.designerHeroSub.Size = new System.Drawing.Size(650, 28);
            this.designerHeroSub.Text = "Jump back into your library or browse today’s featured releases.";
            this.designerHero.Controls.Add(this.designerHeroSub);
            this.designerHeroButton = new System.Windows.Forms.Button();
            this.designerHeroButton.BackColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerHeroButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerHeroButton.ForeColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerHeroButton.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerHeroButton.Location = new System.Drawing.Point(820, 104);
            this.designerHeroButton.Name = "designerHeroButton";
            this.designerHeroButton.Size = new System.Drawing.Size(140, 40);
            this.designerHeroButton.Text = "OPEN STORE";
            this.designerHeroButton.UseVisualStyleBackColor = false;
            this.designerHero.Controls.Add(this.designerHeroButton);
            this.designerSectionTitle = new System.Windows.Forms.Label();
            this.designerSectionTitle.AutoSize = false;
            this.designerSectionTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSectionTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerSectionTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.designerSectionTitle.Location = new System.Drawing.Point(0, 292);
            this.designerSectionTitle.Name = "designerSectionTitle";
            this.designerSectionTitle.Size = new System.Drawing.Size(300, 34);
            this.designerSectionTitle.Text = "Quick Access";
            this.designerContent.Controls.Add(this.designerSectionTitle);
            this.designerQuick1 = new System.Windows.Forms.Panel();
            this.designerQuick1.BackColor = System.Drawing.Color.FromArgb(74, 65, 220);
            this.designerQuick1.Location = new System.Drawing.Point(0, 338);
            this.designerQuick1.Name = "designerQuick1";
            this.designerQuick1.Size = new System.Drawing.Size(306, 160);
            this.designerContent.Controls.Add(this.designerQuick1);
            this.designerQuick1Title = new System.Windows.Forms.Label();
            this.designerQuick1Title.AutoSize = false;
            this.designerQuick1Title.BackColor = System.Drawing.Color.Transparent;
            this.designerQuick1Title.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerQuick1Title.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerQuick1Title.Location = new System.Drawing.Point(18, 18);
            this.designerQuick1Title.Name = "designerQuick1Title";
            this.designerQuick1Title.Size = new System.Drawing.Size(250, 30);
            this.designerQuick1Title.Text = "Library";
            this.designerQuick1.Controls.Add(this.designerQuick1Title);
            this.designerQuick1Sub = new System.Windows.Forms.Label();
            this.designerQuick1Sub.AutoSize = false;
            this.designerQuick1Sub.BackColor = System.Drawing.Color.Transparent;
            this.designerQuick1Sub.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerQuick1Sub.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerQuick1Sub.Location = new System.Drawing.Point(18, 54);
            this.designerQuick1Sub.Name = "designerQuick1Sub";
            this.designerQuick1Sub.Size = new System.Drawing.Size(250, 24);
            this.designerQuick1Sub.Text = "Purchased games";
            this.designerQuick1.Controls.Add(this.designerQuick1Sub);
            this.designerQuick1Open = new System.Windows.Forms.Button();
            this.designerQuick1Open.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerQuick1Open.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerQuick1Open.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerQuick1Open.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerQuick1Open.Location = new System.Drawing.Point(18, 104);
            this.designerQuick1Open.Name = "designerQuick1Open";
            this.designerQuick1Open.Size = new System.Drawing.Size(110, 36);
            this.designerQuick1Open.Text = "OPEN";
            this.designerQuick1Open.UseVisualStyleBackColor = false;
            this.designerQuick1.Controls.Add(this.designerQuick1Open);
            this.designerQuick2 = new System.Windows.Forms.Panel();
            this.designerQuick2.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerQuick2.Location = new System.Drawing.Point(326, 338);
            this.designerQuick2.Name = "designerQuick2";
            this.designerQuick2.Size = new System.Drawing.Size(306, 160);
            this.designerContent.Controls.Add(this.designerQuick2);
            this.designerQuick2Title = new System.Windows.Forms.Label();
            this.designerQuick2Title.AutoSize = false;
            this.designerQuick2Title.BackColor = System.Drawing.Color.Transparent;
            this.designerQuick2Title.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerQuick2Title.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerQuick2Title.Location = new System.Drawing.Point(18, 18);
            this.designerQuick2Title.Name = "designerQuick2Title";
            this.designerQuick2Title.Size = new System.Drawing.Size(250, 30);
            this.designerQuick2Title.Text = "Wishlist";
            this.designerQuick2.Controls.Add(this.designerQuick2Title);
            this.designerQuick2Sub = new System.Windows.Forms.Label();
            this.designerQuick2Sub.AutoSize = false;
            this.designerQuick2Sub.BackColor = System.Drawing.Color.Transparent;
            this.designerQuick2Sub.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerQuick2Sub.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerQuick2Sub.Location = new System.Drawing.Point(18, 54);
            this.designerQuick2Sub.Name = "designerQuick2Sub";
            this.designerQuick2Sub.Size = new System.Drawing.Size(250, 24);
            this.designerQuick2Sub.Text = "Saved games";
            this.designerQuick2.Controls.Add(this.designerQuick2Sub);
            this.designerQuick2Open = new System.Windows.Forms.Button();
            this.designerQuick2Open.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerQuick2Open.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerQuick2Open.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerQuick2Open.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerQuick2Open.Location = new System.Drawing.Point(18, 104);
            this.designerQuick2Open.Name = "designerQuick2Open";
            this.designerQuick2Open.Size = new System.Drawing.Size(110, 36);
            this.designerQuick2Open.Text = "OPEN";
            this.designerQuick2Open.UseVisualStyleBackColor = false;
            this.designerQuick2.Controls.Add(this.designerQuick2Open);
            this.designerQuick3 = new System.Windows.Forms.Panel();
            this.designerQuick3.BackColor = System.Drawing.Color.FromArgb(72, 201, 154);
            this.designerQuick3.Location = new System.Drawing.Point(652, 338);
            this.designerQuick3.Name = "designerQuick3";
            this.designerQuick3.Size = new System.Drawing.Size(306, 160);
            this.designerContent.Controls.Add(this.designerQuick3);
            this.designerQuick3Title = new System.Windows.Forms.Label();
            this.designerQuick3Title.AutoSize = false;
            this.designerQuick3Title.BackColor = System.Drawing.Color.Transparent;
            this.designerQuick3Title.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerQuick3Title.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerQuick3Title.Location = new System.Drawing.Point(18, 18);
            this.designerQuick3Title.Name = "designerQuick3Title";
            this.designerQuick3Title.Size = new System.Drawing.Size(250, 30);
            this.designerQuick3Title.Text = "Wallet";
            this.designerQuick3.Controls.Add(this.designerQuick3Title);
            this.designerQuick3Sub = new System.Windows.Forms.Label();
            this.designerQuick3Sub.AutoSize = false;
            this.designerQuick3Sub.BackColor = System.Drawing.Color.Transparent;
            this.designerQuick3Sub.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerQuick3Sub.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerQuick3Sub.Location = new System.Drawing.Point(18, 54);
            this.designerQuick3Sub.Name = "designerQuick3Sub";
            this.designerQuick3Sub.Size = new System.Drawing.Size(250, 24);
            this.designerQuick3Sub.Text = "Balance & rewards";
            this.designerQuick3.Controls.Add(this.designerQuick3Sub);
            this.designerQuick3Open = new System.Windows.Forms.Button();
            this.designerQuick3Open.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerQuick3Open.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerQuick3Open.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerQuick3Open.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerQuick3Open.Location = new System.Drawing.Point(18, 104);
            this.designerQuick3Open.Name = "designerQuick3Open";
            this.designerQuick3Open.Size = new System.Drawing.Size(110, 36);
            this.designerQuick3Open.Text = "OPEN";
            this.designerQuick3Open.UseVisualStyleBackColor = false;
            this.designerQuick3.Controls.Add(this.designerQuick3Open);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(1280, 760);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(1180, 700);
            this.Name = "CustomerDashboardForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - Desktop Launcher";
        }

        private System.Windows.Forms.Panel designerSidebar;
        private System.Windows.Forms.Panel designerLogo;
        private System.Windows.Forms.Label designerLogoText;
        private System.Windows.Forms.Label designerBrand;
        private System.Windows.Forms.Label designerBrandSub;
        private System.Windows.Forms.Label designerBrowse;
        private System.Windows.Forms.Button designerBrowseNav1;
        private System.Windows.Forms.Button designerBrowseNav2;
        private System.Windows.Forms.Button designerBrowseNav3;
        private System.Windows.Forms.Button designerBrowseNav4;
        private System.Windows.Forms.Label designerAccount;
        private System.Windows.Forms.Button designerAccountNav1;
        private System.Windows.Forms.Button designerAccountNav2;
        private System.Windows.Forms.Button designerAccountNav3;
        private System.Windows.Forms.Panel designerUserCard;
        private System.Windows.Forms.Panel designerAvatar;
        private System.Windows.Forms.Label designerAvatarText;
        private System.Windows.Forms.Label designerUserName;
        private System.Windows.Forms.Label designerOnline;
        private System.Windows.Forms.Button designerLogout;
        private System.Windows.Forms.Panel designerMain;
        private System.Windows.Forms.Panel designerTopbar;
        private System.Windows.Forms.Label designerLive;
        private System.Windows.Forms.Button designerQuickStore;
        private System.Windows.Forms.Label designerCustomerPill;
        private System.Windows.Forms.Panel designerContent;
        private System.Windows.Forms.Label designerHomeTitle;
        private System.Windows.Forms.Label designerHomeSub;
        private System.Windows.Forms.Panel designerHero;
        private System.Windows.Forms.Label designerHeroPill;
        private System.Windows.Forms.Label designerHeroTitle;
        private System.Windows.Forms.Label designerHeroSub;
        private System.Windows.Forms.Button designerHeroButton;
        private System.Windows.Forms.Label designerSectionTitle;
        private System.Windows.Forms.Panel designerQuick1;
        private System.Windows.Forms.Label designerQuick1Title;
        private System.Windows.Forms.Label designerQuick1Sub;
        private System.Windows.Forms.Button designerQuick1Open;
        private System.Windows.Forms.Panel designerQuick2;
        private System.Windows.Forms.Label designerQuick2Title;
        private System.Windows.Forms.Label designerQuick2Sub;
        private System.Windows.Forms.Button designerQuick2Open;
        private System.Windows.Forms.Panel designerQuick3;
        private System.Windows.Forms.Label designerQuick3Title;
        private System.Windows.Forms.Label designerQuick3Sub;
        private System.Windows.Forms.Button designerQuick3Open;
    }
}
