namespace GameHub.Forms
{
    partial class DashboardForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerSidebar = new System.Windows.Forms.Panel();
            this.designerSidebar.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerSidebar.Location = new System.Drawing.Point(0, 0);
            this.designerSidebar.Name = "designerSidebar";
            this.designerSidebar.Size = new System.Drawing.Size(255, 760);
            this.Controls.Add(this.designerSidebar);
            this.designerLogo = new System.Windows.Forms.Panel();
            this.designerLogo.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerLogo.Location = new System.Drawing.Point(18, 18);
            this.designerLogo.Name = "designerLogo";
            this.designerLogo.Size = new System.Drawing.Size(48, 48);
            this.designerSidebar.Controls.Add(this.designerLogo);
            this.designerLogoText = new System.Windows.Forms.Label();
            this.designerLogoText.AutoSize = false;
            this.designerLogoText.BackColor = System.Drawing.Color.Transparent;
            this.designerLogoText.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerLogoText.Font = new System.Drawing.Font("Segoe UI", 19F, System.Drawing.FontStyle.Bold);
            this.designerLogoText.Location = new System.Drawing.Point(0, 4);
            this.designerLogoText.Name = "designerLogoText";
            this.designerLogoText.Size = new System.Drawing.Size(48, 40);
            this.designerLogoText.Text = "G";
            this.designerLogoText.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerLogo.Controls.Add(this.designerLogoText);
            this.designerBrand = new System.Windows.Forms.Label();
            this.designerBrand.AutoSize = false;
            this.designerBrand.BackColor = System.Drawing.Color.Transparent;
            this.designerBrand.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBrand.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.designerBrand.Location = new System.Drawing.Point(82, 17);
            this.designerBrand.Name = "designerBrand";
            this.designerBrand.Size = new System.Drawing.Size(155, 34);
            this.designerBrand.Text = "GameHub";
            this.designerSidebar.Controls.Add(this.designerBrand);
            this.designerRoleSub = new System.Windows.Forms.Label();
            this.designerRoleSub.AutoSize = false;
            this.designerRoleSub.BackColor = System.Drawing.Color.Transparent;
            this.designerRoleSub.ForeColor = System.Drawing.Color.FromArgb(116, 126, 158);
            this.designerRoleSub.Font = new System.Drawing.Font("Segoe UI", 7F, System.Drawing.FontStyle.Bold);
            this.designerRoleSub.Location = new System.Drawing.Point(83, 48);
            this.designerRoleSub.Name = "designerRoleSub";
            this.designerRoleSub.Size = new System.Drawing.Size(155, 20);
            this.designerRoleSub.Text = "ADMIN CONTROL CENTER";
            this.designerSidebar.Controls.Add(this.designerRoleSub);
            this.designerManagement = new System.Windows.Forms.Label();
            this.designerManagement.AutoSize = false;
            this.designerManagement.BackColor = System.Drawing.Color.Transparent;
            this.designerManagement.ForeColor = System.Drawing.Color.FromArgb(116, 126, 158);
            this.designerManagement.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerManagement.Location = new System.Drawing.Point(20, 93);
            this.designerManagement.Name = "designerManagement";
            this.designerManagement.Size = new System.Drawing.Size(180, 24);
            this.designerManagement.Text = "MANAGEMENT";
            this.designerSidebar.Controls.Add(this.designerManagement);
            this.designerNav1 = new System.Windows.Forms.Button();
            this.designerNav1.BackColor = System.Drawing.Color.FromArgb(74, 65, 220);
            this.designerNav1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerNav1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerNav1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerNav1.Location = new System.Drawing.Point(18, 125);
            this.designerNav1.Name = "designerNav1";
            this.designerNav1.Size = new System.Drawing.Size(219, 44);
            this.designerNav1.Text = "   Dashboard";
            this.designerNav1.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerNav1);
            this.designerNav2 = new System.Windows.Forms.Button();
            this.designerNav2.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerNav2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerNav2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerNav2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerNav2.Location = new System.Drawing.Point(18, 175);
            this.designerNav2.Name = "designerNav2";
            this.designerNav2.Size = new System.Drawing.Size(219, 44);
            this.designerNav2.Text = "   Manage Games";
            this.designerNav2.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerNav2);
            this.designerNav3 = new System.Windows.Forms.Button();
            this.designerNav3.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerNav3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerNav3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerNav3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerNav3.Location = new System.Drawing.Point(18, 225);
            this.designerNav3.Name = "designerNav3";
            this.designerNav3.Size = new System.Drawing.Size(219, 44);
            this.designerNav3.Text = "   Orders";
            this.designerNav3.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerNav3);
            this.designerNav4 = new System.Windows.Forms.Button();
            this.designerNav4.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerNav4.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerNav4.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerNav4.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerNav4.Location = new System.Drawing.Point(18, 275);
            this.designerNav4.Name = "designerNav4";
            this.designerNav4.Size = new System.Drawing.Size(219, 44);
            this.designerNav4.Text = "   Payments";
            this.designerNav4.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerNav4);
            this.designerNav5 = new System.Windows.Forms.Button();
            this.designerNav5.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerNav5.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerNav5.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerNav5.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerNav5.Location = new System.Drawing.Point(18, 325);
            this.designerNav5.Name = "designerNav5";
            this.designerNav5.Size = new System.Drawing.Size(219, 44);
            this.designerNav5.Text = "   Users & Staff";
            this.designerNav5.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerNav5);
            this.designerNav6 = new System.Windows.Forms.Button();
            this.designerNav6.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerNav6.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerNav6.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerNav6.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerNav6.Location = new System.Drawing.Point(18, 375);
            this.designerNav6.Name = "designerNav6";
            this.designerNav6.Size = new System.Drawing.Size(219, 44);
            this.designerNav6.Text = "   Reports";
            this.designerNav6.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerNav6);
            this.designerNav7 = new System.Windows.Forms.Button();
            this.designerNav7.BackColor = System.Drawing.Color.FromArgb(16, 19, 38);
            this.designerNav7.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerNav7.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerNav7.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerNav7.Location = new System.Drawing.Point(18, 425);
            this.designerNav7.Name = "designerNav7";
            this.designerNav7.Size = new System.Drawing.Size(219, 44);
            this.designerNav7.Text = "   Logout";
            this.designerNav7.UseVisualStyleBackColor = false;
            this.designerSidebar.Controls.Add(this.designerNav7);
            this.designerUserCard = new System.Windows.Forms.Panel();
            this.designerUserCard.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerUserCard.Location = new System.Drawing.Point(18, 650);
            this.designerUserCard.Name = "designerUserCard";
            this.designerUserCard.Size = new System.Drawing.Size(219, 82);
            this.designerSidebar.Controls.Add(this.designerUserCard);
            this.designerSigned = new System.Windows.Forms.Label();
            this.designerSigned.AutoSize = false;
            this.designerSigned.BackColor = System.Drawing.Color.Transparent;
            this.designerSigned.ForeColor = System.Drawing.Color.FromArgb(116, 126, 158);
            this.designerSigned.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerSigned.Location = new System.Drawing.Point(15, 9);
            this.designerSigned.Name = "designerSigned";
            this.designerSigned.Size = new System.Drawing.Size(180, 18);
            this.designerSigned.Text = "SIGNED IN";
            this.designerUserCard.Controls.Add(this.designerSigned);
            this.designerUser = new System.Windows.Forms.Label();
            this.designerUser.AutoSize = false;
            this.designerUser.BackColor = System.Drawing.Color.Transparent;
            this.designerUser.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerUser.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.designerUser.Location = new System.Drawing.Point(15, 29);
            this.designerUser.Name = "designerUser";
            this.designerUser.Size = new System.Drawing.Size(180, 24);
            this.designerUser.Text = "Administrator";
            this.designerUserCard.Controls.Add(this.designerUser);
            this.designerStatus = new System.Windows.Forms.Label();
            this.designerStatus.AutoSize = false;
            this.designerStatus.BackColor = System.Drawing.Color.Transparent;
            this.designerStatus.ForeColor = System.Drawing.Color.FromArgb(72, 201, 154);
            this.designerStatus.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerStatus.Location = new System.Drawing.Point(15, 54);
            this.designerStatus.Name = "designerStatus";
            this.designerStatus.Size = new System.Drawing.Size(185, 19);
            this.designerStatus.Text = "● Administrator";
            this.designerUserCard.Controls.Add(this.designerStatus);
            this.designerContent = new System.Windows.Forms.Panel();
            this.designerContent.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.designerContent.Location = new System.Drawing.Point(255, 0);
            this.designerContent.Name = "designerContent";
            this.designerContent.Size = new System.Drawing.Size(1025, 760);
            this.Controls.Add(this.designerContent);
            this.designerWelcome = new System.Windows.Forms.Label();
            this.designerWelcome.AutoSize = false;
            this.designerWelcome.BackColor = System.Drawing.Color.Transparent;
            this.designerWelcome.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerWelcome.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.designerWelcome.Location = new System.Drawing.Point(28, 24);
            this.designerWelcome.Name = "designerWelcome";
            this.designerWelcome.Size = new System.Drawing.Size(780, 45);
            this.designerWelcome.Text = "Welcome back, Administrator";
            this.designerContent.Controls.Add(this.designerWelcome);
            this.designerWelcomeSub = new System.Windows.Forms.Label();
            this.designerWelcomeSub.AutoSize = false;
            this.designerWelcomeSub.BackColor = System.Drawing.Color.Transparent;
            this.designerWelcomeSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerWelcomeSub.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this.designerWelcomeSub.Location = new System.Drawing.Point(30, 69);
            this.designerWelcomeSub.Name = "designerWelcomeSub";
            this.designerWelcomeSub.Size = new System.Drawing.Size(800, 28);
            this.designerWelcomeSub.Text = "Manage users, games, orders, payments and reports from one control center.";
            this.designerContent.Controls.Add(this.designerWelcomeSub);
            this.designerRolePill = new System.Windows.Forms.Label();
            this.designerRolePill.AutoSize = false;
            this.designerRolePill.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerRolePill.ForeColor = System.Drawing.Color.FromArgb(64, 214, 216);
            this.designerRolePill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerRolePill.Location = new System.Drawing.Point(860, 29);
            this.designerRolePill.Name = "designerRolePill";
            this.designerRolePill.Size = new System.Drawing.Size(110, 28);
            this.designerRolePill.Text = "ADMIN";
            this.designerRolePill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerContent.Controls.Add(this.designerRolePill);
            this.designerStat1 = new System.Windows.Forms.Panel();
            this.designerStat1.BackColor = System.Drawing.Color.FromArgb(74, 65, 220);
            this.designerStat1.Location = new System.Drawing.Point(28, 125);
            this.designerStat1.Name = "designerStat1";
            this.designerStat1.Size = new System.Drawing.Size(218, 104);
            this.designerContent.Controls.Add(this.designerStat1);
            this.designerStatTitle1 = new System.Windows.Forms.Label();
            this.designerStatTitle1.AutoSize = false;
            this.designerStatTitle1.BackColor = System.Drawing.Color.Transparent;
            this.designerStatTitle1.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerStatTitle1.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerStatTitle1.Location = new System.Drawing.Point(16, 15);
            this.designerStatTitle1.Name = "designerStatTitle1";
            this.designerStatTitle1.Size = new System.Drawing.Size(180, 22);
            this.designerStatTitle1.Text = "TOTAL GAMES";
            this.designerStat1.Controls.Add(this.designerStatTitle1);
            this.designerStatValue1 = new System.Windows.Forms.Label();
            this.designerStatValue1.AutoSize = false;
            this.designerStatValue1.BackColor = System.Drawing.Color.Transparent;
            this.designerStatValue1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStatValue1.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.designerStatValue1.Location = new System.Drawing.Point(16, 43);
            this.designerStatValue1.Name = "designerStatValue1";
            this.designerStatValue1.Size = new System.Drawing.Size(180, 42);
            this.designerStatValue1.Text = "128";
            this.designerStat1.Controls.Add(this.designerStatValue1);
            this.designerStat2 = new System.Windows.Forms.Panel();
            this.designerStat2.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerStat2.Location = new System.Drawing.Point(266, 125);
            this.designerStat2.Name = "designerStat2";
            this.designerStat2.Size = new System.Drawing.Size(218, 104);
            this.designerContent.Controls.Add(this.designerStat2);
            this.designerStatTitle2 = new System.Windows.Forms.Label();
            this.designerStatTitle2.AutoSize = false;
            this.designerStatTitle2.BackColor = System.Drawing.Color.Transparent;
            this.designerStatTitle2.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerStatTitle2.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerStatTitle2.Location = new System.Drawing.Point(16, 15);
            this.designerStatTitle2.Name = "designerStatTitle2";
            this.designerStatTitle2.Size = new System.Drawing.Size(180, 22);
            this.designerStatTitle2.Text = "TOTAL ORDERS";
            this.designerStat2.Controls.Add(this.designerStatTitle2);
            this.designerStatValue2 = new System.Windows.Forms.Label();
            this.designerStatValue2.AutoSize = false;
            this.designerStatValue2.BackColor = System.Drawing.Color.Transparent;
            this.designerStatValue2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStatValue2.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.designerStatValue2.Location = new System.Drawing.Point(16, 43);
            this.designerStatValue2.Name = "designerStatValue2";
            this.designerStatValue2.Size = new System.Drawing.Size(180, 42);
            this.designerStatValue2.Text = "1,284";
            this.designerStat2.Controls.Add(this.designerStatValue2);
            this.designerStat3 = new System.Windows.Forms.Panel();
            this.designerStat3.BackColor = System.Drawing.Color.FromArgb(72, 201, 154);
            this.designerStat3.Location = new System.Drawing.Point(504, 125);
            this.designerStat3.Name = "designerStat3";
            this.designerStat3.Size = new System.Drawing.Size(218, 104);
            this.designerContent.Controls.Add(this.designerStat3);
            this.designerStatTitle3 = new System.Windows.Forms.Label();
            this.designerStatTitle3.AutoSize = false;
            this.designerStatTitle3.BackColor = System.Drawing.Color.Transparent;
            this.designerStatTitle3.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerStatTitle3.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerStatTitle3.Location = new System.Drawing.Point(16, 15);
            this.designerStatTitle3.Name = "designerStatTitle3";
            this.designerStatTitle3.Size = new System.Drawing.Size(180, 22);
            this.designerStatTitle3.Text = "TOTAL REVENUE";
            this.designerStat3.Controls.Add(this.designerStatTitle3);
            this.designerStatValue3 = new System.Windows.Forms.Label();
            this.designerStatValue3.AutoSize = false;
            this.designerStatValue3.BackColor = System.Drawing.Color.Transparent;
            this.designerStatValue3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStatValue3.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.designerStatValue3.Location = new System.Drawing.Point(16, 43);
            this.designerStatValue3.Name = "designerStatValue3";
            this.designerStatValue3.Size = new System.Drawing.Size(180, 42);
            this.designerStatValue3.Text = "Tk 4.8M";
            this.designerStat3.Controls.Add(this.designerStatValue3);
            this.designerStat4 = new System.Windows.Forms.Panel();
            this.designerStat4.BackColor = System.Drawing.Color.FromArgb(58, 159, 255);
            this.designerStat4.Location = new System.Drawing.Point(742, 125);
            this.designerStat4.Name = "designerStat4";
            this.designerStat4.Size = new System.Drawing.Size(218, 104);
            this.designerContent.Controls.Add(this.designerStat4);
            this.designerStatTitle4 = new System.Windows.Forms.Label();
            this.designerStatTitle4.AutoSize = false;
            this.designerStatTitle4.BackColor = System.Drawing.Color.Transparent;
            this.designerStatTitle4.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerStatTitle4.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerStatTitle4.Location = new System.Drawing.Point(16, 15);
            this.designerStatTitle4.Name = "designerStatTitle4";
            this.designerStatTitle4.Size = new System.Drawing.Size(180, 22);
            this.designerStatTitle4.Text = "ACTIVE USERS";
            this.designerStat4.Controls.Add(this.designerStatTitle4);
            this.designerStatValue4 = new System.Windows.Forms.Label();
            this.designerStatValue4.AutoSize = false;
            this.designerStatValue4.BackColor = System.Drawing.Color.Transparent;
            this.designerStatValue4.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStatValue4.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.designerStatValue4.Location = new System.Drawing.Point(16, 43);
            this.designerStatValue4.Name = "designerStatValue4";
            this.designerStatValue4.Size = new System.Drawing.Size(180, 42);
            this.designerStatValue4.Text = "846";
            this.designerStat4.Controls.Add(this.designerStatValue4);
            this.designerRecentTitle = new System.Windows.Forms.Label();
            this.designerRecentTitle.AutoSize = false;
            this.designerRecentTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerRecentTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerRecentTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.designerRecentTitle.Location = new System.Drawing.Point(28, 260);
            this.designerRecentTitle.Name = "designerRecentTitle";
            this.designerRecentTitle.Size = new System.Drawing.Size(320, 36);
            this.designerRecentTitle.Text = "Recent Orders";
            this.designerContent.Controls.Add(this.designerRecentTitle);
            this.designerGridCard = new System.Windows.Forms.Panel();
            this.designerGridCard.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerGridCard.Location = new System.Drawing.Point(28, 307);
            this.designerGridCard.Name = "designerGridCard";
            this.designerGridCard.Size = new System.Drawing.Size(950, 400);
            this.designerContent.Controls.Add(this.designerGridCard);
            this._grid = new System.Windows.Forms.DataGridView();
            this._grid.AllowUserToAddRows = false;
            this._grid.AllowUserToDeleteRows = false;
            this._grid.BackgroundColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this._grid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._grid.ColumnHeadersHeight = 36;
            this._grid.Location = new System.Drawing.Point(18, 18);
            this._grid.Name = "_grid";
            this._grid.ReadOnly = true;
            this._grid.RowHeadersVisible = false;
            this._grid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._grid.Size = new System.Drawing.Size(914, 364);
            this.designerGridCard.Controls.Add(this._grid);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(1280, 760);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(1100, 700);
            this.Name = "DashboardForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - Admin Dashboard";
        }

        private System.Windows.Forms.Panel designerSidebar;
        private System.Windows.Forms.Panel designerLogo;
        private System.Windows.Forms.Label designerLogoText;
        private System.Windows.Forms.Label designerBrand;
        private System.Windows.Forms.Label designerRoleSub;
        private System.Windows.Forms.Label designerManagement;
        private System.Windows.Forms.Button designerNav1;
        private System.Windows.Forms.Button designerNav2;
        private System.Windows.Forms.Button designerNav3;
        private System.Windows.Forms.Button designerNav4;
        private System.Windows.Forms.Button designerNav5;
        private System.Windows.Forms.Button designerNav6;
        private System.Windows.Forms.Button designerNav7;
        private System.Windows.Forms.Panel designerUserCard;
        private System.Windows.Forms.Label designerSigned;
        private System.Windows.Forms.Label designerUser;
        private System.Windows.Forms.Label designerStatus;
        private System.Windows.Forms.Panel designerContent;
        private System.Windows.Forms.Label designerWelcome;
        private System.Windows.Forms.Label designerWelcomeSub;
        private System.Windows.Forms.Label designerRolePill;
        private System.Windows.Forms.Panel designerStat1;
        private System.Windows.Forms.Label designerStatTitle1;
        private System.Windows.Forms.Label designerStatValue1;
        private System.Windows.Forms.Panel designerStat2;
        private System.Windows.Forms.Label designerStatTitle2;
        private System.Windows.Forms.Label designerStatValue2;
        private System.Windows.Forms.Panel designerStat3;
        private System.Windows.Forms.Label designerStatTitle3;
        private System.Windows.Forms.Label designerStatValue3;
        private System.Windows.Forms.Panel designerStat4;
        private System.Windows.Forms.Label designerStatTitle4;
        private System.Windows.Forms.Label designerStatValue4;
        private System.Windows.Forms.Label designerRecentTitle;
        private System.Windows.Forms.Panel designerGridCard;
    }
}
