namespace GameHub.Forms
{
    partial class LibraryForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerTitle = new System.Windows.Forms.Label();
            this.designerTitle.AutoSize = false;
            this.designerTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.designerTitle.Location = new System.Drawing.Point(28, 22);
            this.designerTitle.Name = "designerTitle";
            this.designerTitle.Size = new System.Drawing.Size(480, 42);
            this.designerTitle.Text = "My Library";
            this.Controls.Add(this.designerTitle);
            this.designerSubtitle = new System.Windows.Forms.Label();
            this.designerSubtitle.AutoSize = false;
            this.designerSubtitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSubtitle.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSubtitle.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerSubtitle.Location = new System.Drawing.Point(30, 54);
            this.designerSubtitle.Name = "designerSubtitle";
            this.designerSubtitle.Size = new System.Drawing.Size(620, 28);
            this.designerSubtitle.Text = "Purchased games, activation keys and your reviews.";
            this.Controls.Add(this.designerSubtitle);
            this.designerBack = new System.Windows.Forms.Button();
            this.designerBack.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBack.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBack.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBack.Location = new System.Drawing.Point(956, 20);
            this.designerBack.Name = "designerBack";
            this.designerBack.Size = new System.Drawing.Size(96, 34);
            this.designerBack.Text = "←  Back";
            this.designerBack.UseVisualStyleBackColor = false;
            this.Controls.Add(this.designerBack);
            this.designerLibrary = new System.Windows.Forms.Panel();
            this.designerLibrary.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerLibrary.Location = new System.Drawing.Point(28, 94);
            this.designerLibrary.Name = "designerLibrary";
            this.designerLibrary.Size = new System.Drawing.Size(650, 528);
            this.Controls.Add(this.designerLibrary);
            this.designerLibraryPill = new System.Windows.Forms.Label();
            this.designerLibraryPill.AutoSize = false;
            this.designerLibraryPill.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerLibraryPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerLibraryPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerLibraryPill.Location = new System.Drawing.Point(18, 16);
            this.designerLibraryPill.Name = "designerLibraryPill";
            this.designerLibraryPill.Size = new System.Drawing.Size(76, 26);
            this.designerLibraryPill.Text = "LIBRARY";
            this.designerLibraryPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerLibrary.Controls.Add(this.designerLibraryPill);
            this.designerOwned = new System.Windows.Forms.Label();
            this.designerOwned.AutoSize = false;
            this.designerOwned.BackColor = System.Drawing.Color.Transparent;
            this.designerOwned.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerOwned.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerOwned.Location = new System.Drawing.Point(18, 54);
            this.designerOwned.Name = "designerOwned";
            this.designerOwned.Size = new System.Drawing.Size(280, 32);
            this.designerOwned.Text = "Owned Games";
            this.designerLibrary.Controls.Add(this.designerOwned);
            this.designerOwnedSub = new System.Windows.Forms.Label();
            this.designerOwnedSub.AutoSize = false;
            this.designerOwnedSub.BackColor = System.Drawing.Color.Transparent;
            this.designerOwnedSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerOwnedSub.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerOwnedSub.Location = new System.Drawing.Point(18, 84);
            this.designerOwnedSub.Name = "designerOwnedSub";
            this.designerOwnedSub.Size = new System.Drawing.Size(500, 24);
            this.designerOwnedSub.Text = "Select a game to write or update your review.";
            this.designerLibrary.Controls.Add(this.designerOwnedSub);
            this._libraryGrid = new System.Windows.Forms.DataGridView();
            this._libraryGrid.AllowUserToAddRows = false;
            this._libraryGrid.AllowUserToDeleteRows = false;
            this._libraryGrid.BackgroundColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this._libraryGrid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._libraryGrid.ColumnHeadersHeight = 36;
            this._libraryGrid.Location = new System.Drawing.Point(18, 112);
            this._libraryGrid.Name = "_libraryGrid";
            this._libraryGrid.ReadOnly = true;
            this._libraryGrid.RowHeadersVisible = false;
            this._libraryGrid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._libraryGrid.Size = new System.Drawing.Size(614, 396);
            this._libraryGrid.SelectionChanged += new System.EventHandler(this.LibraryGrid_SelectionChanged);
            this.designerLibrary.Controls.Add(this._libraryGrid);
            this.designerReview = new System.Windows.Forms.Panel();
            this.designerReview.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerReview.Location = new System.Drawing.Point(696, 94);
            this.designerReview.Name = "designerReview";
            this.designerReview.Size = new System.Drawing.Size(356, 528);
            this.Controls.Add(this.designerReview);
            this.designerReviewPill = new System.Windows.Forms.Label();
            this.designerReviewPill.AutoSize = false;
            this.designerReviewPill.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerReviewPill.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerReviewPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerReviewPill.Location = new System.Drawing.Point(18, 16);
            this.designerReviewPill.Name = "designerReviewPill";
            this.designerReviewPill.Size = new System.Drawing.Size(76, 26);
            this.designerReviewPill.Text = "REVIEWS";
            this.designerReviewPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerReview.Controls.Add(this.designerReviewPill);
            this.designerReviewTitle = new System.Windows.Forms.Label();
            this.designerReviewTitle.AutoSize = false;
            this.designerReviewTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerReviewTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerReviewTitle.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerReviewTitle.Location = new System.Drawing.Point(18, 54);
            this.designerReviewTitle.Name = "designerReviewTitle";
            this.designerReviewTitle.Size = new System.Drawing.Size(300, 32);
            this.designerReviewTitle.Text = "Review Selected Game";
            this.designerReview.Controls.Add(this.designerReviewTitle);
            this._selectedGame = new System.Windows.Forms.Label();
            this._selectedGame.AutoSize = false;
            this._selectedGame.BackColor = System.Drawing.Color.Transparent;
            this._selectedGame.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this._selectedGame.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this._selectedGame.Location = new System.Drawing.Point(18, 84);
            this._selectedGame.Name = "_selectedGame";
            this._selectedGame.Size = new System.Drawing.Size(310, 26);
            this._selectedGame.Text = "Select a game from your library";
            this.designerReview.Controls.Add(this._selectedGame);
            this.designerRatingLabel = new System.Windows.Forms.Label();
            this.designerRatingLabel.AutoSize = false;
            this.designerRatingLabel.BackColor = System.Drawing.Color.Transparent;
            this.designerRatingLabel.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerRatingLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerRatingLabel.Location = new System.Drawing.Point(18, 120);
            this.designerRatingLabel.Name = "designerRatingLabel";
            this.designerRatingLabel.Size = new System.Drawing.Size(120, 22);
            this.designerRatingLabel.Text = "Rating";
            this.designerReview.Controls.Add(this.designerRatingLabel);
            this._rating = new System.Windows.Forms.ComboBox();
            this._rating.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._rating.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._rating.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._rating.Location = new System.Drawing.Point(18, 144);
            this._rating.Name = "_rating";
            this._rating.Size = new System.Drawing.Size(110, 28);
            this._rating.Items.AddRange(new object[] { "1", "2", "3", "4", "5" });
            this._rating.SelectedIndex = 0;
            this.designerReview.Controls.Add(this._rating);
            this.designerCommentLabel = new System.Windows.Forms.Label();
            this.designerCommentLabel.AutoSize = false;
            this.designerCommentLabel.BackColor = System.Drawing.Color.Transparent;
            this.designerCommentLabel.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerCommentLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerCommentLabel.Location = new System.Drawing.Point(18, 184);
            this.designerCommentLabel.Name = "designerCommentLabel";
            this.designerCommentLabel.Size = new System.Drawing.Size(120, 22);
            this.designerCommentLabel.Text = "Comment";
            this.designerReview.Controls.Add(this.designerCommentLabel);
            this._comment = new System.Windows.Forms.TextBox();
            this._comment.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._comment.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._comment.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._comment.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._comment.Location = new System.Drawing.Point(18, 208);
            this._comment.Name = "_comment";
            this._comment.Size = new System.Drawing.Size(320, 82);
            this._comment.Multiline = true;
            this._comment.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.designerReview.Controls.Add(this._comment);
            this.designerSaveReview = new System.Windows.Forms.Button();
            this.designerSaveReview.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerSaveReview.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerSaveReview.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerSaveReview.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerSaveReview.Location = new System.Drawing.Point(18, 302);
            this.designerSaveReview.Name = "designerSaveReview";
            this.designerSaveReview.Size = new System.Drawing.Size(320, 36);
            this.designerSaveReview.Text = "SAVE REVIEW";
            this.designerSaveReview.UseVisualStyleBackColor = false;
            this.designerSaveReview.Click += new System.EventHandler(this.SaveReview_Click);
            this.designerReview.Controls.Add(this.designerSaveReview);
            this.designerCommunity = new System.Windows.Forms.Label();
            this.designerCommunity.AutoSize = false;
            this.designerCommunity.BackColor = System.Drawing.Color.Transparent;
            this.designerCommunity.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerCommunity.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.designerCommunity.Location = new System.Drawing.Point(18, 360);
            this.designerCommunity.Name = "designerCommunity";
            this.designerCommunity.Size = new System.Drawing.Size(250, 28);
            this.designerCommunity.Text = "Community Reviews";
            this.designerReview.Controls.Add(this.designerCommunity);
            this._reviewsGrid = new System.Windows.Forms.DataGridView();
            this._reviewsGrid.AllowUserToAddRows = false;
            this._reviewsGrid.AllowUserToDeleteRows = false;
            this._reviewsGrid.BackgroundColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this._reviewsGrid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._reviewsGrid.ColumnHeadersHeight = 36;
            this._reviewsGrid.Location = new System.Drawing.Point(18, 390);
            this._reviewsGrid.Name = "_reviewsGrid";
            this._reviewsGrid.ReadOnly = true;
            this._reviewsGrid.RowHeadersVisible = false;
            this._reviewsGrid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._reviewsGrid.Size = new System.Drawing.Size(320, 118);
            this.designerReview.Controls.Add(this._reviewsGrid);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(1080, 650);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(980, 600);
            this.Name = "LibraryForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - My Library";
        }

        private System.Windows.Forms.Label designerTitle;
        private System.Windows.Forms.Label designerSubtitle;
        private System.Windows.Forms.Button designerBack;
        private System.Windows.Forms.Panel designerLibrary;
        private System.Windows.Forms.Label designerLibraryPill;
        private System.Windows.Forms.Label designerOwned;
        private System.Windows.Forms.Label designerOwnedSub;
        private System.Windows.Forms.Panel designerReview;
        private System.Windows.Forms.Label designerReviewPill;
        private System.Windows.Forms.Label designerReviewTitle;
        private System.Windows.Forms.Label designerRatingLabel;
        private System.Windows.Forms.Label designerCommentLabel;
        private System.Windows.Forms.Button designerSaveReview;
        private System.Windows.Forms.Label designerCommunity;
    }
}
