namespace GameHub.Forms
{
    partial class LoginForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerShell = new System.Windows.Forms.Panel();
            this.designerShell.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerShell.Location = new System.Drawing.Point(30, 28);
            this.designerShell.Name = "designerShell";
            this.designerShell.Size = new System.Drawing.Size(1120, 650);
            this.Controls.Add(this.designerShell);
            this.designerFormSide = new System.Windows.Forms.Panel();
            this.designerFormSide.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerFormSide.Location = new System.Drawing.Point(0, 0);
            this.designerFormSide.Name = "designerFormSide";
            this.designerFormSide.Size = new System.Drawing.Size(500, 650);
            this.designerShell.Controls.Add(this.designerFormSide);
            this.designerArtwork = new System.Windows.Forms.Panel();
            this.designerArtwork.BackColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this.designerArtwork.Location = new System.Drawing.Point(500, 0);
            this.designerArtwork.Name = "designerArtwork";
            this.designerArtwork.Size = new System.Drawing.Size(620, 650);
            this.designerShell.Controls.Add(this.designerArtwork);
            this.designerLogo = new System.Windows.Forms.Panel();
            this.designerLogo.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerLogo.Location = new System.Drawing.Point(48, 36);
            this.designerLogo.Name = "designerLogo";
            this.designerLogo.Size = new System.Drawing.Size(48, 48);
            this.designerFormSide.Controls.Add(this.designerLogo);
            this.designerLogoText = new System.Windows.Forms.Label();
            this.designerLogoText.AutoSize = false;
            this.designerLogoText.BackColor = System.Drawing.Color.Transparent;
            this.designerLogoText.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerLogoText.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.designerLogoText.Location = new System.Drawing.Point(0, 3);
            this.designerLogoText.Name = "designerLogoText";
            this.designerLogoText.Size = new System.Drawing.Size(48, 40);
            this.designerLogoText.Text = "G";
            this.designerLogoText.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerLogo.Controls.Add(this.designerLogoText);
            this.designerBrand = new System.Windows.Forms.Label();
            this.designerBrand.AutoSize = false;
            this.designerBrand.BackColor = System.Drawing.Color.Transparent;
            this.designerBrand.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBrand.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.designerBrand.Location = new System.Drawing.Point(108, 43);
            this.designerBrand.Name = "designerBrand";
            this.designerBrand.Size = new System.Drawing.Size(160, 34);
            this.designerBrand.Text = "GameHub";
            this.designerFormSide.Controls.Add(this.designerBrand);
            this.designerWelcome = new System.Windows.Forms.Label();
            this.designerWelcome.AutoSize = false;
            this.designerWelcome.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerWelcome.ForeColor = System.Drawing.Color.FromArgb(64, 214, 216);
            this.designerWelcome.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerWelcome.Location = new System.Drawing.Point(48, 118);
            this.designerWelcome.Name = "designerWelcome";
            this.designerWelcome.Size = new System.Drawing.Size(112, 26);
            this.designerWelcome.Text = "WELCOME BACK";
            this.designerWelcome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerFormSide.Controls.Add(this.designerWelcome);
            this.lblAppName = new System.Windows.Forms.Label();
            this.lblAppName.AutoSize = false;
            this.lblAppName.BackColor = System.Drawing.Color.Transparent;
            this.lblAppName.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.lblAppName.Font = new System.Drawing.Font("Segoe UI", 27F, System.Drawing.FontStyle.Bold);
            this.lblAppName.Location = new System.Drawing.Point(48, 156);
            this.lblAppName.Name = "lblAppName";
            this.lblAppName.Size = new System.Drawing.Size(402, 58);
            this.lblAppName.Text = "Sign in";
            this.designerFormSide.Controls.Add(this.lblAppName);
            this.lblSub = new System.Windows.Forms.Label();
            this.lblSub.AutoSize = false;
            this.lblSub.BackColor = System.Drawing.Color.Transparent;
            this.lblSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.lblSub.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this.lblSub.Location = new System.Drawing.Point(50, 218);
            this.lblSub.Name = "lblSub";
            this.lblSub.Size = new System.Drawing.Size(400, 38);
            this.lblSub.Text = "Enter your GameHub username/email and password.";
            this.designerFormSide.Controls.Add(this.lblSub);
            this.lblUserId = new System.Windows.Forms.Label();
            this.lblUserId.AutoSize = false;
            this.lblUserId.BackColor = System.Drawing.Color.Transparent;
            this.lblUserId.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.lblUserId.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.lblUserId.Location = new System.Drawing.Point(50, 266);
            this.lblUserId.Name = "lblUserId";
            this.lblUserId.Size = new System.Drawing.Size(220, 22);
            this.lblUserId.Text = "Username or Email";
            this.designerFormSide.Controls.Add(this.lblUserId);
            this.txtUserId = new System.Windows.Forms.TextBox();
            this.txtUserId.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.txtUserId.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtUserId.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.txtUserId.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.txtUserId.Location = new System.Drawing.Point(50, 290);
            this.txtUserId.Name = "txtUserId";
            this.txtUserId.Size = new System.Drawing.Size(400, 44);
            this.designerFormSide.Controls.Add(this.txtUserId);
            this.lblPassword = new System.Windows.Forms.Label();
            this.lblPassword.AutoSize = false;
            this.lblPassword.BackColor = System.Drawing.Color.Transparent;
            this.lblPassword.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.lblPassword.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.lblPassword.Location = new System.Drawing.Point(50, 354);
            this.lblPassword.Name = "lblPassword";
            this.lblPassword.Size = new System.Drawing.Size(220, 22);
            this.lblPassword.Text = "Password";
            this.designerFormSide.Controls.Add(this.lblPassword);
            this.txtPassword = new System.Windows.Forms.TextBox();
            this.txtPassword.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.txtPassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPassword.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.txtPassword.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.txtPassword.Location = new System.Drawing.Point(50, 378);
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.Size = new System.Drawing.Size(400, 44);
            this.txtPassword.PasswordChar = '●';
            this.designerFormSide.Controls.Add(this.txtPassword);
            this._showPassword = new System.Windows.Forms.CheckBox();
            this._showPassword.AutoSize = false;
            this._showPassword.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._showPassword.Location = new System.Drawing.Point(50, 433);
            this._showPassword.Name = "_showPassword";
            this._showPassword.Size = new System.Drawing.Size(140, 24);
            this._showPassword.Text = "Show password";
            this._showPassword.UseVisualStyleBackColor = true;
            this.designerFormSide.Controls.Add(this._showPassword);
            this._forgot = new System.Windows.Forms.LinkLabel();
            this._forgot.AutoSize = false;
            this._forgot.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._forgot.LinkColor = System.Drawing.Color.FromArgb(58, 159, 255);
            this._forgot.Location = new System.Drawing.Point(316, 434);
            this._forgot.Name = "_forgot";
            this._forgot.Size = new System.Drawing.Size(134, 26);
            this._forgot.Text = "Forgot password?";
            this._forgot.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.ForgotPassword_LinkClicked);
            this.designerFormSide.Controls.Add(this._forgot);
            this.btnLogin = new System.Windows.Forms.Button();
            this.btnLogin.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.btnLogin.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLogin.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.btnLogin.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.btnLogin.Location = new System.Drawing.Point(50, 478);
            this.btnLogin.Name = "btnLogin";
            this.btnLogin.Size = new System.Drawing.Size(400, 44);
            this.btnLogin.Text = "SIGN IN";
            this.btnLogin.UseVisualStyleBackColor = false;
            this.btnLogin.Click += new System.EventHandler(this.btnLogin_Click);
            this.designerFormSide.Controls.Add(this.btnLogin);
            this.lnkRegister = new System.Windows.Forms.LinkLabel();
            this.lnkRegister.AutoSize = false;
            this.lnkRegister.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lnkRegister.LinkColor = System.Drawing.Color.FromArgb(58, 159, 255);
            this.lnkRegister.Location = new System.Drawing.Point(50, 548);
            this.lnkRegister.Name = "lnkRegister";
            this.lnkRegister.Size = new System.Drawing.Size(400, 30);
            this.lnkRegister.Text = "New to GameHub? Create account";
            this.lnkRegister.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.lnkRegister_LinkClicked);
            this.designerFormSide.Controls.Add(this.lnkRegister);
            this.lblBrand = new System.Windows.Forms.Label();
            this.lblBrand.AutoSize = false;
            this.lblBrand.BackColor = System.Drawing.Color.Transparent;
            this.lblBrand.ForeColor = System.Drawing.Color.FromArgb(116, 126, 158);
            this.lblBrand.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.lblBrand.Location = new System.Drawing.Point(50, 592);
            this.lblBrand.Name = "lblBrand";
            this.lblBrand.Size = new System.Drawing.Size(330, 22);
            this.lblBrand.Text = "GameHub secure desktop authentication";
            this.designerFormSide.Controls.Add(this.lblBrand);
            this.designerArtTitle = new System.Windows.Forms.Label();
            this.designerArtTitle.AutoSize = false;
            this.designerArtTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerArtTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerArtTitle.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
            this.designerArtTitle.Location = new System.Drawing.Point(48, 76);
            this.designerArtTitle.Name = "designerArtTitle";
            this.designerArtTitle.Size = new System.Drawing.Size(510, 92);
            this.designerArtTitle.Text = "YOUR GAME LIBRARY\r\nIN ONE PLACE";
            this.designerArtwork.Controls.Add(this.designerArtTitle);
            this.designerArtSub = new System.Windows.Forms.Label();
            this.designerArtSub.AutoSize = false;
            this.designerArtSub.BackColor = System.Drawing.Color.Transparent;
            this.designerArtSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerArtSub.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular);
            this.designerArtSub.Location = new System.Drawing.Point(50, 180);
            this.designerArtSub.Name = "designerArtSub";
            this.designerArtSub.Size = new System.Drawing.Size(500, 64);
            this.designerArtSub.Text = "Discover games, build your wishlist, manage your wallet and launch from one desktop hub.";
            this.designerArtwork.Controls.Add(this.designerArtSub);
            this.designerGameCard1 = new System.Windows.Forms.Panel();
            this.designerGameCard1.BackColor = System.Drawing.Color.FromArgb(74, 65, 220);
            this.designerGameCard1.Location = new System.Drawing.Point(50, 286);
            this.designerGameCard1.Name = "designerGameCard1";
            this.designerGameCard1.Size = new System.Drawing.Size(146, 190);
            this.designerArtwork.Controls.Add(this.designerGameCard1);
            this.designerGameCard1Title = new System.Windows.Forms.Label();
            this.designerGameCard1Title.AutoSize = false;
            this.designerGameCard1Title.BackColor = System.Drawing.Color.Transparent;
            this.designerGameCard1Title.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerGameCard1Title.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.designerGameCard1Title.Location = new System.Drawing.Point(12, 126);
            this.designerGameCard1Title.Name = "designerGameCard1Title";
            this.designerGameCard1Title.Size = new System.Drawing.Size(120, 26);
            this.designerGameCard1Title.Text = "ACTION";
            this.designerGameCard1.Controls.Add(this.designerGameCard1Title);
            this.designerGameCard1Meta = new System.Windows.Forms.Label();
            this.designerGameCard1Meta.AutoSize = false;
            this.designerGameCard1Meta.BackColor = System.Drawing.Color.Transparent;
            this.designerGameCard1Meta.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerGameCard1Meta.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerGameCard1Meta.Location = new System.Drawing.Point(12, 154);
            this.designerGameCard1Meta.Name = "designerGameCard1Meta";
            this.designerGameCard1Meta.Size = new System.Drawing.Size(120, 22);
            this.designerGameCard1Meta.Text = "Featured";
            this.designerGameCard1.Controls.Add(this.designerGameCard1Meta);
            this.designerGameCard2 = new System.Windows.Forms.Panel();
            this.designerGameCard2.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerGameCard2.Location = new System.Drawing.Point(226, 286);
            this.designerGameCard2.Name = "designerGameCard2";
            this.designerGameCard2.Size = new System.Drawing.Size(146, 190);
            this.designerArtwork.Controls.Add(this.designerGameCard2);
            this.designerGameCard2Title = new System.Windows.Forms.Label();
            this.designerGameCard2Title.AutoSize = false;
            this.designerGameCard2Title.BackColor = System.Drawing.Color.Transparent;
            this.designerGameCard2Title.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerGameCard2Title.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.designerGameCard2Title.Location = new System.Drawing.Point(12, 126);
            this.designerGameCard2Title.Name = "designerGameCard2Title";
            this.designerGameCard2Title.Size = new System.Drawing.Size(120, 26);
            this.designerGameCard2Title.Text = "RACING";
            this.designerGameCard2.Controls.Add(this.designerGameCard2Title);
            this.designerGameCard2Meta = new System.Windows.Forms.Label();
            this.designerGameCard2Meta.AutoSize = false;
            this.designerGameCard2Meta.BackColor = System.Drawing.Color.Transparent;
            this.designerGameCard2Meta.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerGameCard2Meta.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerGameCard2Meta.Location = new System.Drawing.Point(12, 154);
            this.designerGameCard2Meta.Name = "designerGameCard2Meta";
            this.designerGameCard2Meta.Size = new System.Drawing.Size(120, 22);
            this.designerGameCard2Meta.Text = "New release";
            this.designerGameCard2.Controls.Add(this.designerGameCard2Meta);
            this.designerGameCard3 = new System.Windows.Forms.Panel();
            this.designerGameCard3.BackColor = System.Drawing.Color.FromArgb(58, 159, 255);
            this.designerGameCard3.Location = new System.Drawing.Point(402, 286);
            this.designerGameCard3.Name = "designerGameCard3";
            this.designerGameCard3.Size = new System.Drawing.Size(146, 190);
            this.designerArtwork.Controls.Add(this.designerGameCard3);
            this.designerGameCard3Title = new System.Windows.Forms.Label();
            this.designerGameCard3Title.AutoSize = false;
            this.designerGameCard3Title.BackColor = System.Drawing.Color.Transparent;
            this.designerGameCard3Title.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerGameCard3Title.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.designerGameCard3Title.Location = new System.Drawing.Point(12, 126);
            this.designerGameCard3Title.Name = "designerGameCard3Title";
            this.designerGameCard3Title.Size = new System.Drawing.Size(120, 26);
            this.designerGameCard3Title.Text = "ADVENTURE";
            this.designerGameCard3.Controls.Add(this.designerGameCard3Title);
            this.designerGameCard3Meta = new System.Windows.Forms.Label();
            this.designerGameCard3Meta.AutoSize = false;
            this.designerGameCard3Meta.BackColor = System.Drawing.Color.Transparent;
            this.designerGameCard3Meta.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerGameCard3Meta.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerGameCard3Meta.Location = new System.Drawing.Point(12, 154);
            this.designerGameCard3Meta.Name = "designerGameCard3Meta";
            this.designerGameCard3Meta.Size = new System.Drawing.Size(120, 22);
            this.designerGameCard3Meta.Text = "Top rated";
            this.designerGameCard3.Controls.Add(this.designerGameCard3Meta);
            this.designerSecure = new System.Windows.Forms.Label();
            this.designerSecure.AutoSize = false;
            this.designerSecure.BackColor = System.Drawing.Color.Transparent;
            this.designerSecure.ForeColor = System.Drawing.Color.FromArgb(72, 201, 154);
            this.designerSecure.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerSecure.Location = new System.Drawing.Point(50, 532);
            this.designerSecure.Name = "designerSecure";
            this.designerSecure.Size = new System.Drawing.Size(500, 30);
            this.designerSecure.Text = "SQL LIVE  •  SECURE ACCESS  •  GAMEHUB PASS";
            this.designerArtwork.Controls.Add(this.designerSecure);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(1180, 720);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(1180, 720);
            this.Name = "LoginForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - Sign In";
        }

        private System.Windows.Forms.Panel designerShell;
        private System.Windows.Forms.Panel designerFormSide;
        private System.Windows.Forms.Panel designerArtwork;
        private System.Windows.Forms.Panel designerLogo;
        private System.Windows.Forms.Label designerLogoText;
        private System.Windows.Forms.Label designerBrand;
        private System.Windows.Forms.Label designerWelcome;
        private System.Windows.Forms.Label lblAppName;
        private System.Windows.Forms.Label lblSub;
        private System.Windows.Forms.Label lblUserId;
        private System.Windows.Forms.TextBox txtUserId;
        private System.Windows.Forms.Label lblPassword;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.Button btnLogin;
        private System.Windows.Forms.LinkLabel lnkRegister;
        private System.Windows.Forms.Label lblBrand;
        private System.Windows.Forms.Label designerArtTitle;
        private System.Windows.Forms.Label designerArtSub;
        private System.Windows.Forms.Panel designerGameCard1;
        private System.Windows.Forms.Label designerGameCard1Title;
        private System.Windows.Forms.Label designerGameCard1Meta;
        private System.Windows.Forms.Panel designerGameCard2;
        private System.Windows.Forms.Label designerGameCard2Title;
        private System.Windows.Forms.Label designerGameCard2Meta;
        private System.Windows.Forms.Panel designerGameCard3;
        private System.Windows.Forms.Label designerGameCard3Title;
        private System.Windows.Forms.Label designerGameCard3Meta;
        private System.Windows.Forms.Label designerSecure;
    }
}
