namespace GameHub.Forms
{
    partial class ManageGamesForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerTitle = new System.Windows.Forms.Label();
            this.designerTitle.AutoSize = false;
            this.designerTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTitle.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.designerTitle.Location = new System.Drawing.Point(28, 20);
            this.designerTitle.Name = "designerTitle";
            this.designerTitle.Size = new System.Drawing.Size(700, 44);
            this.designerTitle.Text = "Game Library & Inventory";
            this.Controls.Add(this.designerTitle);
            this.designerSubtitle = new System.Windows.Forms.Label();
            this.designerSubtitle.AutoSize = false;
            this.designerSubtitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSubtitle.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSubtitle.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this.designerSubtitle.Location = new System.Drawing.Point(30, 62);
            this.designerSubtitle.Name = "designerSubtitle";
            this.designerSubtitle.Size = new System.Drawing.Size(800, 28);
            this.designerSubtitle.Text = "Add games, edit catalog details and maintain inventory levels.";
            this.Controls.Add(this.designerSubtitle);
            this.designerBack = new System.Windows.Forms.Button();
            this.designerBack.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBack.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBack.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBack.Location = new System.Drawing.Point(1130, 22);
            this.designerBack.Name = "designerBack";
            this.designerBack.Size = new System.Drawing.Size(112, 38);
            this.designerBack.Text = "←  BACK";
            this.designerBack.UseVisualStyleBackColor = false;
            this.Controls.Add(this.designerBack);
            this.designerSearchCard = new System.Windows.Forms.Panel();
            this.designerSearchCard.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerSearchCard.Location = new System.Drawing.Point(28, 104);
            this.designerSearchCard.Name = "designerSearchCard";
            this.designerSearchCard.Size = new System.Drawing.Size(1224, 62);
            this.Controls.Add(this.designerSearchCard);
            this.designerSearchLabel = new System.Windows.Forms.Label();
            this.designerSearchLabel.AutoSize = false;
            this.designerSearchLabel.BackColor = System.Drawing.Color.Transparent;
            this.designerSearchLabel.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSearchLabel.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerSearchLabel.Location = new System.Drawing.Point(16, 15);
            this.designerSearchLabel.Name = "designerSearchLabel";
            this.designerSearchLabel.Size = new System.Drawing.Size(72, 30);
            this.designerSearchLabel.Text = "SEARCH";
            this.designerSearchCard.Controls.Add(this.designerSearchLabel);
            this._txtSearch = new System.Windows.Forms.TextBox();
            this._txtSearch.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtSearch.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtSearch.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtSearch.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtSearch.Location = new System.Drawing.Point(92, 14);
            this._txtSearch.Name = "_txtSearch";
            this._txtSearch.Size = new System.Drawing.Size(850, 34);
            this.designerSearchCard.Controls.Add(this._txtSearch);
            this.designerSearchButton = new System.Windows.Forms.Button();
            this.designerSearchButton.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerSearchButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerSearchButton.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerSearchButton.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerSearchButton.Location = new System.Drawing.Point(954, 13);
            this.designerSearchButton.Name = "designerSearchButton";
            this.designerSearchButton.Size = new System.Drawing.Size(110, 36);
            this.designerSearchButton.Text = "SEARCH";
            this.designerSearchButton.UseVisualStyleBackColor = false;
            this.designerSearchCard.Controls.Add(this.designerSearchButton);
            this.designerShowAll = new System.Windows.Forms.Button();
            this.designerShowAll.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerShowAll.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerShowAll.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerShowAll.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerShowAll.Location = new System.Drawing.Point(1076, 13);
            this.designerShowAll.Name = "designerShowAll";
            this.designerShowAll.Size = new System.Drawing.Size(130, 36);
            this.designerShowAll.Text = "SHOW ALL";
            this.designerShowAll.UseVisualStyleBackColor = false;
            this.designerSearchCard.Controls.Add(this.designerShowAll);
            this.designerEditor = new System.Windows.Forms.Panel();
            this.designerEditor.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerEditor.Location = new System.Drawing.Point(28, 184);
            this.designerEditor.Name = "designerEditor";
            this.designerEditor.Size = new System.Drawing.Size(430, 548);
            this.Controls.Add(this.designerEditor);
            this.designerEditorPill = new System.Windows.Forms.Label();
            this.designerEditorPill.AutoSize = false;
            this.designerEditorPill.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerEditorPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerEditorPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerEditorPill.Location = new System.Drawing.Point(20, 16);
            this.designerEditorPill.Name = "designerEditorPill";
            this.designerEditorPill.Size = new System.Drawing.Size(74, 26);
            this.designerEditorPill.Text = "EDITOR";
            this.designerEditorPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerEditor.Controls.Add(this.designerEditorPill);
            this.designerEditorTitle = new System.Windows.Forms.Label();
            this.designerEditorTitle.AutoSize = false;
            this.designerEditorTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerEditorTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerEditorTitle.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerEditorTitle.Location = new System.Drawing.Point(20, 50);
            this.designerEditorTitle.Name = "designerEditorTitle";
            this.designerEditorTitle.Size = new System.Drawing.Size(300, 34);
            this.designerEditorTitle.Text = "Game Details";
            this.designerEditor.Controls.Add(this.designerEditorTitle);
            this.designerMgLabel1 = new System.Windows.Forms.Label();
            this.designerMgLabel1.AutoSize = false;
            this.designerMgLabel1.BackColor = System.Drawing.Color.Transparent;
            this.designerMgLabel1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerMgLabel1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerMgLabel1.Location = new System.Drawing.Point(20, 84);
            this.designerMgLabel1.Name = "designerMgLabel1";
            this.designerMgLabel1.Size = new System.Drawing.Size(390, 22);
            this.designerMgLabel1.Text = "Title";
            this.designerEditor.Controls.Add(this.designerMgLabel1);
            this._txtTitle = new System.Windows.Forms.TextBox();
            this._txtTitle.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtTitle.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtTitle.Location = new System.Drawing.Point(20, 108);
            this._txtTitle.Name = "_txtTitle";
            this._txtTitle.Size = new System.Drawing.Size(390, 34);
            this.designerEditor.Controls.Add(this._txtTitle);
            this.designerMgLabel2 = new System.Windows.Forms.Label();
            this.designerMgLabel2.AutoSize = false;
            this.designerMgLabel2.BackColor = System.Drawing.Color.Transparent;
            this.designerMgLabel2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerMgLabel2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerMgLabel2.Location = new System.Drawing.Point(20, 156);
            this.designerMgLabel2.Name = "designerMgLabel2";
            this.designerMgLabel2.Size = new System.Drawing.Size(390, 22);
            this.designerMgLabel2.Text = "Description";
            this.designerEditor.Controls.Add(this.designerMgLabel2);
            this._txtDescription = new System.Windows.Forms.TextBox();
            this._txtDescription.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtDescription.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtDescription.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtDescription.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtDescription.Location = new System.Drawing.Point(20, 180);
            this._txtDescription.Name = "_txtDescription";
            this._txtDescription.Size = new System.Drawing.Size(390, 78);
            this._txtDescription.Multiline = true;
            this._txtDescription.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.designerEditor.Controls.Add(this._txtDescription);
            this.designerMgLabel3 = new System.Windows.Forms.Label();
            this.designerMgLabel3.AutoSize = false;
            this.designerMgLabel3.BackColor = System.Drawing.Color.Transparent;
            this.designerMgLabel3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerMgLabel3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerMgLabel3.Location = new System.Drawing.Point(20, 274);
            this.designerMgLabel3.Name = "designerMgLabel3";
            this.designerMgLabel3.Size = new System.Drawing.Size(390, 22);
            this.designerMgLabel3.Text = "Genre";
            this.designerEditor.Controls.Add(this.designerMgLabel3);
            this._cboGenre = new System.Windows.Forms.ComboBox();
            this._cboGenre.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._cboGenre.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._cboGenre.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._cboGenre.Location = new System.Drawing.Point(20, 298);
            this._cboGenre.Name = "_cboGenre";
            this._cboGenre.Size = new System.Drawing.Size(390, 32);
            this._cboGenre.Items.AddRange(new object[] { "Select..." });
            this._cboGenre.SelectedIndex = 0;
            this.designerEditor.Controls.Add(this._cboGenre);
            this.designerMgLabel4 = new System.Windows.Forms.Label();
            this.designerMgLabel4.AutoSize = false;
            this.designerMgLabel4.BackColor = System.Drawing.Color.Transparent;
            this.designerMgLabel4.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerMgLabel4.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerMgLabel4.Location = new System.Drawing.Point(20, 346);
            this.designerMgLabel4.Name = "designerMgLabel4";
            this.designerMgLabel4.Size = new System.Drawing.Size(390, 22);
            this.designerMgLabel4.Text = "Publisher";
            this.designerEditor.Controls.Add(this.designerMgLabel4);
            this._cboPublisher = new System.Windows.Forms.ComboBox();
            this._cboPublisher.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._cboPublisher.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._cboPublisher.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._cboPublisher.Location = new System.Drawing.Point(20, 370);
            this._cboPublisher.Name = "_cboPublisher";
            this._cboPublisher.Size = new System.Drawing.Size(390, 32);
            this._cboPublisher.Items.AddRange(new object[] { "Select..." });
            this._cboPublisher.SelectedIndex = 0;
            this.designerEditor.Controls.Add(this._cboPublisher);
            this.designerMgLabel5 = new System.Windows.Forms.Label();
            this.designerMgLabel5.AutoSize = false;
            this.designerMgLabel5.BackColor = System.Drawing.Color.Transparent;
            this.designerMgLabel5.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerMgLabel5.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerMgLabel5.Location = new System.Drawing.Point(20, 418);
            this.designerMgLabel5.Name = "designerMgLabel5";
            this.designerMgLabel5.Size = new System.Drawing.Size(180, 22);
            this.designerMgLabel5.Text = "Price (BDT)";
            this.designerEditor.Controls.Add(this.designerMgLabel5);
            this._txtPrice = new System.Windows.Forms.TextBox();
            this._txtPrice.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtPrice.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtPrice.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtPrice.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtPrice.Location = new System.Drawing.Point(20, 442);
            this._txtPrice.Name = "_txtPrice";
            this._txtPrice.Size = new System.Drawing.Size(180, 32);
            this.designerEditor.Controls.Add(this._txtPrice);
            this.designerMgLabel6 = new System.Windows.Forms.Label();
            this.designerMgLabel6.AutoSize = false;
            this.designerMgLabel6.BackColor = System.Drawing.Color.Transparent;
            this.designerMgLabel6.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerMgLabel6.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerMgLabel6.Location = new System.Drawing.Point(230, 418);
            this.designerMgLabel6.Name = "designerMgLabel6";
            this.designerMgLabel6.Size = new System.Drawing.Size(180, 22);
            this.designerMgLabel6.Text = "Stock";
            this.designerEditor.Controls.Add(this.designerMgLabel6);
            this._txtStock = new System.Windows.Forms.TextBox();
            this._txtStock.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtStock.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtStock.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtStock.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtStock.Location = new System.Drawing.Point(230, 442);
            this._txtStock.Name = "_txtStock";
            this._txtStock.Size = new System.Drawing.Size(180, 32);
            this.designerEditor.Controls.Add(this._txtStock);
            this.designerReleaseLabel = new System.Windows.Forms.Label();
            this.designerReleaseLabel.AutoSize = false;
            this.designerReleaseLabel.BackColor = System.Drawing.Color.Transparent;
            this.designerReleaseLabel.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerReleaseLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerReleaseLabel.Location = new System.Drawing.Point(20, 486);
            this.designerReleaseLabel.Name = "designerReleaseLabel";
            this.designerReleaseLabel.Size = new System.Drawing.Size(180, 22);
            this.designerReleaseLabel.Text = "Release Date";
            this.designerEditor.Controls.Add(this.designerReleaseLabel);
            this._releaseDate = new System.Windows.Forms.DateTimePicker();
            this._releaseDate.Location = new System.Drawing.Point(20, 508);
            this._releaseDate.Name = "_releaseDate";
            this._releaseDate.Size = new System.Drawing.Size(390, 28);
            this.designerEditor.Controls.Add(this._releaseDate);
            this.designerAdd = new System.Windows.Forms.Button();
            this.designerAdd.BackColor = System.Drawing.Color.FromArgb(72, 201, 154);
            this.designerAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerAdd.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerAdd.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerAdd.Location = new System.Drawing.Point(20, 548);
            this.designerAdd.Name = "designerAdd";
            this.designerAdd.Size = new System.Drawing.Size(82, 36);
            this.designerAdd.Text = "ADD";
            this.designerAdd.UseVisualStyleBackColor = false;
            this.designerAdd.Click += new System.EventHandler(this.BtnAdd_Click);
            this.designerEditor.Controls.Add(this.designerAdd);
            this.designerUpdate = new System.Windows.Forms.Button();
            this.designerUpdate.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerUpdate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerUpdate.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerUpdate.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerUpdate.Location = new System.Drawing.Point(110, 548);
            this.designerUpdate.Name = "designerUpdate";
            this.designerUpdate.Size = new System.Drawing.Size(96, 36);
            this.designerUpdate.Text = "UPDATE";
            this.designerUpdate.UseVisualStyleBackColor = false;
            this.designerUpdate.Click += new System.EventHandler(this.BtnUpdate_Click);
            this.designerEditor.Controls.Add(this.designerUpdate);
            this.designerDeactivate = new System.Windows.Forms.Button();
            this.designerDeactivate.BackColor = System.Drawing.Color.FromArgb(238, 93, 111);
            this.designerDeactivate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerDeactivate.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerDeactivate.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerDeactivate.Location = new System.Drawing.Point(214, 548);
            this.designerDeactivate.Name = "designerDeactivate";
            this.designerDeactivate.Size = new System.Drawing.Size(120, 36);
            this.designerDeactivate.Text = "DEACTIVATE";
            this.designerDeactivate.UseVisualStyleBackColor = false;
            this.designerDeactivate.Click += new System.EventHandler(this.BtnDelete_Click);
            this.designerEditor.Controls.Add(this.designerDeactivate);
            this.designerClear = new System.Windows.Forms.Button();
            this.designerClear.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerClear.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerClear.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerClear.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerClear.Location = new System.Drawing.Point(342, 548);
            this.designerClear.Name = "designerClear";
            this.designerClear.Size = new System.Drawing.Size(68, 36);
            this.designerClear.Text = "CLEAR";
            this.designerClear.UseVisualStyleBackColor = false;
            this.designerEditor.Controls.Add(this.designerClear);
            this.designerCatalog = new System.Windows.Forms.Panel();
            this.designerCatalog.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerCatalog.Location = new System.Drawing.Point(478, 184);
            this.designerCatalog.Name = "designerCatalog";
            this.designerCatalog.Size = new System.Drawing.Size(774, 548);
            this.Controls.Add(this.designerCatalog);
            this.designerCatalogPill = new System.Windows.Forms.Label();
            this.designerCatalogPill.AutoSize = false;
            this.designerCatalogPill.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerCatalogPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerCatalogPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerCatalogPill.Location = new System.Drawing.Point(18, 15);
            this.designerCatalogPill.Name = "designerCatalogPill";
            this.designerCatalogPill.Size = new System.Drawing.Size(82, 26);
            this.designerCatalogPill.Text = "CATALOG";
            this.designerCatalogPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerCatalog.Controls.Add(this.designerCatalogPill);
            this.designerCatalogTitle = new System.Windows.Forms.Label();
            this.designerCatalogTitle.AutoSize = false;
            this.designerCatalogTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerCatalogTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerCatalogTitle.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerCatalogTitle.Location = new System.Drawing.Point(18, 48);
            this.designerCatalogTitle.Name = "designerCatalogTitle";
            this.designerCatalogTitle.Size = new System.Drawing.Size(310, 34);
            this.designerCatalogTitle.Text = "Game Library";
            this.designerCatalog.Controls.Add(this.designerCatalogTitle);
            this.designerCatalogSub = new System.Windows.Forms.Label();
            this.designerCatalogSub.AutoSize = false;
            this.designerCatalogSub.BackColor = System.Drawing.Color.Transparent;
            this.designerCatalogSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerCatalogSub.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerCatalogSub.Location = new System.Drawing.Point(18, 78);
            this.designerCatalogSub.Name = "designerCatalogSub";
            this.designerCatalogSub.Size = new System.Drawing.Size(420, 24);
            this.designerCatalogSub.Text = "Active games and inventory details";
            this.designerCatalog.Controls.Add(this.designerCatalogSub);
            this._grid = new System.Windows.Forms.DataGridView();
            this._grid.AllowUserToAddRows = false;
            this._grid.AllowUserToDeleteRows = false;
            this._grid.BackgroundColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this._grid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._grid.ColumnHeadersHeight = 36;
            this._grid.Location = new System.Drawing.Point(18, 112);
            this._grid.Name = "_grid";
            this._grid.ReadOnly = true;
            this._grid.RowHeadersVisible = false;
            this._grid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._grid.Size = new System.Drawing.Size(738, 416);
            this._grid.SelectionChanged += new System.EventHandler(this.Grid_SelectionChanged);
            this.designerCatalog.Controls.Add(this._grid);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(1280, 760);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(1050, 700);
            this.Name = "ManageGamesForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - Manage Games";
        }

        private System.Windows.Forms.Label designerTitle;
        private System.Windows.Forms.Label designerSubtitle;
        private System.Windows.Forms.Button designerBack;
        private System.Windows.Forms.Panel designerSearchCard;
        private System.Windows.Forms.Label designerSearchLabel;
        private System.Windows.Forms.Button designerSearchButton;
        private System.Windows.Forms.Button designerShowAll;
        private System.Windows.Forms.Panel designerEditor;
        private System.Windows.Forms.Label designerEditorPill;
        private System.Windows.Forms.Label designerEditorTitle;
        private System.Windows.Forms.Label designerMgLabel1;
        private System.Windows.Forms.Label designerMgLabel2;
        private System.Windows.Forms.Label designerMgLabel3;
        private System.Windows.Forms.Label designerMgLabel4;
        private System.Windows.Forms.Label designerMgLabel5;
        private System.Windows.Forms.Label designerMgLabel6;
        private System.Windows.Forms.Label designerReleaseLabel;
        private System.Windows.Forms.Button designerAdd;
        private System.Windows.Forms.Button designerUpdate;
        private System.Windows.Forms.Button designerDeactivate;
        private System.Windows.Forms.Button designerClear;
        private System.Windows.Forms.Panel designerCatalog;
        private System.Windows.Forms.Label designerCatalogPill;
        private System.Windows.Forms.Label designerCatalogTitle;
        private System.Windows.Forms.Label designerCatalogSub;
    }
}
