namespace GameHub.Forms
{
    partial class OrdersForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerTitle = new System.Windows.Forms.Label();
            this.designerTitle.AutoSize = false;
            this.designerTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTitle.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.designerTitle.Location = new System.Drawing.Point(28, 20);
            this.designerTitle.Name = "designerTitle";
            this.designerTitle.Size = new System.Drawing.Size(750, 44);
            this.designerTitle.Text = "Order Management";
            this.Controls.Add(this.designerTitle);
            this.designerSubtitle = new System.Windows.Forms.Label();
            this.designerSubtitle.AutoSize = false;
            this.designerSubtitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSubtitle.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSubtitle.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this.designerSubtitle.Location = new System.Drawing.Point(30, 62);
            this.designerSubtitle.Name = "designerSubtitle";
            this.designerSubtitle.Size = new System.Drawing.Size(850, 28);
            this.designerSubtitle.Text = "Review customer orders, inspect items and update order status.";
            this.Controls.Add(this.designerSubtitle);
            this.designerBack = new System.Windows.Forms.Button();
            this.designerBack.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBack.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBack.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBack.Location = new System.Drawing.Point(1138, 22);
            this.designerBack.Name = "designerBack";
            this.designerBack.Size = new System.Drawing.Size(105, 36);
            this.designerBack.Text = "←  BACK";
            this.designerBack.UseVisualStyleBackColor = false;
            this.Controls.Add(this.designerBack);
            this.designerSearchCard = new System.Windows.Forms.Panel();
            this.designerSearchCard.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerSearchCard.Location = new System.Drawing.Point(28, 106);
            this.designerSearchCard.Name = "designerSearchCard";
            this.designerSearchCard.Size = new System.Drawing.Size(1224, 64);
            this.Controls.Add(this.designerSearchCard);
            this._search = new System.Windows.Forms.TextBox();
            this._search.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._search.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._search.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._search.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._search.Location = new System.Drawing.Point(18, 17);
            this._search.Name = "_search";
            this._search.Size = new System.Drawing.Size(900, 30);
            this.designerSearchCard.Controls.Add(this._search);
            this.designerSearch = new System.Windows.Forms.Button();
            this.designerSearch.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerSearch.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerSearch.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerSearch.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerSearch.Location = new System.Drawing.Point(930, 15);
            this.designerSearch.Name = "designerSearch";
            this.designerSearch.Size = new System.Drawing.Size(105, 34);
            this.designerSearch.Text = "SEARCH";
            this.designerSearch.UseVisualStyleBackColor = false;
            this.designerSearchCard.Controls.Add(this.designerSearch);
            this.designerAll = new System.Windows.Forms.Button();
            this.designerAll.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerAll.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerAll.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerAll.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerAll.Location = new System.Drawing.Point(1045, 15);
            this.designerAll.Name = "designerAll";
            this.designerAll.Size = new System.Drawing.Size(115, 34);
            this.designerAll.Text = "SHOW ALL";
            this.designerAll.UseVisualStyleBackColor = false;
            this.designerSearchCard.Controls.Add(this.designerAll);
            this.designerOrdersList = new System.Windows.Forms.Panel();
            this.designerOrdersList.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerOrdersList.Location = new System.Drawing.Point(28, 184);
            this.designerOrdersList.Name = "designerOrdersList";
            this.designerOrdersList.Size = new System.Drawing.Size(770, 548);
            this.Controls.Add(this.designerOrdersList);
            this.designerOrdersTitle = new System.Windows.Forms.Label();
            this.designerOrdersTitle.AutoSize = false;
            this.designerOrdersTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerOrdersTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerOrdersTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.designerOrdersTitle.Location = new System.Drawing.Point(18, 15);
            this.designerOrdersTitle.Name = "designerOrdersTitle";
            this.designerOrdersTitle.Size = new System.Drawing.Size(260, 34);
            this.designerOrdersTitle.Text = "Orders";
            this.designerOrdersList.Controls.Add(this.designerOrdersTitle);
            this._grid = new System.Windows.Forms.DataGridView();
            this._grid.AllowUserToAddRows = false;
            this._grid.AllowUserToDeleteRows = false;
            this._grid.BackgroundColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this._grid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._grid.ColumnHeadersHeight = 36;
            this._grid.Location = new System.Drawing.Point(18, 58);
            this._grid.Name = "_grid";
            this._grid.ReadOnly = true;
            this._grid.RowHeadersVisible = false;
            this._grid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._grid.Size = new System.Drawing.Size(734, 470);
            this._grid.SelectionChanged += new System.EventHandler(this.Grid_SelectionChanged);
            this.designerOrdersList.Controls.Add(this._grid);
            this.designerAction = new System.Windows.Forms.Panel();
            this.designerAction.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerAction.Location = new System.Drawing.Point(816, 184);
            this.designerAction.Name = "designerAction";
            this.designerAction.Size = new System.Drawing.Size(436, 548);
            this.Controls.Add(this.designerAction);
            this.designerProcessPill = new System.Windows.Forms.Label();
            this.designerProcessPill.AutoSize = false;
            this.designerProcessPill.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerProcessPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerProcessPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerProcessPill.Location = new System.Drawing.Point(18, 18);
            this.designerProcessPill.Name = "designerProcessPill";
            this.designerProcessPill.Size = new System.Drawing.Size(84, 26);
            this.designerProcessPill.Text = "PROCESS";
            this.designerProcessPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerAction.Controls.Add(this.designerProcessPill);
            this.designerSelectedTitle = new System.Windows.Forms.Label();
            this.designerSelectedTitle.AutoSize = false;
            this.designerSelectedTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSelectedTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerSelectedTitle.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerSelectedTitle.Location = new System.Drawing.Point(18, 57);
            this.designerSelectedTitle.Name = "designerSelectedTitle";
            this.designerSelectedTitle.Size = new System.Drawing.Size(280, 32);
            this.designerSelectedTitle.Text = "Selected Order";
            this.designerAction.Controls.Add(this.designerSelectedTitle);
            this._selected = new System.Windows.Forms.Label();
            this._selected.AutoSize = false;
            this._selected.BackColor = System.Drawing.Color.Transparent;
            this._selected.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this._selected.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this._selected.Location = new System.Drawing.Point(18, 91);
            this._selected.Name = "_selected";
            this._selected.Size = new System.Drawing.Size(400, 26);
            this._selected.Text = "No order selected";
            this.designerAction.Controls.Add(this._selected);
            this.designerStatusLabel = new System.Windows.Forms.Label();
            this.designerStatusLabel.AutoSize = false;
            this.designerStatusLabel.BackColor = System.Drawing.Color.Transparent;
            this.designerStatusLabel.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStatusLabel.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this.designerStatusLabel.Location = new System.Drawing.Point(18, 131);
            this.designerStatusLabel.Name = "designerStatusLabel";
            this.designerStatusLabel.Size = new System.Drawing.Size(150, 24);
            this.designerStatusLabel.Text = "Status";
            this.designerAction.Controls.Add(this.designerStatusLabel);
            this._status = new System.Windows.Forms.ComboBox();
            this._status.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._status.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._status.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._status.Location = new System.Drawing.Point(18, 158);
            this._status.Name = "_status";
            this._status.Size = new System.Drawing.Size(400, 31);
            this._status.Items.AddRange(new object[] { "Pending", "Paid", "Completed", "Cancelled" });
            this._status.SelectedIndex = 0;
            this.designerAction.Controls.Add(this._status);
            this.designerUpdateStatus = new System.Windows.Forms.Button();
            this.designerUpdateStatus.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerUpdateStatus.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerUpdateStatus.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerUpdateStatus.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerUpdateStatus.Location = new System.Drawing.Point(18, 207);
            this.designerUpdateStatus.Name = "designerUpdateStatus";
            this.designerUpdateStatus.Size = new System.Drawing.Size(400, 40);
            this.designerUpdateStatus.Text = "UPDATE STATUS";
            this.designerUpdateStatus.UseVisualStyleBackColor = false;
            this.designerUpdateStatus.Click += new System.EventHandler(this.Update_Click);
            this.designerAction.Controls.Add(this.designerUpdateStatus);
            this.designerItemsTitle = new System.Windows.Forms.Label();
            this.designerItemsTitle.AutoSize = false;
            this.designerItemsTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerItemsTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerItemsTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.designerItemsTitle.Location = new System.Drawing.Point(18, 278);
            this.designerItemsTitle.Name = "designerItemsTitle";
            this.designerItemsTitle.Size = new System.Drawing.Size(250, 30);
            this.designerItemsTitle.Text = "Order Items";
            this.designerAction.Controls.Add(this.designerItemsTitle);
            this._details = new System.Windows.Forms.DataGridView();
            this._details.AllowUserToAddRows = false;
            this._details.AllowUserToDeleteRows = false;
            this._details.BackgroundColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this._details.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._details.ColumnHeadersHeight = 36;
            this._details.Location = new System.Drawing.Point(18, 314);
            this._details.Name = "_details";
            this._details.ReadOnly = true;
            this._details.RowHeadersVisible = false;
            this._details.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._details.Size = new System.Drawing.Size(400, 214);
            this.designerAction.Controls.Add(this._details);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(1280, 760);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(1050, 700);
            this.Name = "OrdersForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - Order Management";
        }

        private System.Windows.Forms.Label designerTitle;
        private System.Windows.Forms.Label designerSubtitle;
        private System.Windows.Forms.Button designerBack;
        private System.Windows.Forms.Panel designerSearchCard;
        private System.Windows.Forms.Button designerSearch;
        private System.Windows.Forms.Button designerAll;
        private System.Windows.Forms.Panel designerOrdersList;
        private System.Windows.Forms.Label designerOrdersTitle;
        private System.Windows.Forms.Panel designerAction;
        private System.Windows.Forms.Label designerProcessPill;
        private System.Windows.Forms.Label designerSelectedTitle;
        private System.Windows.Forms.Label designerStatusLabel;
        private System.Windows.Forms.Button designerUpdateStatus;
        private System.Windows.Forms.Label designerItemsTitle;
    }
}
