namespace GameHub.Forms
{
    partial class ProfileForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerTitle = new System.Windows.Forms.Label();
            this.designerTitle.AutoSize = false;
            this.designerTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.designerTitle.Location = new System.Drawing.Point(28, 22);
            this.designerTitle.Name = "designerTitle";
            this.designerTitle.Size = new System.Drawing.Size(480, 42);
            this.designerTitle.Text = "Profile";
            this.Controls.Add(this.designerTitle);
            this.designerSubtitle = new System.Windows.Forms.Label();
            this.designerSubtitle.AutoSize = false;
            this.designerSubtitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSubtitle.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSubtitle.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerSubtitle.Location = new System.Drawing.Point(30, 54);
            this.designerSubtitle.Name = "designerSubtitle";
            this.designerSubtitle.Size = new System.Drawing.Size(620, 28);
            this.designerSubtitle.Text = "Update your contact information and account password.";
            this.Controls.Add(this.designerSubtitle);
            this.designerBack = new System.Windows.Forms.Button();
            this.designerBack.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBack.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBack.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBack.Location = new System.Drawing.Point(776, 20);
            this.designerBack.Name = "designerBack";
            this.designerBack.Size = new System.Drawing.Size(96, 34);
            this.designerBack.Text = "←  Back";
            this.designerBack.UseVisualStyleBackColor = false;
            this.Controls.Add(this.designerBack);
            this.designerInfo = new System.Windows.Forms.Panel();
            this.designerInfo.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerInfo.Location = new System.Drawing.Point(28, 94);
            this.designerInfo.Name = "designerInfo";
            this.designerInfo.Size = new System.Drawing.Size(404, 498);
            this.Controls.Add(this.designerInfo);
            this.designerAccountPill = new System.Windows.Forms.Label();
            this.designerAccountPill.AutoSize = false;
            this.designerAccountPill.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerAccountPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerAccountPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerAccountPill.Location = new System.Drawing.Point(18, 16);
            this.designerAccountPill.Name = "designerAccountPill";
            this.designerAccountPill.Size = new System.Drawing.Size(78, 26);
            this.designerAccountPill.Text = "ACCOUNT";
            this.designerAccountPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerInfo.Controls.Add(this.designerAccountPill);
            this.designerInfoTitle = new System.Windows.Forms.Label();
            this.designerInfoTitle.AutoSize = false;
            this.designerInfoTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerInfoTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerInfoTitle.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerInfoTitle.Location = new System.Drawing.Point(18, 54);
            this.designerInfoTitle.Name = "designerInfoTitle";
            this.designerInfoTitle.Size = new System.Drawing.Size(300, 32);
            this.designerInfoTitle.Text = "Profile Information";
            this.designerInfo.Controls.Add(this.designerInfoTitle);
            this.designerUsernameLabel = new System.Windows.Forms.Label();
            this.designerUsernameLabel.AutoSize = false;
            this.designerUsernameLabel.BackColor = System.Drawing.Color.Transparent;
            this.designerUsernameLabel.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerUsernameLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerUsernameLabel.Location = new System.Drawing.Point(18, 102);
            this.designerUsernameLabel.Name = "designerUsernameLabel";
            this.designerUsernameLabel.Size = new System.Drawing.Size(160, 22);
            this.designerUsernameLabel.Text = "Username";
            this.designerInfo.Controls.Add(this.designerUsernameLabel);
            this._username = new System.Windows.Forms.Label();
            this._username.AutoSize = false;
            this._username.BackColor = System.Drawing.Color.Transparent;
            this._username.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this._username.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this._username.Location = new System.Drawing.Point(18, 126);
            this._username.Name = "_username";
            this._username.Size = new System.Drawing.Size(180, 28);
            this._username.Text = "customer01";
            this.designerInfo.Controls.Add(this._username);
            this.designerRoleLabel = new System.Windows.Forms.Label();
            this.designerRoleLabel.AutoSize = false;
            this.designerRoleLabel.BackColor = System.Drawing.Color.Transparent;
            this.designerRoleLabel.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerRoleLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerRoleLabel.Location = new System.Drawing.Point(220, 102);
            this.designerRoleLabel.Name = "designerRoleLabel";
            this.designerRoleLabel.Size = new System.Drawing.Size(120, 22);
            this.designerRoleLabel.Text = "Role";
            this.designerInfo.Controls.Add(this.designerRoleLabel);
            this._role = new System.Windows.Forms.Label();
            this._role.AutoSize = false;
            this._role.BackColor = System.Drawing.Color.Transparent;
            this._role.ForeColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this._role.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this._role.Location = new System.Drawing.Point(220, 126);
            this._role.Name = "_role";
            this._role.Size = new System.Drawing.Size(160, 28);
            this._role.Text = "Customer";
            this.designerInfo.Controls.Add(this._role);
            this.designerProfileLabel1 = new System.Windows.Forms.Label();
            this.designerProfileLabel1.AutoSize = false;
            this.designerProfileLabel1.BackColor = System.Drawing.Color.Transparent;
            this.designerProfileLabel1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerProfileLabel1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerProfileLabel1.Location = new System.Drawing.Point(18, 176);
            this.designerProfileLabel1.Name = "designerProfileLabel1";
            this.designerProfileLabel1.Size = new System.Drawing.Size(180, 22);
            this.designerProfileLabel1.Text = "Full Name";
            this.designerInfo.Controls.Add(this.designerProfileLabel1);
            this._name = new System.Windows.Forms.TextBox();
            this._name.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._name.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._name.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._name.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._name.Location = new System.Drawing.Point(18, 200);
            this._name.Name = "_name";
            this._name.Size = new System.Drawing.Size(368, 30);
            this.designerInfo.Controls.Add(this._name);
            this.designerProfileLabel2 = new System.Windows.Forms.Label();
            this.designerProfileLabel2.AutoSize = false;
            this.designerProfileLabel2.BackColor = System.Drawing.Color.Transparent;
            this.designerProfileLabel2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerProfileLabel2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerProfileLabel2.Location = new System.Drawing.Point(18, 246);
            this.designerProfileLabel2.Name = "designerProfileLabel2";
            this.designerProfileLabel2.Size = new System.Drawing.Size(180, 22);
            this.designerProfileLabel2.Text = "Email";
            this.designerInfo.Controls.Add(this.designerProfileLabel2);
            this._email = new System.Windows.Forms.TextBox();
            this._email.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._email.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._email.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._email.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._email.Location = new System.Drawing.Point(18, 270);
            this._email.Name = "_email";
            this._email.Size = new System.Drawing.Size(368, 30);
            this.designerInfo.Controls.Add(this._email);
            this.designerProfileLabel3 = new System.Windows.Forms.Label();
            this.designerProfileLabel3.AutoSize = false;
            this.designerProfileLabel3.BackColor = System.Drawing.Color.Transparent;
            this.designerProfileLabel3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerProfileLabel3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerProfileLabel3.Location = new System.Drawing.Point(18, 316);
            this.designerProfileLabel3.Name = "designerProfileLabel3";
            this.designerProfileLabel3.Size = new System.Drawing.Size(180, 22);
            this.designerProfileLabel3.Text = "Phone";
            this.designerInfo.Controls.Add(this.designerProfileLabel3);
            this._phone = new System.Windows.Forms.TextBox();
            this._phone.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._phone.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._phone.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._phone.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._phone.Location = new System.Drawing.Point(18, 340);
            this._phone.Name = "_phone";
            this._phone.Size = new System.Drawing.Size(368, 30);
            this.designerInfo.Controls.Add(this._phone);
            this.designerSaveProfile = new System.Windows.Forms.Button();
            this.designerSaveProfile.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerSaveProfile.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerSaveProfile.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerSaveProfile.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerSaveProfile.Location = new System.Drawing.Point(18, 410);
            this.designerSaveProfile.Name = "designerSaveProfile";
            this.designerSaveProfile.Size = new System.Drawing.Size(368, 40);
            this.designerSaveProfile.Text = "SAVE PROFILE";
            this.designerSaveProfile.UseVisualStyleBackColor = false;
            this.designerSaveProfile.Click += new System.EventHandler(this.SaveProfile_Click);
            this.designerInfo.Controls.Add(this.designerSaveProfile);
            this.designerPassword = new System.Windows.Forms.Panel();
            this.designerPassword.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerPassword.Location = new System.Drawing.Point(450, 94);
            this.designerPassword.Name = "designerPassword";
            this.designerPassword.Size = new System.Drawing.Size(422, 498);
            this.Controls.Add(this.designerPassword);
            this.designerSecurityPill = new System.Windows.Forms.Label();
            this.designerSecurityPill.AutoSize = false;
            this.designerSecurityPill.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerSecurityPill.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerSecurityPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerSecurityPill.Location = new System.Drawing.Point(18, 16);
            this.designerSecurityPill.Name = "designerSecurityPill";
            this.designerSecurityPill.Size = new System.Drawing.Size(82, 26);
            this.designerSecurityPill.Text = "SECURITY";
            this.designerSecurityPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerPassword.Controls.Add(this.designerSecurityPill);
            this.designerPasswordTitle = new System.Windows.Forms.Label();
            this.designerPasswordTitle.AutoSize = false;
            this.designerPasswordTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerPasswordTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPasswordTitle.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerPasswordTitle.Location = new System.Drawing.Point(18, 54);
            this.designerPasswordTitle.Name = "designerPasswordTitle";
            this.designerPasswordTitle.Size = new System.Drawing.Size(320, 32);
            this.designerPasswordTitle.Text = "Change Password";
            this.designerPassword.Controls.Add(this.designerPasswordTitle);
            this.designerPasswordSub = new System.Windows.Forms.Label();
            this.designerPasswordSub.AutoSize = false;
            this.designerPasswordSub.BackColor = System.Drawing.Color.Transparent;
            this.designerPasswordSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerPasswordSub.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerPasswordSub.Location = new System.Drawing.Point(18, 82);
            this.designerPasswordSub.Name = "designerPasswordSub";
            this.designerPasswordSub.Size = new System.Drawing.Size(330, 24);
            this.designerPasswordSub.Text = "Your current password is required.";
            this.designerPassword.Controls.Add(this.designerPasswordSub);
            this.designerPasswordLabel1 = new System.Windows.Forms.Label();
            this.designerPasswordLabel1.AutoSize = false;
            this.designerPasswordLabel1.BackColor = System.Drawing.Color.Transparent;
            this.designerPasswordLabel1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPasswordLabel1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPasswordLabel1.Location = new System.Drawing.Point(18, 128);
            this.designerPasswordLabel1.Name = "designerPasswordLabel1";
            this.designerPasswordLabel1.Size = new System.Drawing.Size(220, 22);
            this.designerPasswordLabel1.Text = "Current Password";
            this.designerPassword.Controls.Add(this.designerPasswordLabel1);
            this._oldPassword = new System.Windows.Forms.TextBox();
            this._oldPassword.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._oldPassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._oldPassword.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._oldPassword.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._oldPassword.Location = new System.Drawing.Point(18, 152);
            this._oldPassword.Name = "_oldPassword";
            this._oldPassword.Size = new System.Drawing.Size(386, 30);
            this._oldPassword.PasswordChar = '●';
            this.designerPassword.Controls.Add(this._oldPassword);
            this.designerPasswordLabel2 = new System.Windows.Forms.Label();
            this.designerPasswordLabel2.AutoSize = false;
            this.designerPasswordLabel2.BackColor = System.Drawing.Color.Transparent;
            this.designerPasswordLabel2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPasswordLabel2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPasswordLabel2.Location = new System.Drawing.Point(18, 204);
            this.designerPasswordLabel2.Name = "designerPasswordLabel2";
            this.designerPasswordLabel2.Size = new System.Drawing.Size(220, 22);
            this.designerPasswordLabel2.Text = "New Password";
            this.designerPassword.Controls.Add(this.designerPasswordLabel2);
            this._newPassword = new System.Windows.Forms.TextBox();
            this._newPassword.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._newPassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._newPassword.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._newPassword.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._newPassword.Location = new System.Drawing.Point(18, 228);
            this._newPassword.Name = "_newPassword";
            this._newPassword.Size = new System.Drawing.Size(386, 30);
            this._newPassword.PasswordChar = '●';
            this.designerPassword.Controls.Add(this._newPassword);
            this.designerPasswordLabel3 = new System.Windows.Forms.Label();
            this.designerPasswordLabel3.AutoSize = false;
            this.designerPasswordLabel3.BackColor = System.Drawing.Color.Transparent;
            this.designerPasswordLabel3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPasswordLabel3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPasswordLabel3.Location = new System.Drawing.Point(18, 280);
            this.designerPasswordLabel3.Name = "designerPasswordLabel3";
            this.designerPasswordLabel3.Size = new System.Drawing.Size(220, 22);
            this.designerPasswordLabel3.Text = "Confirm New Password";
            this.designerPassword.Controls.Add(this.designerPasswordLabel3);
            this._confirmPassword = new System.Windows.Forms.TextBox();
            this._confirmPassword.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._confirmPassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._confirmPassword.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._confirmPassword.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._confirmPassword.Location = new System.Drawing.Point(18, 304);
            this._confirmPassword.Name = "_confirmPassword";
            this._confirmPassword.Size = new System.Drawing.Size(386, 30);
            this._confirmPassword.PasswordChar = '●';
            this.designerPassword.Controls.Add(this._confirmPassword);
            this.designerShowPasswords = new System.Windows.Forms.CheckBox();
            this.designerShowPasswords.AutoSize = false;
            this.designerShowPasswords.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerShowPasswords.Location = new System.Drawing.Point(18, 350);
            this.designerShowPasswords.Name = "designerShowPasswords";
            this.designerShowPasswords.Size = new System.Drawing.Size(150, 24);
            this.designerShowPasswords.Text = "Show passwords";
            this.designerShowPasswords.UseVisualStyleBackColor = true;
            this.designerPassword.Controls.Add(this.designerShowPasswords);
            this.designerChangePassword = new System.Windows.Forms.Button();
            this.designerChangePassword.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerChangePassword.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerChangePassword.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerChangePassword.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerChangePassword.Location = new System.Drawing.Point(18, 410);
            this.designerChangePassword.Name = "designerChangePassword";
            this.designerChangePassword.Size = new System.Drawing.Size(386, 40);
            this.designerChangePassword.Text = "CHANGE PASSWORD";
            this.designerChangePassword.UseVisualStyleBackColor = false;
            this.designerChangePassword.Click += new System.EventHandler(this.ChangePassword_Click);
            this.designerPassword.Controls.Add(this.designerChangePassword);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(900, 620);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(860, 600);
            this.Name = "ProfileForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - Profile";
        }

        private System.Windows.Forms.Label designerTitle;
        private System.Windows.Forms.Label designerSubtitle;
        private System.Windows.Forms.Button designerBack;
        private System.Windows.Forms.Panel designerInfo;
        private System.Windows.Forms.Label designerAccountPill;
        private System.Windows.Forms.Label designerInfoTitle;
        private System.Windows.Forms.Label designerUsernameLabel;
        private System.Windows.Forms.Label designerRoleLabel;
        private System.Windows.Forms.Label designerProfileLabel1;
        private System.Windows.Forms.Label designerProfileLabel2;
        private System.Windows.Forms.Label designerProfileLabel3;
        private System.Windows.Forms.Button designerSaveProfile;
        private System.Windows.Forms.Panel designerPassword;
        private System.Windows.Forms.Label designerSecurityPill;
        private System.Windows.Forms.Label designerPasswordTitle;
        private System.Windows.Forms.Label designerPasswordSub;
        private System.Windows.Forms.Label designerPasswordLabel1;
        private System.Windows.Forms.Label designerPasswordLabel2;
        private System.Windows.Forms.Label designerPasswordLabel3;
        private System.Windows.Forms.CheckBox designerShowPasswords;
        private System.Windows.Forms.Button designerChangePassword;
    }
}
