namespace GameHub.Forms
{
    partial class RegisterForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerShell = new System.Windows.Forms.Panel();
            this.designerShell.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerShell.Location = new System.Drawing.Point(24, 24);
            this.designerShell.Name = "designerShell";
            this.designerShell.Size = new System.Drawing.Size(1132, 672);
            this.Controls.Add(this.designerShell);
            this.designerFormSide = new System.Windows.Forms.Panel();
            this.designerFormSide.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerFormSide.Location = new System.Drawing.Point(0, 0);
            this.designerFormSide.Name = "designerFormSide";
            this.designerFormSide.Size = new System.Drawing.Size(548, 672);
            this.designerShell.Controls.Add(this.designerFormSide);
            this.designerArtwork = new System.Windows.Forms.Panel();
            this.designerArtwork.BackColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this.designerArtwork.Location = new System.Drawing.Point(548, 0);
            this.designerArtwork.Name = "designerArtwork";
            this.designerArtwork.Size = new System.Drawing.Size(584, 672);
            this.designerShell.Controls.Add(this.designerArtwork);
            this.designerLogo = new System.Windows.Forms.Panel();
            this.designerLogo.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerLogo.Location = new System.Drawing.Point(42, 26);
            this.designerLogo.Name = "designerLogo";
            this.designerLogo.Size = new System.Drawing.Size(46, 46);
            this.designerFormSide.Controls.Add(this.designerLogo);
            this.designerLogoText = new System.Windows.Forms.Label();
            this.designerLogoText.AutoSize = false;
            this.designerLogoText.BackColor = System.Drawing.Color.Transparent;
            this.designerLogoText.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerLogoText.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.designerLogoText.Location = new System.Drawing.Point(0, 2);
            this.designerLogoText.Name = "designerLogoText";
            this.designerLogoText.Size = new System.Drawing.Size(46, 40);
            this.designerLogoText.Text = "G";
            this.designerLogoText.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerLogo.Controls.Add(this.designerLogoText);
            this.designerBrand = new System.Windows.Forms.Label();
            this.designerBrand.AutoSize = false;
            this.designerBrand.BackColor = System.Drawing.Color.Transparent;
            this.designerBrand.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBrand.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerBrand.Location = new System.Drawing.Point(100, 31);
            this.designerBrand.Name = "designerBrand";
            this.designerBrand.Size = new System.Drawing.Size(180, 32);
            this.designerBrand.Text = "GameHub";
            this.designerFormSide.Controls.Add(this.designerBrand);
            this.designerPill = new System.Windows.Forms.Label();
            this.designerPill.AutoSize = false;
            this.designerPill.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerPill.ForeColor = System.Drawing.Color.FromArgb(64, 214, 216);
            this.designerPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerPill.Location = new System.Drawing.Point(42, 88);
            this.designerPill.Name = "designerPill";
            this.designerPill.Size = new System.Drawing.Size(114, 26);
            this.designerPill.Text = "START FOR FREE";
            this.designerPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerFormSide.Controls.Add(this.designerPill);
            this.designerTitle = new System.Windows.Forms.Label();
            this.designerTitle.AutoSize = false;
            this.designerTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTitle.Font = new System.Drawing.Font("Segoe UI", 25F, System.Drawing.FontStyle.Bold);
            this.designerTitle.Location = new System.Drawing.Point(42, 123);
            this.designerTitle.Name = "designerTitle";
            this.designerTitle.Size = new System.Drawing.Size(462, 58);
            this.designerTitle.Text = "Create account";
            this.designerFormSide.Controls.Add(this.designerTitle);
            this.designerSub = new System.Windows.Forms.Label();
            this.designerSub.AutoSize = false;
            this.designerSub.BackColor = System.Drawing.Color.Transparent;
            this.designerSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSub.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerSub.Location = new System.Drawing.Point(44, 178);
            this.designerSub.Name = "designerSub";
            this.designerSub.Size = new System.Drawing.Size(462, 34);
            this.designerSub.Text = "Every public registration is safely created as Customer.";
            this.designerFormSide.Controls.Add(this.designerSub);
            this.designerLabelName = new System.Windows.Forms.Label();
            this.designerLabelName.AutoSize = false;
            this.designerLabelName.BackColor = System.Drawing.Color.Transparent;
            this.designerLabelName.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerLabelName.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerLabelName.Location = new System.Drawing.Point(42, 202);
            this.designerLabelName.Name = "designerLabelName";
            this.designerLabelName.Size = new System.Drawing.Size(222, 20);
            this.designerLabelName.Text = "Full Name *";
            this.designerFormSide.Controls.Add(this.designerLabelName);
            this._txtName = new System.Windows.Forms.TextBox();
            this._txtName.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtName.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtName.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtName.Location = new System.Drawing.Point(42, 224);
            this._txtName.Name = "_txtName";
            this._txtName.Size = new System.Drawing.Size(222, 36);
            this.designerFormSide.Controls.Add(this._txtName);
            this.designerLabelUser = new System.Windows.Forms.Label();
            this.designerLabelUser.AutoSize = false;
            this.designerLabelUser.BackColor = System.Drawing.Color.Transparent;
            this.designerLabelUser.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerLabelUser.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerLabelUser.Location = new System.Drawing.Point(282, 202);
            this.designerLabelUser.Name = "designerLabelUser";
            this.designerLabelUser.Size = new System.Drawing.Size(222, 20);
            this.designerLabelUser.Text = "Username *";
            this.designerFormSide.Controls.Add(this.designerLabelUser);
            this._txtUser = new System.Windows.Forms.TextBox();
            this._txtUser.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtUser.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtUser.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtUser.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtUser.Location = new System.Drawing.Point(282, 224);
            this._txtUser.Name = "_txtUser";
            this._txtUser.Size = new System.Drawing.Size(222, 36);
            this.designerFormSide.Controls.Add(this._txtUser);
            this.designerLabelEmail = new System.Windows.Forms.Label();
            this.designerLabelEmail.AutoSize = false;
            this.designerLabelEmail.BackColor = System.Drawing.Color.Transparent;
            this.designerLabelEmail.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerLabelEmail.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerLabelEmail.Location = new System.Drawing.Point(42, 276);
            this.designerLabelEmail.Name = "designerLabelEmail";
            this.designerLabelEmail.Size = new System.Drawing.Size(462, 20);
            this.designerLabelEmail.Text = "Email *";
            this.designerFormSide.Controls.Add(this.designerLabelEmail);
            this._txtEmail = new System.Windows.Forms.TextBox();
            this._txtEmail.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtEmail.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtEmail.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtEmail.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtEmail.Location = new System.Drawing.Point(42, 298);
            this._txtEmail.Name = "_txtEmail";
            this._txtEmail.Size = new System.Drawing.Size(462, 36);
            this.designerFormSide.Controls.Add(this._txtEmail);
            this.designerLabelPhone = new System.Windows.Forms.Label();
            this.designerLabelPhone.AutoSize = false;
            this.designerLabelPhone.BackColor = System.Drawing.Color.Transparent;
            this.designerLabelPhone.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerLabelPhone.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerLabelPhone.Location = new System.Drawing.Point(42, 350);
            this.designerLabelPhone.Name = "designerLabelPhone";
            this.designerLabelPhone.Size = new System.Drawing.Size(462, 20);
            this.designerLabelPhone.Text = "Phone *";
            this.designerFormSide.Controls.Add(this.designerLabelPhone);
            this._txtPhone = new System.Windows.Forms.TextBox();
            this._txtPhone.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtPhone.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtPhone.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtPhone.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtPhone.Location = new System.Drawing.Point(42, 372);
            this._txtPhone.Name = "_txtPhone";
            this._txtPhone.Size = new System.Drawing.Size(462, 36);
            this.designerFormSide.Controls.Add(this._txtPhone);
            this.designerLabelPass = new System.Windows.Forms.Label();
            this.designerLabelPass.AutoSize = false;
            this.designerLabelPass.BackColor = System.Drawing.Color.Transparent;
            this.designerLabelPass.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerLabelPass.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerLabelPass.Location = new System.Drawing.Point(42, 424);
            this.designerLabelPass.Name = "designerLabelPass";
            this.designerLabelPass.Size = new System.Drawing.Size(222, 20);
            this.designerLabelPass.Text = "Password *";
            this.designerFormSide.Controls.Add(this.designerLabelPass);
            this._txtPass = new System.Windows.Forms.TextBox();
            this._txtPass.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtPass.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtPass.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtPass.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtPass.Location = new System.Drawing.Point(42, 446);
            this._txtPass.Name = "_txtPass";
            this._txtPass.Size = new System.Drawing.Size(222, 36);
            this._txtPass.PasswordChar = '●';
            this.designerFormSide.Controls.Add(this._txtPass);
            this.designerLabelConfirm = new System.Windows.Forms.Label();
            this.designerLabelConfirm.AutoSize = false;
            this.designerLabelConfirm.BackColor = System.Drawing.Color.Transparent;
            this.designerLabelConfirm.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerLabelConfirm.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerLabelConfirm.Location = new System.Drawing.Point(282, 424);
            this.designerLabelConfirm.Name = "designerLabelConfirm";
            this.designerLabelConfirm.Size = new System.Drawing.Size(222, 20);
            this.designerLabelConfirm.Text = "Confirm Password *";
            this.designerFormSide.Controls.Add(this.designerLabelConfirm);
            this._txtConfirm = new System.Windows.Forms.TextBox();
            this._txtConfirm.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtConfirm.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtConfirm.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtConfirm.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtConfirm.Location = new System.Drawing.Point(282, 446);
            this._txtConfirm.Name = "_txtConfirm";
            this._txtConfirm.Size = new System.Drawing.Size(222, 36);
            this._txtConfirm.PasswordChar = '●';
            this.designerFormSide.Controls.Add(this._txtConfirm);
            this.designerShowPassword = new System.Windows.Forms.CheckBox();
            this.designerShowPassword.AutoSize = false;
            this.designerShowPassword.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerShowPassword.Location = new System.Drawing.Point(42, 492);
            this.designerShowPassword.Name = "designerShowPassword";
            this.designerShowPassword.Size = new System.Drawing.Size(150, 24);
            this.designerShowPassword.Text = "Show passwords";
            this.designerShowPassword.UseVisualStyleBackColor = true;
            this.designerFormSide.Controls.Add(this.designerShowPassword);
            this.designerCreateButton = new System.Windows.Forms.Button();
            this.designerCreateButton.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerCreateButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerCreateButton.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerCreateButton.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerCreateButton.Location = new System.Drawing.Point(42, 526);
            this.designerCreateButton.Name = "designerCreateButton";
            this.designerCreateButton.Size = new System.Drawing.Size(462, 44);
            this.designerCreateButton.Text = "CREATE CUSTOMER ACCOUNT";
            this.designerCreateButton.UseVisualStyleBackColor = false;
            this.designerCreateButton.Click += new System.EventHandler(this.Register_Click);
            this.designerFormSide.Controls.Add(this.designerCreateButton);
            this.designerLoginLink = new System.Windows.Forms.LinkLabel();
            this.designerLoginLink.AutoSize = false;
            this.designerLoginLink.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.designerLoginLink.LinkColor = System.Drawing.Color.FromArgb(58, 159, 255);
            this.designerLoginLink.Location = new System.Drawing.Point(42, 584);
            this.designerLoginLink.Name = "designerLoginLink";
            this.designerLoginLink.Size = new System.Drawing.Size(300, 28);
            this.designerLoginLink.Text = "Already have an account? Sign in";
            this.designerFormSide.Controls.Add(this.designerLoginLink);
            this.designerArtTitle = new System.Windows.Forms.Label();
            this.designerArtTitle.AutoSize = false;
            this.designerArtTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerArtTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerArtTitle.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
            this.designerArtTitle.Location = new System.Drawing.Point(42, 74);
            this.designerArtTitle.Name = "designerArtTitle";
            this.designerArtTitle.Size = new System.Drawing.Size(490, 50);
            this.designerArtTitle.Text = "JOIN GAMEHUB";
            this.designerArtwork.Controls.Add(this.designerArtTitle);
            this.designerArtSub = new System.Windows.Forms.Label();
            this.designerArtSub.AutoSize = false;
            this.designerArtSub.BackColor = System.Drawing.Color.Transparent;
            this.designerArtSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerArtSub.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular);
            this.designerArtSub.Location = new System.Drawing.Point(44, 136);
            this.designerArtSub.Name = "designerArtSub";
            this.designerArtSub.Size = new System.Drawing.Size(470, 64);
            this.designerArtSub.Text = "One account for Store, Library, Wishlist, Wallet, Rewards and GameHub Pass.";
            this.designerArtwork.Controls.Add(this.designerArtSub);
            this.designerFeature1 = new System.Windows.Forms.Panel();
            this.designerFeature1.BackColor = System.Drawing.Color.FromArgb(74, 65, 220);
            this.designerFeature1.Location = new System.Drawing.Point(44, 246);
            this.designerFeature1.Name = "designerFeature1";
            this.designerFeature1.Size = new System.Drawing.Size(490, 82);
            this.designerArtwork.Controls.Add(this.designerFeature1);
            this.designerFeatureTitle1 = new System.Windows.Forms.Label();
            this.designerFeatureTitle1.AutoSize = false;
            this.designerFeatureTitle1.BackColor = System.Drawing.Color.Transparent;
            this.designerFeatureTitle1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerFeatureTitle1.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.designerFeatureTitle1.Location = new System.Drawing.Point(18, 12);
            this.designerFeatureTitle1.Name = "designerFeatureTitle1";
            this.designerFeatureTitle1.Size = new System.Drawing.Size(120, 26);
            this.designerFeatureTitle1.Text = "SHOP";
            this.designerFeature1.Controls.Add(this.designerFeatureTitle1);
            this.designerFeatureSub1 = new System.Windows.Forms.Label();
            this.designerFeatureSub1.AutoSize = false;
            this.designerFeatureSub1.BackColor = System.Drawing.Color.Transparent;
            this.designerFeatureSub1.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerFeatureSub1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerFeatureSub1.Location = new System.Drawing.Point(18, 40);
            this.designerFeatureSub1.Name = "designerFeatureSub1";
            this.designerFeatureSub1.Size = new System.Drawing.Size(440, 30);
            this.designerFeatureSub1.Text = "Browse the catalog and buy games securely.";
            this.designerFeature1.Controls.Add(this.designerFeatureSub1);
            this.designerFeature2 = new System.Windows.Forms.Panel();
            this.designerFeature2.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerFeature2.Location = new System.Drawing.Point(44, 350);
            this.designerFeature2.Name = "designerFeature2";
            this.designerFeature2.Size = new System.Drawing.Size(490, 82);
            this.designerArtwork.Controls.Add(this.designerFeature2);
            this.designerFeatureTitle2 = new System.Windows.Forms.Label();
            this.designerFeatureTitle2.AutoSize = false;
            this.designerFeatureTitle2.BackColor = System.Drawing.Color.Transparent;
            this.designerFeatureTitle2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerFeatureTitle2.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.designerFeatureTitle2.Location = new System.Drawing.Point(18, 12);
            this.designerFeatureTitle2.Name = "designerFeatureTitle2";
            this.designerFeatureTitle2.Size = new System.Drawing.Size(120, 26);
            this.designerFeatureTitle2.Text = "COLLECT";
            this.designerFeature2.Controls.Add(this.designerFeatureTitle2);
            this.designerFeatureSub2 = new System.Windows.Forms.Label();
            this.designerFeatureSub2.AutoSize = false;
            this.designerFeatureSub2.BackColor = System.Drawing.Color.Transparent;
            this.designerFeatureSub2.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerFeatureSub2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerFeatureSub2.Location = new System.Drawing.Point(18, 40);
            this.designerFeatureSub2.Name = "designerFeatureSub2";
            this.designerFeatureSub2.Size = new System.Drawing.Size(440, 30);
            this.designerFeatureSub2.Text = "Keep purchases, keys and reviews together.";
            this.designerFeature2.Controls.Add(this.designerFeatureSub2);
            this.designerFeature3 = new System.Windows.Forms.Panel();
            this.designerFeature3.BackColor = System.Drawing.Color.FromArgb(58, 159, 255);
            this.designerFeature3.Location = new System.Drawing.Point(44, 454);
            this.designerFeature3.Name = "designerFeature3";
            this.designerFeature3.Size = new System.Drawing.Size(490, 82);
            this.designerArtwork.Controls.Add(this.designerFeature3);
            this.designerFeatureTitle3 = new System.Windows.Forms.Label();
            this.designerFeatureTitle3.AutoSize = false;
            this.designerFeatureTitle3.BackColor = System.Drawing.Color.Transparent;
            this.designerFeatureTitle3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerFeatureTitle3.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold);
            this.designerFeatureTitle3.Location = new System.Drawing.Point(18, 12);
            this.designerFeatureTitle3.Name = "designerFeatureTitle3";
            this.designerFeatureTitle3.Size = new System.Drawing.Size(120, 26);
            this.designerFeatureTitle3.Text = "REWARD";
            this.designerFeature3.Controls.Add(this.designerFeatureTitle3);
            this.designerFeatureSub3 = new System.Windows.Forms.Label();
            this.designerFeatureSub3.AutoSize = false;
            this.designerFeatureSub3.BackColor = System.Drawing.Color.Transparent;
            this.designerFeatureSub3.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerFeatureSub3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerFeatureSub3.Location = new System.Drawing.Point(18, 40);
            this.designerFeatureSub3.Name = "designerFeatureSub3";
            this.designerFeatureSub3.Size = new System.Drawing.Size(440, 30);
            this.designerFeatureSub3.Text = "Earn points and unlock membership benefits.";
            this.designerFeature3.Controls.Add(this.designerFeatureSub3);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(1180, 720);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(1120, 720);
            this.Name = "RegisterForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - Create Account";
        }

        private System.Windows.Forms.Panel designerShell;
        private System.Windows.Forms.Panel designerFormSide;
        private System.Windows.Forms.Panel designerArtwork;
        private System.Windows.Forms.Panel designerLogo;
        private System.Windows.Forms.Label designerLogoText;
        private System.Windows.Forms.Label designerBrand;
        private System.Windows.Forms.Label designerPill;
        private System.Windows.Forms.Label designerTitle;
        private System.Windows.Forms.Label designerSub;
        private System.Windows.Forms.Label designerLabelName;
        private System.Windows.Forms.Label designerLabelUser;
        private System.Windows.Forms.Label designerLabelEmail;
        private System.Windows.Forms.Label designerLabelPhone;
        private System.Windows.Forms.Label designerLabelPass;
        private System.Windows.Forms.Label designerLabelConfirm;
        private System.Windows.Forms.CheckBox designerShowPassword;
        private System.Windows.Forms.Button designerCreateButton;
        private System.Windows.Forms.LinkLabel designerLoginLink;
        private System.Windows.Forms.Label designerArtTitle;
        private System.Windows.Forms.Label designerArtSub;
        private System.Windows.Forms.Panel designerFeature1;
        private System.Windows.Forms.Label designerFeatureTitle1;
        private System.Windows.Forms.Label designerFeatureSub1;
        private System.Windows.Forms.Panel designerFeature2;
        private System.Windows.Forms.Label designerFeatureTitle2;
        private System.Windows.Forms.Label designerFeatureSub2;
        private System.Windows.Forms.Panel designerFeature3;
        private System.Windows.Forms.Label designerFeatureTitle3;
        private System.Windows.Forms.Label designerFeatureSub3;
    }
}
