namespace GameHub.Forms
{
    partial class ReportsForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerTitle = new System.Windows.Forms.Label();
            this.designerTitle.AutoSize = false;
            this.designerTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTitle.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.designerTitle.Location = new System.Drawing.Point(28, 20);
            this.designerTitle.Name = "designerTitle";
            this.designerTitle.Size = new System.Drawing.Size(620, 44);
            this.designerTitle.Text = "Reports & Analytics";
            this.Controls.Add(this.designerTitle);
            this.designerSubtitle = new System.Windows.Forms.Label();
            this.designerSubtitle.AutoSize = false;
            this.designerSubtitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSubtitle.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSubtitle.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this.designerSubtitle.Location = new System.Drawing.Point(30, 62);
            this.designerSubtitle.Name = "designerSubtitle";
            this.designerSubtitle.Size = new System.Drawing.Size(780, 28);
            this.designerSubtitle.Text = "Review GameHub revenue, orders, users and store performance.";
            this.Controls.Add(this.designerSubtitle);
            this.designerBack = new System.Windows.Forms.Button();
            this.designerBack.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBack.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBack.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBack.Location = new System.Drawing.Point(1138, 22);
            this.designerBack.Name = "designerBack";
            this.designerBack.Size = new System.Drawing.Size(112, 38);
            this.designerBack.Text = "←  BACK";
            this.designerBack.UseVisualStyleBackColor = false;
            this.Controls.Add(this.designerBack);
            this.designerChartCard = new System.Windows.Forms.Panel();
            this.designerChartCard.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerChartCard.Location = new System.Drawing.Point(28, 112);
            this.designerChartCard.Name = "designerChartCard";
            this.designerChartCard.Size = new System.Drawing.Size(770, 620);
            this.Controls.Add(this.designerChartCard);
            this.designerChartPill = new System.Windows.Forms.Label();
            this.designerChartPill.AutoSize = false;
            this.designerChartPill.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerChartPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerChartPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerChartPill.Location = new System.Drawing.Point(18, 16);
            this.designerChartPill.Name = "designerChartPill";
            this.designerChartPill.Size = new System.Drawing.Size(74, 26);
            this.designerChartPill.Text = "REPORT";
            this.designerChartPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerChartCard.Controls.Add(this.designerChartPill);
            this.designerChartTitle = new System.Windows.Forms.Label();
            this.designerChartTitle.AutoSize = false;
            this.designerChartTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerChartTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerChartTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.designerChartTitle.Location = new System.Drawing.Point(18, 50);
            this.designerChartTitle.Name = "designerChartTitle";
            this.designerChartTitle.Size = new System.Drawing.Size(360, 34);
            this.designerChartTitle.Text = "Revenue by Genre";
            this.designerChartCard.Controls.Add(this.designerChartTitle);
            this.designerChartSub = new System.Windows.Forms.Label();
            this.designerChartSub.AutoSize = false;
            this.designerChartSub.BackColor = System.Drawing.Color.Transparent;
            this.designerChartSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerChartSub.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerChartSub.Location = new System.Drawing.Point(18, 82);
            this.designerChartSub.Name = "designerChartSub";
            this.designerChartSub.Size = new System.Drawing.Size(620, 24);
            this.designerChartSub.Text = "Paid/completed order revenue grouped by game category";
            this.designerChartCard.Controls.Add(this.designerChartSub);
            this._chart = new System.Windows.Forms.Panel();
            this._chart.BackColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this._chart.Location = new System.Drawing.Point(18, 120);
            this._chart.Name = "_chart";
            this._chart.Size = new System.Drawing.Size(734, 474);
            this.designerChartCard.Controls.Add(this._chart);
            this.designerBarLabel1 = new System.Windows.Forms.Label();
            this.designerBarLabel1.AutoSize = false;
            this.designerBarLabel1.BackColor = System.Drawing.Color.Transparent;
            this.designerBarLabel1.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerBarLabel1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBarLabel1.Location = new System.Drawing.Point(20, 90);
            this.designerBarLabel1.Name = "designerBarLabel1";
            this.designerBarLabel1.Size = new System.Drawing.Size(110, 24);
            this.designerBarLabel1.Text = "Action";
            this._chart.Controls.Add(this.designerBarLabel1);
            this.designerBar1 = new System.Windows.Forms.Panel();
            this.designerBar1.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerBar1.Location = new System.Drawing.Point(130, 90);
            this.designerBar1.Name = "designerBar1";
            this.designerBar1.Size = new System.Drawing.Size(430, 24);
            this._chart.Controls.Add(this.designerBar1);
            this.designerBarValue1 = new System.Windows.Forms.Label();
            this.designerBarValue1.AutoSize = false;
            this.designerBarValue1.BackColor = System.Drawing.Color.Transparent;
            this.designerBarValue1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBarValue1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBarValue1.Location = new System.Drawing.Point(570, 90);
            this.designerBarValue1.Name = "designerBarValue1";
            this.designerBarValue1.Size = new System.Drawing.Size(130, 24);
            this.designerBarValue1.Text = "Tk 1.5M";
            this._chart.Controls.Add(this.designerBarValue1);
            this.designerBarLabel2 = new System.Windows.Forms.Label();
            this.designerBarLabel2.AutoSize = false;
            this.designerBarLabel2.BackColor = System.Drawing.Color.Transparent;
            this.designerBarLabel2.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerBarLabel2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBarLabel2.Location = new System.Drawing.Point(20, 150);
            this.designerBarLabel2.Name = "designerBarLabel2";
            this.designerBarLabel2.Size = new System.Drawing.Size(110, 24);
            this.designerBarLabel2.Text = "Adventure";
            this._chart.Controls.Add(this.designerBarLabel2);
            this.designerBar2 = new System.Windows.Forms.Panel();
            this.designerBar2.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerBar2.Location = new System.Drawing.Point(130, 150);
            this.designerBar2.Name = "designerBar2";
            this.designerBar2.Size = new System.Drawing.Size(385, 24);
            this._chart.Controls.Add(this.designerBar2);
            this.designerBarValue2 = new System.Windows.Forms.Label();
            this.designerBarValue2.AutoSize = false;
            this.designerBarValue2.BackColor = System.Drawing.Color.Transparent;
            this.designerBarValue2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBarValue2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBarValue2.Location = new System.Drawing.Point(570, 150);
            this.designerBarValue2.Name = "designerBarValue2";
            this.designerBarValue2.Size = new System.Drawing.Size(130, 24);
            this.designerBarValue2.Text = "Tk 1.3M";
            this._chart.Controls.Add(this.designerBarValue2);
            this.designerBarLabel3 = new System.Windows.Forms.Label();
            this.designerBarLabel3.AutoSize = false;
            this.designerBarLabel3.BackColor = System.Drawing.Color.Transparent;
            this.designerBarLabel3.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerBarLabel3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBarLabel3.Location = new System.Drawing.Point(20, 220);
            this.designerBarLabel3.Name = "designerBarLabel3";
            this.designerBarLabel3.Size = new System.Drawing.Size(110, 24);
            this.designerBarLabel3.Text = "Racing";
            this._chart.Controls.Add(this.designerBarLabel3);
            this.designerBar3 = new System.Windows.Forms.Panel();
            this.designerBar3.BackColor = System.Drawing.Color.FromArgb(58, 159, 255);
            this.designerBar3.Location = new System.Drawing.Point(130, 220);
            this.designerBar3.Name = "designerBar3";
            this.designerBar3.Size = new System.Drawing.Size(340, 24);
            this._chart.Controls.Add(this.designerBar3);
            this.designerBarValue3 = new System.Windows.Forms.Label();
            this.designerBarValue3.AutoSize = false;
            this.designerBarValue3.BackColor = System.Drawing.Color.Transparent;
            this.designerBarValue3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBarValue3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBarValue3.Location = new System.Drawing.Point(570, 220);
            this.designerBarValue3.Name = "designerBarValue3";
            this.designerBarValue3.Size = new System.Drawing.Size(130, 24);
            this.designerBarValue3.Text = "Tk 1.1M";
            this._chart.Controls.Add(this.designerBarValue3);
            this.designerBarLabel4 = new System.Windows.Forms.Label();
            this.designerBarLabel4.AutoSize = false;
            this.designerBarLabel4.BackColor = System.Drawing.Color.Transparent;
            this.designerBarLabel4.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerBarLabel4.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBarLabel4.Location = new System.Drawing.Point(20, 285);
            this.designerBarLabel4.Name = "designerBarLabel4";
            this.designerBarLabel4.Size = new System.Drawing.Size(110, 24);
            this.designerBarLabel4.Text = "RPG";
            this._chart.Controls.Add(this.designerBarLabel4);
            this.designerBar4 = new System.Windows.Forms.Panel();
            this.designerBar4.BackColor = System.Drawing.Color.FromArgb(72, 201, 154);
            this.designerBar4.Location = new System.Drawing.Point(130, 285);
            this.designerBar4.Name = "designerBar4";
            this.designerBar4.Size = new System.Drawing.Size(295, 24);
            this._chart.Controls.Add(this.designerBar4);
            this.designerBarValue4 = new System.Windows.Forms.Label();
            this.designerBarValue4.AutoSize = false;
            this.designerBarValue4.BackColor = System.Drawing.Color.Transparent;
            this.designerBarValue4.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBarValue4.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBarValue4.Location = new System.Drawing.Point(570, 285);
            this.designerBarValue4.Name = "designerBarValue4";
            this.designerBarValue4.Size = new System.Drawing.Size(130, 24);
            this.designerBarValue4.Text = "Tk 0.9M";
            this._chart.Controls.Add(this.designerBarValue4);
            this.designerBarLabel5 = new System.Windows.Forms.Label();
            this.designerBarLabel5.AutoSize = false;
            this.designerBarLabel5.BackColor = System.Drawing.Color.Transparent;
            this.designerBarLabel5.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerBarLabel5.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBarLabel5.Location = new System.Drawing.Point(20, 350);
            this.designerBarLabel5.Name = "designerBarLabel5";
            this.designerBarLabel5.Size = new System.Drawing.Size(110, 24);
            this.designerBarLabel5.Text = "Strategy";
            this._chart.Controls.Add(this.designerBarLabel5);
            this.designerBar5 = new System.Windows.Forms.Panel();
            this.designerBar5.BackColor = System.Drawing.Color.FromArgb(247, 190, 89);
            this.designerBar5.Location = new System.Drawing.Point(130, 350);
            this.designerBar5.Name = "designerBar5";
            this.designerBar5.Size = new System.Drawing.Size(250, 24);
            this._chart.Controls.Add(this.designerBar5);
            this.designerBarValue5 = new System.Windows.Forms.Label();
            this.designerBarValue5.AutoSize = false;
            this.designerBarValue5.BackColor = System.Drawing.Color.Transparent;
            this.designerBarValue5.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBarValue5.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBarValue5.Location = new System.Drawing.Point(570, 350);
            this.designerBarValue5.Name = "designerBarValue5";
            this.designerBarValue5.Size = new System.Drawing.Size(130, 24);
            this.designerBarValue5.Text = "Tk 0.7M";
            this._chart.Controls.Add(this.designerBarValue5);
            this.designerSummary = new System.Windows.Forms.Panel();
            this.designerSummary.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerSummary.Location = new System.Drawing.Point(818, 112);
            this.designerSummary.Name = "designerSummary";
            this.designerSummary.Size = new System.Drawing.Size(434, 620);
            this.Controls.Add(this.designerSummary);
            this.designerSummaryPill = new System.Windows.Forms.Label();
            this.designerSummaryPill.AutoSize = false;
            this.designerSummaryPill.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerSummaryPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerSummaryPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerSummaryPill.Location = new System.Drawing.Point(18, 16);
            this.designerSummaryPill.Name = "designerSummaryPill";
            this.designerSummaryPill.Size = new System.Drawing.Size(84, 26);
            this.designerSummaryPill.Text = "OVERVIEW";
            this.designerSummaryPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerSummary.Controls.Add(this.designerSummaryPill);
            this.designerSummaryTitle = new System.Windows.Forms.Label();
            this.designerSummaryTitle.AutoSize = false;
            this.designerSummaryTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSummaryTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerSummaryTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.designerSummaryTitle.Location = new System.Drawing.Point(18, 50);
            this.designerSummaryTitle.Name = "designerSummaryTitle";
            this.designerSummaryTitle.Size = new System.Drawing.Size(280, 34);
            this.designerSummaryTitle.Text = "Shop Summary";
            this.designerSummary.Controls.Add(this.designerSummaryTitle);
            this.designerSummarySub = new System.Windows.Forms.Label();
            this.designerSummarySub.AutoSize = false;
            this.designerSummarySub.BackColor = System.Drawing.Color.Transparent;
            this.designerSummarySub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSummarySub.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerSummarySub.Location = new System.Drawing.Point(18, 82);
            this.designerSummarySub.Name = "designerSummarySub";
            this.designerSummarySub.Size = new System.Drawing.Size(300, 24);
            this.designerSummarySub.Text = "Current database totals";
            this.designerSummary.Controls.Add(this.designerSummarySub);
            this._lblSummary = new System.Windows.Forms.Label();
            this._lblSummary.AutoSize = false;
            this._lblSummary.BackColor = System.Drawing.Color.Transparent;
            this._lblSummary.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._lblSummary.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this._lblSummary.Location = new System.Drawing.Point(18, 132);
            this._lblSummary.Name = "_lblSummary";
            this._lblSummary.Size = new System.Drawing.Size(390, 380);
            this._lblSummary.Text = "GROSS REVENUE\r\nTk 4,820,500\r\n\r\nTOTAL ORDERS\r\n1,284\r\n\r\nTOTAL GAMES\r\n128\r\n\r\nACTIVE USERS\r\n846";
            this.designerSummary.Controls.Add(this._lblSummary);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(1280, 760);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(1050, 700);
            this.Name = "ReportsForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - Reports & Analytics";
        }

        private System.Windows.Forms.Label designerTitle;
        private System.Windows.Forms.Label designerSubtitle;
        private System.Windows.Forms.Button designerBack;
        private System.Windows.Forms.Panel designerChartCard;
        private System.Windows.Forms.Label designerChartPill;
        private System.Windows.Forms.Label designerChartTitle;
        private System.Windows.Forms.Label designerChartSub;
        private System.Windows.Forms.Label designerBarLabel1;
        private System.Windows.Forms.Panel designerBar1;
        private System.Windows.Forms.Label designerBarValue1;
        private System.Windows.Forms.Label designerBarLabel2;
        private System.Windows.Forms.Panel designerBar2;
        private System.Windows.Forms.Label designerBarValue2;
        private System.Windows.Forms.Label designerBarLabel3;
        private System.Windows.Forms.Panel designerBar3;
        private System.Windows.Forms.Label designerBarValue3;
        private System.Windows.Forms.Label designerBarLabel4;
        private System.Windows.Forms.Panel designerBar4;
        private System.Windows.Forms.Label designerBarValue4;
        private System.Windows.Forms.Label designerBarLabel5;
        private System.Windows.Forms.Panel designerBar5;
        private System.Windows.Forms.Label designerBarValue5;
        private System.Windows.Forms.Panel designerSummary;
        private System.Windows.Forms.Label designerSummaryPill;
        private System.Windows.Forms.Label designerSummaryTitle;
        private System.Windows.Forms.Label designerSummarySub;
    }
}
