namespace GameHub.Forms
{
    partial class StoreForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerTitle = new System.Windows.Forms.Label();
            this.designerTitle.AutoSize = false;
            this.designerTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.designerTitle.Location = new System.Drawing.Point(28, 22);
            this.designerTitle.Name = "designerTitle";
            this.designerTitle.Size = new System.Drawing.Size(520, 42);
            this.designerTitle.Text = "GameHub Store";
            this.Controls.Add(this.designerTitle);
            this.designerSubtitle = new System.Windows.Forms.Label();
            this.designerSubtitle.AutoSize = false;
            this.designerSubtitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSubtitle.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSubtitle.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerSubtitle.Location = new System.Drawing.Point(30, 56);
            this.designerSubtitle.Name = "designerSubtitle";
            this.designerSubtitle.Size = new System.Drawing.Size(720, 28);
            this.designerSubtitle.Text = "Browse games, build your wishlist and complete purchases.";
            this.Controls.Add(this.designerSubtitle);
            this.designerBack = new System.Windows.Forms.Button();
            this.designerBack.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBack.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBack.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBack.Location = new System.Drawing.Point(998, 20);
            this.designerBack.Name = "designerBack";
            this.designerBack.Size = new System.Drawing.Size(96, 34);
            this.designerBack.Text = "←  Back";
            this.designerBack.UseVisualStyleBackColor = false;
            this.Controls.Add(this.designerBack);
            this.designerHero = new System.Windows.Forms.Panel();
            this.designerHero.BackColor = System.Drawing.Color.FromArgb(74, 65, 220);
            this.designerHero.Location = new System.Drawing.Point(28, 92);
            this.designerHero.Name = "designerHero";
            this.designerHero.Size = new System.Drawing.Size(1064, 144);
            this.Controls.Add(this.designerHero);
            this.designerHeroPill = new System.Windows.Forms.Label();
            this.designerHeroPill.AutoSize = false;
            this.designerHeroPill.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerHeroPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerHeroPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerHeroPill.Location = new System.Drawing.Point(22, 18);
            this.designerHeroPill.Name = "designerHeroPill";
            this.designerHeroPill.Size = new System.Drawing.Size(64, 26);
            this.designerHeroPill.Text = "STORE";
            this.designerHeroPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerHero.Controls.Add(this.designerHeroPill);
            this.designerHeroTitle = new System.Windows.Forms.Label();
            this.designerHeroTitle.AutoSize = false;
            this.designerHeroTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerHeroTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerHeroTitle.Font = new System.Drawing.Font("Segoe UI", 21F, System.Drawing.FontStyle.Bold);
            this.designerHeroTitle.Location = new System.Drawing.Point(22, 52);
            this.designerHeroTitle.Name = "designerHeroTitle";
            this.designerHeroTitle.Size = new System.Drawing.Size(600, 44);
            this.designerHeroTitle.Text = "Find your next favorite game.";
            this.designerHero.Controls.Add(this.designerHeroTitle);
            this.designerHeroSub = new System.Windows.Forms.Label();
            this.designerHeroSub.AutoSize = false;
            this.designerHeroSub.BackColor = System.Drawing.Color.Transparent;
            this.designerHeroSub.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerHeroSub.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this.designerHeroSub.Location = new System.Drawing.Point(24, 98);
            this.designerHeroSub.Name = "designerHeroSub";
            this.designerHeroSub.Size = new System.Drawing.Size(780, 28);
            this.designerHeroSub.Text = "Search the catalog, filter by genre and add titles to your cart or wishlist.";
            this.designerHero.Controls.Add(this.designerHeroSub);
            this.designerSearchPanel = new System.Windows.Forms.Panel();
            this.designerSearchPanel.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerSearchPanel.Location = new System.Drawing.Point(28, 254);
            this.designerSearchPanel.Name = "designerSearchPanel";
            this.designerSearchPanel.Size = new System.Drawing.Size(1064, 72);
            this.Controls.Add(this.designerSearchPanel);
            this.designerSearchLabel = new System.Windows.Forms.Label();
            this.designerSearchLabel.AutoSize = false;
            this.designerSearchLabel.BackColor = System.Drawing.Color.Transparent;
            this.designerSearchLabel.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSearchLabel.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerSearchLabel.Location = new System.Drawing.Point(18, 22);
            this.designerSearchLabel.Name = "designerSearchLabel";
            this.designerSearchLabel.Size = new System.Drawing.Size(70, 24);
            this.designerSearchLabel.Text = "SEARCH";
            this.designerSearchPanel.Controls.Add(this.designerSearchLabel);
            this._txtSearch = new System.Windows.Forms.TextBox();
            this._txtSearch.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtSearch.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtSearch.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtSearch.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtSearch.Location = new System.Drawing.Point(92, 19);
            this._txtSearch.Name = "_txtSearch";
            this._txtSearch.Size = new System.Drawing.Size(480, 32);
            this.designerSearchPanel.Controls.Add(this._txtSearch);
            this.designerStoreSearch = new System.Windows.Forms.Button();
            this.designerStoreSearch.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerStoreSearch.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerStoreSearch.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreSearch.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerStoreSearch.Location = new System.Drawing.Point(584, 18);
            this.designerStoreSearch.Name = "designerStoreSearch";
            this.designerStoreSearch.Size = new System.Drawing.Size(100, 34);
            this.designerStoreSearch.Text = "SEARCH";
            this.designerStoreSearch.UseVisualStyleBackColor = false;
            this.designerSearchPanel.Controls.Add(this.designerStoreSearch);
            this._cboGenre = new System.Windows.Forms.ComboBox();
            this._cboGenre.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._cboGenre.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._cboGenre.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._cboGenre.Location = new System.Drawing.Point(696, 19);
            this._cboGenre.Name = "_cboGenre";
            this._cboGenre.Size = new System.Drawing.Size(150, 32);
            this._cboGenre.Items.AddRange(new object[] { "All genres", "Action", "Adventure" });
            this._cboGenre.SelectedIndex = 0;
            this.designerSearchPanel.Controls.Add(this._cboGenre);
            this.designerWishlist = new System.Windows.Forms.Button();
            this.designerWishlist.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerWishlist.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerWishlist.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerWishlist.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerWishlist.Location = new System.Drawing.Point(858, 18);
            this.designerWishlist.Name = "designerWishlist";
            this.designerWishlist.Size = new System.Drawing.Size(92, 34);
            this.designerWishlist.Text = "WISHLIST";
            this.designerWishlist.UseVisualStyleBackColor = false;
            this.designerSearchPanel.Controls.Add(this.designerWishlist);
            this._btnCart = new System.Windows.Forms.Button();
            this._btnCart.BackColor = System.Drawing.Color.FromArgb(72, 201, 154);
            this._btnCart.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this._btnCart.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._btnCart.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this._btnCart.Location = new System.Drawing.Point(960, 18);
            this._btnCart.Name = "_btnCart";
            this._btnCart.Size = new System.Drawing.Size(86, 34);
            this._btnCart.Text = "CART (0)";
            this._btnCart.UseVisualStyleBackColor = false;
            this.designerSearchPanel.Controls.Add(this._btnCart);
            this._flow = new System.Windows.Forms.FlowLayoutPanel();
            this._flow.AutoScroll = true;
            this._flow.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this._flow.Location = new System.Drawing.Point(28, 346);
            this._flow.Name = "_flow";
            this._flow.Size = new System.Drawing.Size(1064, 326);
            this.Controls.Add(this._flow);
            this.designerStoreCard1 = new System.Windows.Forms.Panel();
            this.designerStoreCard1.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerStoreCard1.Location = new System.Drawing.Point(0, 0);
            this.designerStoreCard1.Name = "designerStoreCard1";
            this.designerStoreCard1.Size = new System.Drawing.Size(310, 290);
            this._flow.Controls.Add(this.designerStoreCard1);
            this.designerStoreCard1.Margin = new System.Windows.Forms.Padding(0, 0, 16, 16);
            this.designerStoreCard1Art = new System.Windows.Forms.Panel();
            this.designerStoreCard1Art.BackColor = System.Drawing.Color.FromArgb(74, 65, 220);
            this.designerStoreCard1Art.Location = new System.Drawing.Point(0, 0);
            this.designerStoreCard1Art.Name = "designerStoreCard1Art";
            this.designerStoreCard1Art.Size = new System.Drawing.Size(310, 130);
            this.designerStoreCard1.Controls.Add(this.designerStoreCard1Art);
            this.designerStoreCard1Title = new System.Windows.Forms.Label();
            this.designerStoreCard1Title.AutoSize = false;
            this.designerStoreCard1Title.BackColor = System.Drawing.Color.Transparent;
            this.designerStoreCard1Title.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard1Title.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard1Title.Location = new System.Drawing.Point(14, 146);
            this.designerStoreCard1Title.Name = "designerStoreCard1Title";
            this.designerStoreCard1Title.Size = new System.Drawing.Size(280, 30);
            this.designerStoreCard1Title.Text = "Neon Strike";
            this.designerStoreCard1.Controls.Add(this.designerStoreCard1Title);
            this.designerStoreCard1Meta = new System.Windows.Forms.Label();
            this.designerStoreCard1Meta.AutoSize = false;
            this.designerStoreCard1Meta.BackColor = System.Drawing.Color.Transparent;
            this.designerStoreCard1Meta.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerStoreCard1Meta.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerStoreCard1Meta.Location = new System.Drawing.Point(14, 178);
            this.designerStoreCard1Meta.Name = "designerStoreCard1Meta";
            this.designerStoreCard1Meta.Size = new System.Drawing.Size(280, 24);
            this.designerStoreCard1Meta.Text = "Action • In stock";
            this.designerStoreCard1.Controls.Add(this.designerStoreCard1Meta);
            this.designerStoreCard1Price = new System.Windows.Forms.Label();
            this.designerStoreCard1Price.AutoSize = false;
            this.designerStoreCard1Price.BackColor = System.Drawing.Color.Transparent;
            this.designerStoreCard1Price.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard1Price.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard1Price.Location = new System.Drawing.Point(14, 210);
            this.designerStoreCard1Price.Name = "designerStoreCard1Price";
            this.designerStoreCard1Price.Size = new System.Drawing.Size(120, 30);
            this.designerStoreCard1Price.Text = "Tk 1,999";
            this.designerStoreCard1.Controls.Add(this.designerStoreCard1Price);
            this.designerStoreCard1Wish = new System.Windows.Forms.Button();
            this.designerStoreCard1Wish.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerStoreCard1Wish.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerStoreCard1Wish.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard1Wish.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard1Wish.Location = new System.Drawing.Point(190, 210);
            this.designerStoreCard1Wish.Name = "designerStoreCard1Wish";
            this.designerStoreCard1Wish.Size = new System.Drawing.Size(44, 34);
            this.designerStoreCard1Wish.Text = "♡";
            this.designerStoreCard1Wish.UseVisualStyleBackColor = false;
            this.designerStoreCard1.Controls.Add(this.designerStoreCard1Wish);
            this.designerStoreCard1Add = new System.Windows.Forms.Button();
            this.designerStoreCard1Add.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerStoreCard1Add.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerStoreCard1Add.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard1Add.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard1Add.Location = new System.Drawing.Point(242, 210);
            this.designerStoreCard1Add.Name = "designerStoreCard1Add";
            this.designerStoreCard1Add.Size = new System.Drawing.Size(54, 34);
            this.designerStoreCard1Add.Text = "ADD";
            this.designerStoreCard1Add.UseVisualStyleBackColor = false;
            this.designerStoreCard1.Controls.Add(this.designerStoreCard1Add);
            this.designerStoreCard2 = new System.Windows.Forms.Panel();
            this.designerStoreCard2.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerStoreCard2.Location = new System.Drawing.Point(0, 0);
            this.designerStoreCard2.Name = "designerStoreCard2";
            this.designerStoreCard2.Size = new System.Drawing.Size(310, 290);
            this._flow.Controls.Add(this.designerStoreCard2);
            this.designerStoreCard2.Margin = new System.Windows.Forms.Padding(0, 0, 16, 16);
            this.designerStoreCard2Art = new System.Windows.Forms.Panel();
            this.designerStoreCard2Art.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerStoreCard2Art.Location = new System.Drawing.Point(0, 0);
            this.designerStoreCard2Art.Name = "designerStoreCard2Art";
            this.designerStoreCard2Art.Size = new System.Drawing.Size(310, 130);
            this.designerStoreCard2.Controls.Add(this.designerStoreCard2Art);
            this.designerStoreCard2Title = new System.Windows.Forms.Label();
            this.designerStoreCard2Title.AutoSize = false;
            this.designerStoreCard2Title.BackColor = System.Drawing.Color.Transparent;
            this.designerStoreCard2Title.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard2Title.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard2Title.Location = new System.Drawing.Point(14, 146);
            this.designerStoreCard2Title.Name = "designerStoreCard2Title";
            this.designerStoreCard2Title.Size = new System.Drawing.Size(280, 30);
            this.designerStoreCard2Title.Text = "Velocity X";
            this.designerStoreCard2.Controls.Add(this.designerStoreCard2Title);
            this.designerStoreCard2Meta = new System.Windows.Forms.Label();
            this.designerStoreCard2Meta.AutoSize = false;
            this.designerStoreCard2Meta.BackColor = System.Drawing.Color.Transparent;
            this.designerStoreCard2Meta.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerStoreCard2Meta.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerStoreCard2Meta.Location = new System.Drawing.Point(14, 178);
            this.designerStoreCard2Meta.Name = "designerStoreCard2Meta";
            this.designerStoreCard2Meta.Size = new System.Drawing.Size(280, 24);
            this.designerStoreCard2Meta.Text = "Racing • In stock";
            this.designerStoreCard2.Controls.Add(this.designerStoreCard2Meta);
            this.designerStoreCard2Price = new System.Windows.Forms.Label();
            this.designerStoreCard2Price.AutoSize = false;
            this.designerStoreCard2Price.BackColor = System.Drawing.Color.Transparent;
            this.designerStoreCard2Price.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard2Price.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard2Price.Location = new System.Drawing.Point(14, 210);
            this.designerStoreCard2Price.Name = "designerStoreCard2Price";
            this.designerStoreCard2Price.Size = new System.Drawing.Size(120, 30);
            this.designerStoreCard2Price.Text = "Tk 2,499";
            this.designerStoreCard2.Controls.Add(this.designerStoreCard2Price);
            this.designerStoreCard2Wish = new System.Windows.Forms.Button();
            this.designerStoreCard2Wish.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerStoreCard2Wish.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerStoreCard2Wish.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard2Wish.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard2Wish.Location = new System.Drawing.Point(190, 210);
            this.designerStoreCard2Wish.Name = "designerStoreCard2Wish";
            this.designerStoreCard2Wish.Size = new System.Drawing.Size(44, 34);
            this.designerStoreCard2Wish.Text = "♡";
            this.designerStoreCard2Wish.UseVisualStyleBackColor = false;
            this.designerStoreCard2.Controls.Add(this.designerStoreCard2Wish);
            this.designerStoreCard2Add = new System.Windows.Forms.Button();
            this.designerStoreCard2Add.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerStoreCard2Add.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerStoreCard2Add.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard2Add.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard2Add.Location = new System.Drawing.Point(242, 210);
            this.designerStoreCard2Add.Name = "designerStoreCard2Add";
            this.designerStoreCard2Add.Size = new System.Drawing.Size(54, 34);
            this.designerStoreCard2Add.Text = "ADD";
            this.designerStoreCard2Add.UseVisualStyleBackColor = false;
            this.designerStoreCard2.Controls.Add(this.designerStoreCard2Add);
            this.designerStoreCard3 = new System.Windows.Forms.Panel();
            this.designerStoreCard3.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerStoreCard3.Location = new System.Drawing.Point(0, 0);
            this.designerStoreCard3.Name = "designerStoreCard3";
            this.designerStoreCard3.Size = new System.Drawing.Size(310, 290);
            this._flow.Controls.Add(this.designerStoreCard3);
            this.designerStoreCard3.Margin = new System.Windows.Forms.Padding(0, 0, 16, 16);
            this.designerStoreCard3Art = new System.Windows.Forms.Panel();
            this.designerStoreCard3Art.BackColor = System.Drawing.Color.FromArgb(58, 159, 255);
            this.designerStoreCard3Art.Location = new System.Drawing.Point(0, 0);
            this.designerStoreCard3Art.Name = "designerStoreCard3Art";
            this.designerStoreCard3Art.Size = new System.Drawing.Size(310, 130);
            this.designerStoreCard3.Controls.Add(this.designerStoreCard3Art);
            this.designerStoreCard3Title = new System.Windows.Forms.Label();
            this.designerStoreCard3Title.AutoSize = false;
            this.designerStoreCard3Title.BackColor = System.Drawing.Color.Transparent;
            this.designerStoreCard3Title.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard3Title.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard3Title.Location = new System.Drawing.Point(14, 146);
            this.designerStoreCard3Title.Name = "designerStoreCard3Title";
            this.designerStoreCard3Title.Size = new System.Drawing.Size(280, 30);
            this.designerStoreCard3Title.Text = "Lost Horizon";
            this.designerStoreCard3.Controls.Add(this.designerStoreCard3Title);
            this.designerStoreCard3Meta = new System.Windows.Forms.Label();
            this.designerStoreCard3Meta.AutoSize = false;
            this.designerStoreCard3Meta.BackColor = System.Drawing.Color.Transparent;
            this.designerStoreCard3Meta.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerStoreCard3Meta.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerStoreCard3Meta.Location = new System.Drawing.Point(14, 178);
            this.designerStoreCard3Meta.Name = "designerStoreCard3Meta";
            this.designerStoreCard3Meta.Size = new System.Drawing.Size(280, 24);
            this.designerStoreCard3Meta.Text = "Adventure • In stock";
            this.designerStoreCard3.Controls.Add(this.designerStoreCard3Meta);
            this.designerStoreCard3Price = new System.Windows.Forms.Label();
            this.designerStoreCard3Price.AutoSize = false;
            this.designerStoreCard3Price.BackColor = System.Drawing.Color.Transparent;
            this.designerStoreCard3Price.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard3Price.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard3Price.Location = new System.Drawing.Point(14, 210);
            this.designerStoreCard3Price.Name = "designerStoreCard3Price";
            this.designerStoreCard3Price.Size = new System.Drawing.Size(120, 30);
            this.designerStoreCard3Price.Text = "Tk 1,499";
            this.designerStoreCard3.Controls.Add(this.designerStoreCard3Price);
            this.designerStoreCard3Wish = new System.Windows.Forms.Button();
            this.designerStoreCard3Wish.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerStoreCard3Wish.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerStoreCard3Wish.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard3Wish.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard3Wish.Location = new System.Drawing.Point(190, 210);
            this.designerStoreCard3Wish.Name = "designerStoreCard3Wish";
            this.designerStoreCard3Wish.Size = new System.Drawing.Size(44, 34);
            this.designerStoreCard3Wish.Text = "♡";
            this.designerStoreCard3Wish.UseVisualStyleBackColor = false;
            this.designerStoreCard3.Controls.Add(this.designerStoreCard3Wish);
            this.designerStoreCard3Add = new System.Windows.Forms.Button();
            this.designerStoreCard3Add.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerStoreCard3Add.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerStoreCard3Add.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerStoreCard3Add.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerStoreCard3Add.Location = new System.Drawing.Point(242, 210);
            this.designerStoreCard3Add.Name = "designerStoreCard3Add";
            this.designerStoreCard3Add.Size = new System.Drawing.Size(54, 34);
            this.designerStoreCard3Add.Text = "ADD";
            this.designerStoreCard3Add.UseVisualStyleBackColor = false;
            this.designerStoreCard3.Controls.Add(this.designerStoreCard3Add);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(1120, 700);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(900, 600);
            this.Name = "StoreForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - Store";
        }

        private System.Windows.Forms.Label designerTitle;
        private System.Windows.Forms.Label designerSubtitle;
        private System.Windows.Forms.Button designerBack;
        private System.Windows.Forms.Panel designerHero;
        private System.Windows.Forms.Label designerHeroPill;
        private System.Windows.Forms.Label designerHeroTitle;
        private System.Windows.Forms.Label designerHeroSub;
        private System.Windows.Forms.Panel designerSearchPanel;
        private System.Windows.Forms.Label designerSearchLabel;
        private System.Windows.Forms.Button designerStoreSearch;
        private System.Windows.Forms.Button designerWishlist;
        private System.Windows.Forms.Panel designerStoreCard1;
        private System.Windows.Forms.Panel designerStoreCard1Art;
        private System.Windows.Forms.Label designerStoreCard1Title;
        private System.Windows.Forms.Label designerStoreCard1Meta;
        private System.Windows.Forms.Label designerStoreCard1Price;
        private System.Windows.Forms.Button designerStoreCard1Wish;
        private System.Windows.Forms.Button designerStoreCard1Add;
        private System.Windows.Forms.Panel designerStoreCard2;
        private System.Windows.Forms.Panel designerStoreCard2Art;
        private System.Windows.Forms.Label designerStoreCard2Title;
        private System.Windows.Forms.Label designerStoreCard2Meta;
        private System.Windows.Forms.Label designerStoreCard2Price;
        private System.Windows.Forms.Button designerStoreCard2Wish;
        private System.Windows.Forms.Button designerStoreCard2Add;
        private System.Windows.Forms.Panel designerStoreCard3;
        private System.Windows.Forms.Panel designerStoreCard3Art;
        private System.Windows.Forms.Label designerStoreCard3Title;
        private System.Windows.Forms.Label designerStoreCard3Meta;
        private System.Windows.Forms.Label designerStoreCard3Price;
        private System.Windows.Forms.Button designerStoreCard3Wish;
        private System.Windows.Forms.Button designerStoreCard3Add;
    }
}
