namespace GameHub.Forms
{
    partial class SubscriptionForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerTitle = new System.Windows.Forms.Label();
            this.designerTitle.AutoSize = false;
            this.designerTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.designerTitle.Location = new System.Drawing.Point(28, 22);
            this.designerTitle.Name = "designerTitle";
            this.designerTitle.Size = new System.Drawing.Size(520, 42);
            this.designerTitle.Text = "GameHub Pass";
            this.Controls.Add(this.designerTitle);
            this.designerSubtitle = new System.Windows.Forms.Label();
            this.designerSubtitle.AutoSize = false;
            this.designerSubtitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSubtitle.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSubtitle.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerSubtitle.Location = new System.Drawing.Point(30, 54);
            this.designerSubtitle.Name = "designerSubtitle";
            this.designerSubtitle.Size = new System.Drawing.Size(780, 28);
            this.designerSubtitle.Text = "Choose a membership tier and unlock discounts, rewards and early access.";
            this.Controls.Add(this.designerSubtitle);
            this.designerBack = new System.Windows.Forms.Button();
            this.designerBack.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBack.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBack.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBack.Location = new System.Drawing.Point(916, 20);
            this.designerBack.Name = "designerBack";
            this.designerBack.Size = new System.Drawing.Size(96, 34);
            this.designerBack.Text = "←  Back";
            this.designerBack.UseVisualStyleBackColor = false;
            this.Controls.Add(this.designerBack);
            this.designerPlan1 = new System.Windows.Forms.Panel();
            this.designerPlan1.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerPlan1.Location = new System.Drawing.Point(28, 102);
            this.designerPlan1.Name = "designerPlan1";
            this.designerPlan1.Size = new System.Drawing.Size(312, 510);
            this.Controls.Add(this.designerPlan1);
            this.designerPlan1Head = new System.Windows.Forms.Panel();
            this.designerPlan1Head.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerPlan1Head.Location = new System.Drawing.Point(0, 0);
            this.designerPlan1Head.Name = "designerPlan1Head";
            this.designerPlan1Head.Size = new System.Drawing.Size(312, 126);
            this.designerPlan1.Controls.Add(this.designerPlan1Head);
            this.designerPlan1Pill = new System.Windows.Forms.Label();
            this.designerPlan1Pill.AutoSize = false;
            this.designerPlan1Pill.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerPlan1Pill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerPlan1Pill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerPlan1Pill.Location = new System.Drawing.Point(20, 18);
            this.designerPlan1Pill.Name = "designerPlan1Pill";
            this.designerPlan1Pill.Size = new System.Drawing.Size(56, 26);
            this.designerPlan1Pill.Text = "PASS";
            this.designerPlan1Pill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerPlan1Head.Controls.Add(this.designerPlan1Pill);
            this.designerPlan1Name = new System.Windows.Forms.Label();
            this.designerPlan1Name.AutoSize = false;
            this.designerPlan1Name.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan1Name.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan1Name.Font = new System.Drawing.Font("Segoe UI", 17F, System.Drawing.FontStyle.Bold);
            this.designerPlan1Name.Location = new System.Drawing.Point(20, 52);
            this.designerPlan1Name.Name = "designerPlan1Name";
            this.designerPlan1Name.Size = new System.Drawing.Size(250, 32);
            this.designerPlan1Name.Text = "BASIC";
            this.designerPlan1Head.Controls.Add(this.designerPlan1Name);
            this.designerPlan1Discount = new System.Windows.Forms.Label();
            this.designerPlan1Discount.AutoSize = false;
            this.designerPlan1Discount.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan1Discount.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerPlan1Discount.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerPlan1Discount.Location = new System.Drawing.Point(20, 88);
            this.designerPlan1Discount.Name = "designerPlan1Discount";
            this.designerPlan1Discount.Size = new System.Drawing.Size(250, 24);
            this.designerPlan1Discount.Text = "5% store discount";
            this.designerPlan1Head.Controls.Add(this.designerPlan1Discount);
            this.designerPlan1Price = new System.Windows.Forms.Label();
            this.designerPlan1Price.AutoSize = false;
            this.designerPlan1Price.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan1Price.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan1Price.Font = new System.Drawing.Font("Segoe UI", 22F, System.Drawing.FontStyle.Bold);
            this.designerPlan1Price.Location = new System.Drawing.Point(20, 144);
            this.designerPlan1Price.Name = "designerPlan1Price";
            this.designerPlan1Price.Size = new System.Drawing.Size(220, 42);
            this.designerPlan1Price.Text = "Tk 299";
            this.designerPlan1.Controls.Add(this.designerPlan1Price);
            this.designerPlan1Per = new System.Windows.Forms.Label();
            this.designerPlan1Per.AutoSize = false;
            this.designerPlan1Per.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan1Per.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerPlan1Per.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerPlan1Per.Location = new System.Drawing.Point(22, 184);
            this.designerPlan1Per.Name = "designerPlan1Per";
            this.designerPlan1Per.Size = new System.Drawing.Size(160, 22);
            this.designerPlan1Per.Text = "per month";
            this.designerPlan1.Controls.Add(this.designerPlan1Per);
            this.designerPlan1What = new System.Windows.Forms.Label();
            this.designerPlan1What.AutoSize = false;
            this.designerPlan1What.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan1What.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerPlan1What.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.designerPlan1What.Location = new System.Drawing.Point(20, 220);
            this.designerPlan1What.Name = "designerPlan1What";
            this.designerPlan1What.Size = new System.Drawing.Size(180, 24);
            this.designerPlan1What.Text = "WHAT YOU GET";
            this.designerPlan1.Controls.Add(this.designerPlan1What);
            this.designerPlan1Feat1 = new System.Windows.Forms.Label();
            this.designerPlan1Feat1.AutoSize = false;
            this.designerPlan1Feat1.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan1Feat1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan1Feat1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan1Feat1.Location = new System.Drawing.Point(20, 252);
            this.designerPlan1Feat1.Name = "designerPlan1Feat1";
            this.designerPlan1Feat1.Size = new System.Drawing.Size(270, 22);
            this.designerPlan1Feat1.Text = "✓  5% off every purchase";
            this.designerPlan1.Controls.Add(this.designerPlan1Feat1);
            this.designerPlan1Feat2 = new System.Windows.Forms.Label();
            this.designerPlan1Feat2.AutoSize = false;
            this.designerPlan1Feat2.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan1Feat2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan1Feat2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan1Feat2.Location = new System.Drawing.Point(20, 281);
            this.designerPlan1Feat2.Name = "designerPlan1Feat2";
            this.designerPlan1Feat2.Size = new System.Drawing.Size(270, 22);
            this.designerPlan1Feat2.Text = "✓  Wishlist price alerts";
            this.designerPlan1.Controls.Add(this.designerPlan1Feat2);
            this.designerPlan1Feat3 = new System.Windows.Forms.Label();
            this.designerPlan1Feat3.AutoSize = false;
            this.designerPlan1Feat3.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan1Feat3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan1Feat3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan1Feat3.Location = new System.Drawing.Point(20, 310);
            this.designerPlan1Feat3.Name = "designerPlan1Feat3";
            this.designerPlan1Feat3.Size = new System.Drawing.Size(270, 22);
            this.designerPlan1Feat3.Text = "✓  Standard support";
            this.designerPlan1.Controls.Add(this.designerPlan1Feat3);
            this.designerPlan1Feat4 = new System.Windows.Forms.Label();
            this.designerPlan1Feat4.AutoSize = false;
            this.designerPlan1Feat4.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan1Feat4.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan1Feat4.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan1Feat4.Location = new System.Drawing.Point(20, 339);
            this.designerPlan1Feat4.Name = "designerPlan1Feat4";
            this.designerPlan1Feat4.Size = new System.Drawing.Size(270, 22);
            this.designerPlan1Feat4.Text = "✓  Sale event access";
            this.designerPlan1.Controls.Add(this.designerPlan1Feat4);
            this.designerPlan1Choose = new System.Windows.Forms.Button();
            this.designerPlan1Choose.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerPlan1Choose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerPlan1Choose.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan1Choose.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerPlan1Choose.Location = new System.Drawing.Point(20, 446);
            this.designerPlan1Choose.Name = "designerPlan1Choose";
            this.designerPlan1Choose.Size = new System.Drawing.Size(272, 36);
            this.designerPlan1Choose.Text = "Choose Basic";
            this.designerPlan1Choose.UseVisualStyleBackColor = false;
            this.designerPlan1.Controls.Add(this.designerPlan1Choose);
            this.designerPlan2 = new System.Windows.Forms.Panel();
            this.designerPlan2.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerPlan2.Location = new System.Drawing.Point(360, 102);
            this.designerPlan2.Name = "designerPlan2";
            this.designerPlan2.Size = new System.Drawing.Size(312, 510);
            this.Controls.Add(this.designerPlan2);
            this.designerPlan2Head = new System.Windows.Forms.Panel();
            this.designerPlan2Head.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerPlan2Head.Location = new System.Drawing.Point(0, 0);
            this.designerPlan2Head.Name = "designerPlan2Head";
            this.designerPlan2Head.Size = new System.Drawing.Size(312, 126);
            this.designerPlan2.Controls.Add(this.designerPlan2Head);
            this.designerPlan2Pill = new System.Windows.Forms.Label();
            this.designerPlan2Pill.AutoSize = false;
            this.designerPlan2Pill.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerPlan2Pill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerPlan2Pill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerPlan2Pill.Location = new System.Drawing.Point(20, 18);
            this.designerPlan2Pill.Name = "designerPlan2Pill";
            this.designerPlan2Pill.Size = new System.Drawing.Size(78, 26);
            this.designerPlan2Pill.Text = "POPULAR";
            this.designerPlan2Pill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerPlan2Head.Controls.Add(this.designerPlan2Pill);
            this.designerPlan2Name = new System.Windows.Forms.Label();
            this.designerPlan2Name.AutoSize = false;
            this.designerPlan2Name.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan2Name.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan2Name.Font = new System.Drawing.Font("Segoe UI", 17F, System.Drawing.FontStyle.Bold);
            this.designerPlan2Name.Location = new System.Drawing.Point(20, 52);
            this.designerPlan2Name.Name = "designerPlan2Name";
            this.designerPlan2Name.Size = new System.Drawing.Size(250, 32);
            this.designerPlan2Name.Text = "PLUS";
            this.designerPlan2Head.Controls.Add(this.designerPlan2Name);
            this.designerPlan2Discount = new System.Windows.Forms.Label();
            this.designerPlan2Discount.AutoSize = false;
            this.designerPlan2Discount.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan2Discount.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerPlan2Discount.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerPlan2Discount.Location = new System.Drawing.Point(20, 88);
            this.designerPlan2Discount.Name = "designerPlan2Discount";
            this.designerPlan2Discount.Size = new System.Drawing.Size(250, 24);
            this.designerPlan2Discount.Text = "10% store discount";
            this.designerPlan2Head.Controls.Add(this.designerPlan2Discount);
            this.designerPlan2Price = new System.Windows.Forms.Label();
            this.designerPlan2Price.AutoSize = false;
            this.designerPlan2Price.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan2Price.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan2Price.Font = new System.Drawing.Font("Segoe UI", 22F, System.Drawing.FontStyle.Bold);
            this.designerPlan2Price.Location = new System.Drawing.Point(20, 144);
            this.designerPlan2Price.Name = "designerPlan2Price";
            this.designerPlan2Price.Size = new System.Drawing.Size(220, 42);
            this.designerPlan2Price.Text = "Tk 599";
            this.designerPlan2.Controls.Add(this.designerPlan2Price);
            this.designerPlan2Per = new System.Windows.Forms.Label();
            this.designerPlan2Per.AutoSize = false;
            this.designerPlan2Per.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan2Per.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerPlan2Per.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerPlan2Per.Location = new System.Drawing.Point(22, 184);
            this.designerPlan2Per.Name = "designerPlan2Per";
            this.designerPlan2Per.Size = new System.Drawing.Size(160, 22);
            this.designerPlan2Per.Text = "per month";
            this.designerPlan2.Controls.Add(this.designerPlan2Per);
            this.designerPlan2What = new System.Windows.Forms.Label();
            this.designerPlan2What.AutoSize = false;
            this.designerPlan2What.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan2What.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerPlan2What.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.designerPlan2What.Location = new System.Drawing.Point(20, 220);
            this.designerPlan2What.Name = "designerPlan2What";
            this.designerPlan2What.Size = new System.Drawing.Size(180, 24);
            this.designerPlan2What.Text = "WHAT YOU GET";
            this.designerPlan2.Controls.Add(this.designerPlan2What);
            this.designerPlan2Feat1 = new System.Windows.Forms.Label();
            this.designerPlan2Feat1.AutoSize = false;
            this.designerPlan2Feat1.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan2Feat1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan2Feat1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan2Feat1.Location = new System.Drawing.Point(20, 252);
            this.designerPlan2Feat1.Name = "designerPlan2Feat1";
            this.designerPlan2Feat1.Size = new System.Drawing.Size(270, 22);
            this.designerPlan2Feat1.Text = "✓  10% off every purchase";
            this.designerPlan2.Controls.Add(this.designerPlan2Feat1);
            this.designerPlan2Feat2 = new System.Windows.Forms.Label();
            this.designerPlan2Feat2.AutoSize = false;
            this.designerPlan2Feat2.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan2Feat2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan2Feat2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan2Feat2.Location = new System.Drawing.Point(20, 281);
            this.designerPlan2Feat2.Name = "designerPlan2Feat2";
            this.designerPlan2Feat2.Size = new System.Drawing.Size(270, 22);
            this.designerPlan2Feat2.Text = "✓  1 free game / month";
            this.designerPlan2.Controls.Add(this.designerPlan2Feat2);
            this.designerPlan2Feat3 = new System.Windows.Forms.Label();
            this.designerPlan2Feat3.AutoSize = false;
            this.designerPlan2Feat3.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan2Feat3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan2Feat3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan2Feat3.Location = new System.Drawing.Point(20, 310);
            this.designerPlan2Feat3.Name = "designerPlan2Feat3";
            this.designerPlan2Feat3.Size = new System.Drawing.Size(270, 22);
            this.designerPlan2Feat3.Text = "✓  Early pre-order access";
            this.designerPlan2.Controls.Add(this.designerPlan2Feat3);
            this.designerPlan2Feat4 = new System.Windows.Forms.Label();
            this.designerPlan2Feat4.AutoSize = false;
            this.designerPlan2Feat4.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan2Feat4.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan2Feat4.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan2Feat4.Location = new System.Drawing.Point(20, 339);
            this.designerPlan2Feat4.Name = "designerPlan2Feat4";
            this.designerPlan2Feat4.Size = new System.Drawing.Size(270, 22);
            this.designerPlan2Feat4.Text = "✓  2x loyalty points";
            this.designerPlan2.Controls.Add(this.designerPlan2Feat4);
            this.designerPlan2Feat5 = new System.Windows.Forms.Label();
            this.designerPlan2Feat5.AutoSize = false;
            this.designerPlan2Feat5.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan2Feat5.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan2Feat5.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan2Feat5.Location = new System.Drawing.Point(20, 368);
            this.designerPlan2Feat5.Name = "designerPlan2Feat5";
            this.designerPlan2Feat5.Size = new System.Drawing.Size(270, 22);
            this.designerPlan2Feat5.Text = "✓  Priority support";
            this.designerPlan2.Controls.Add(this.designerPlan2Feat5);
            this.designerPlan2Choose = new System.Windows.Forms.Button();
            this.designerPlan2Choose.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerPlan2Choose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerPlan2Choose.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan2Choose.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerPlan2Choose.Location = new System.Drawing.Point(20, 446);
            this.designerPlan2Choose.Name = "designerPlan2Choose";
            this.designerPlan2Choose.Size = new System.Drawing.Size(272, 36);
            this.designerPlan2Choose.Text = "Choose Plus";
            this.designerPlan2Choose.UseVisualStyleBackColor = false;
            this.designerPlan2.Controls.Add(this.designerPlan2Choose);
            this.designerPlan3 = new System.Windows.Forms.Panel();
            this.designerPlan3.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerPlan3.Location = new System.Drawing.Point(692, 102);
            this.designerPlan3.Name = "designerPlan3";
            this.designerPlan3.Size = new System.Drawing.Size(312, 510);
            this.Controls.Add(this.designerPlan3);
            this.designerPlan3Head = new System.Windows.Forms.Panel();
            this.designerPlan3Head.BackColor = System.Drawing.Color.FromArgb(247, 190, 89);
            this.designerPlan3Head.Location = new System.Drawing.Point(0, 0);
            this.designerPlan3Head.Name = "designerPlan3Head";
            this.designerPlan3Head.Size = new System.Drawing.Size(312, 126);
            this.designerPlan3.Controls.Add(this.designerPlan3Head);
            this.designerPlan3Pill = new System.Windows.Forms.Label();
            this.designerPlan3Pill.AutoSize = false;
            this.designerPlan3Pill.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerPlan3Pill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerPlan3Pill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerPlan3Pill.Location = new System.Drawing.Point(20, 18);
            this.designerPlan3Pill.Name = "designerPlan3Pill";
            this.designerPlan3Pill.Size = new System.Drawing.Size(56, 26);
            this.designerPlan3Pill.Text = "PASS";
            this.designerPlan3Pill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerPlan3Head.Controls.Add(this.designerPlan3Pill);
            this.designerPlan3Name = new System.Windows.Forms.Label();
            this.designerPlan3Name.AutoSize = false;
            this.designerPlan3Name.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan3Name.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan3Name.Font = new System.Drawing.Font("Segoe UI", 17F, System.Drawing.FontStyle.Bold);
            this.designerPlan3Name.Location = new System.Drawing.Point(20, 52);
            this.designerPlan3Name.Name = "designerPlan3Name";
            this.designerPlan3Name.Size = new System.Drawing.Size(250, 32);
            this.designerPlan3Name.Text = "ULTIMATE";
            this.designerPlan3Head.Controls.Add(this.designerPlan3Name);
            this.designerPlan3Discount = new System.Windows.Forms.Label();
            this.designerPlan3Discount.AutoSize = false;
            this.designerPlan3Discount.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan3Discount.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerPlan3Discount.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerPlan3Discount.Location = new System.Drawing.Point(20, 88);
            this.designerPlan3Discount.Name = "designerPlan3Discount";
            this.designerPlan3Discount.Size = new System.Drawing.Size(250, 24);
            this.designerPlan3Discount.Text = "15% store discount";
            this.designerPlan3Head.Controls.Add(this.designerPlan3Discount);
            this.designerPlan3Price = new System.Windows.Forms.Label();
            this.designerPlan3Price.AutoSize = false;
            this.designerPlan3Price.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan3Price.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan3Price.Font = new System.Drawing.Font("Segoe UI", 22F, System.Drawing.FontStyle.Bold);
            this.designerPlan3Price.Location = new System.Drawing.Point(20, 144);
            this.designerPlan3Price.Name = "designerPlan3Price";
            this.designerPlan3Price.Size = new System.Drawing.Size(220, 42);
            this.designerPlan3Price.Text = "Tk 999";
            this.designerPlan3.Controls.Add(this.designerPlan3Price);
            this.designerPlan3Per = new System.Windows.Forms.Label();
            this.designerPlan3Per.AutoSize = false;
            this.designerPlan3Per.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan3Per.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerPlan3Per.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerPlan3Per.Location = new System.Drawing.Point(22, 184);
            this.designerPlan3Per.Name = "designerPlan3Per";
            this.designerPlan3Per.Size = new System.Drawing.Size(160, 22);
            this.designerPlan3Per.Text = "per month";
            this.designerPlan3.Controls.Add(this.designerPlan3Per);
            this.designerPlan3What = new System.Windows.Forms.Label();
            this.designerPlan3What.AutoSize = false;
            this.designerPlan3What.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan3What.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerPlan3What.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.designerPlan3What.Location = new System.Drawing.Point(20, 220);
            this.designerPlan3What.Name = "designerPlan3What";
            this.designerPlan3What.Size = new System.Drawing.Size(180, 24);
            this.designerPlan3What.Text = "WHAT YOU GET";
            this.designerPlan3.Controls.Add(this.designerPlan3What);
            this.designerPlan3Feat1 = new System.Windows.Forms.Label();
            this.designerPlan3Feat1.AutoSize = false;
            this.designerPlan3Feat1.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan3Feat1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan3Feat1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan3Feat1.Location = new System.Drawing.Point(20, 252);
            this.designerPlan3Feat1.Name = "designerPlan3Feat1";
            this.designerPlan3Feat1.Size = new System.Drawing.Size(270, 22);
            this.designerPlan3Feat1.Text = "✓  15% off every purchase";
            this.designerPlan3.Controls.Add(this.designerPlan3Feat1);
            this.designerPlan3Feat2 = new System.Windows.Forms.Label();
            this.designerPlan3Feat2.AutoSize = false;
            this.designerPlan3Feat2.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan3Feat2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan3Feat2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan3Feat2.Location = new System.Drawing.Point(20, 281);
            this.designerPlan3Feat2.Name = "designerPlan3Feat2";
            this.designerPlan3Feat2.Size = new System.Drawing.Size(270, 22);
            this.designerPlan3Feat2.Text = "✓  2 free games / month";
            this.designerPlan3.Controls.Add(this.designerPlan3Feat2);
            this.designerPlan3Feat3 = new System.Windows.Forms.Label();
            this.designerPlan3Feat3.AutoSize = false;
            this.designerPlan3Feat3.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan3Feat3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan3Feat3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan3Feat3.Location = new System.Drawing.Point(20, 310);
            this.designerPlan3Feat3.Name = "designerPlan3Feat3";
            this.designerPlan3Feat3.Size = new System.Drawing.Size(270, 22);
            this.designerPlan3Feat3.Text = "✓  Exclusive beta access";
            this.designerPlan3.Controls.Add(this.designerPlan3Feat3);
            this.designerPlan3Feat4 = new System.Windows.Forms.Label();
            this.designerPlan3Feat4.AutoSize = false;
            this.designerPlan3Feat4.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan3Feat4.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan3Feat4.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan3Feat4.Location = new System.Drawing.Point(20, 339);
            this.designerPlan3Feat4.Name = "designerPlan3Feat4";
            this.designerPlan3Feat4.Size = new System.Drawing.Size(270, 22);
            this.designerPlan3Feat4.Text = "✓  3x loyalty points";
            this.designerPlan3.Controls.Add(this.designerPlan3Feat4);
            this.designerPlan3Feat5 = new System.Windows.Forms.Label();
            this.designerPlan3Feat5.AutoSize = false;
            this.designerPlan3Feat5.BackColor = System.Drawing.Color.Transparent;
            this.designerPlan3Feat5.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan3Feat5.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerPlan3Feat5.Location = new System.Drawing.Point(20, 368);
            this.designerPlan3Feat5.Name = "designerPlan3Feat5";
            this.designerPlan3Feat5.Size = new System.Drawing.Size(270, 22);
            this.designerPlan3Feat5.Text = "✓  Gift game keys";
            this.designerPlan3.Controls.Add(this.designerPlan3Feat5);
            this.designerPlan3Choose = new System.Windows.Forms.Button();
            this.designerPlan3Choose.BackColor = System.Drawing.Color.FromArgb(247, 190, 89);
            this.designerPlan3Choose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerPlan3Choose.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerPlan3Choose.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerPlan3Choose.Location = new System.Drawing.Point(20, 446);
            this.designerPlan3Choose.Name = "designerPlan3Choose";
            this.designerPlan3Choose.Size = new System.Drawing.Size(272, 36);
            this.designerPlan3Choose.Text = "Choose Ultimate";
            this.designerPlan3Choose.UseVisualStyleBackColor = false;
            this.designerPlan3.Controls.Add(this.designerPlan3Choose);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(1040, 640);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(950, 620);
            this.Name = "SubscriptionForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - GameHub Pass";
        }

        private System.Windows.Forms.Label designerTitle;
        private System.Windows.Forms.Label designerSubtitle;
        private System.Windows.Forms.Button designerBack;
        private System.Windows.Forms.Panel designerPlan1;
        private System.Windows.Forms.Panel designerPlan1Head;
        private System.Windows.Forms.Label designerPlan1Pill;
        private System.Windows.Forms.Label designerPlan1Name;
        private System.Windows.Forms.Label designerPlan1Discount;
        private System.Windows.Forms.Label designerPlan1Price;
        private System.Windows.Forms.Label designerPlan1Per;
        private System.Windows.Forms.Label designerPlan1What;
        private System.Windows.Forms.Label designerPlan1Feat1;
        private System.Windows.Forms.Label designerPlan1Feat2;
        private System.Windows.Forms.Label designerPlan1Feat3;
        private System.Windows.Forms.Label designerPlan1Feat4;
        private System.Windows.Forms.Button designerPlan1Choose;
        private System.Windows.Forms.Panel designerPlan2;
        private System.Windows.Forms.Panel designerPlan2Head;
        private System.Windows.Forms.Label designerPlan2Pill;
        private System.Windows.Forms.Label designerPlan2Name;
        private System.Windows.Forms.Label designerPlan2Discount;
        private System.Windows.Forms.Label designerPlan2Price;
        private System.Windows.Forms.Label designerPlan2Per;
        private System.Windows.Forms.Label designerPlan2What;
        private System.Windows.Forms.Label designerPlan2Feat1;
        private System.Windows.Forms.Label designerPlan2Feat2;
        private System.Windows.Forms.Label designerPlan2Feat3;
        private System.Windows.Forms.Label designerPlan2Feat4;
        private System.Windows.Forms.Label designerPlan2Feat5;
        private System.Windows.Forms.Button designerPlan2Choose;
        private System.Windows.Forms.Panel designerPlan3;
        private System.Windows.Forms.Panel designerPlan3Head;
        private System.Windows.Forms.Label designerPlan3Pill;
        private System.Windows.Forms.Label designerPlan3Name;
        private System.Windows.Forms.Label designerPlan3Discount;
        private System.Windows.Forms.Label designerPlan3Price;
        private System.Windows.Forms.Label designerPlan3Per;
        private System.Windows.Forms.Label designerPlan3What;
        private System.Windows.Forms.Label designerPlan3Feat1;
        private System.Windows.Forms.Label designerPlan3Feat2;
        private System.Windows.Forms.Label designerPlan3Feat3;
        private System.Windows.Forms.Label designerPlan3Feat4;
        private System.Windows.Forms.Label designerPlan3Feat5;
        private System.Windows.Forms.Button designerPlan3Choose;
    }
}
