namespace GameHub.Forms
{
    partial class UsersForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerTitle = new System.Windows.Forms.Label();
            this.designerTitle.AutoSize = false;
            this.designerTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTitle.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.designerTitle.Location = new System.Drawing.Point(28, 20);
            this.designerTitle.Name = "designerTitle";
            this.designerTitle.Size = new System.Drawing.Size(600, 44);
            this.designerTitle.Text = "Users & Staff";
            this.Controls.Add(this.designerTitle);
            this.designerSubtitle = new System.Windows.Forms.Label();
            this.designerSubtitle.AutoSize = false;
            this.designerSubtitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSubtitle.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSubtitle.Font = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Regular);
            this.designerSubtitle.Location = new System.Drawing.Point(30, 62);
            this.designerSubtitle.Name = "designerSubtitle";
            this.designerSubtitle.Size = new System.Drawing.Size(820, 28);
            this.designerSubtitle.Text = "Create accounts, assign roles, update contact data and reset passwords.";
            this.Controls.Add(this.designerSubtitle);
            this.designerBack = new System.Windows.Forms.Button();
            this.designerBack.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBack.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBack.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBack.Location = new System.Drawing.Point(1138, 22);
            this.designerBack.Name = "designerBack";
            this.designerBack.Size = new System.Drawing.Size(112, 38);
            this.designerBack.Text = "←  BACK";
            this.designerBack.UseVisualStyleBackColor = false;
            this.Controls.Add(this.designerBack);
            this.designerEditor = new System.Windows.Forms.Panel();
            this.designerEditor.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerEditor.Location = new System.Drawing.Point(28, 108);
            this.designerEditor.Name = "designerEditor";
            this.designerEditor.Size = new System.Drawing.Size(410, 624);
            this.Controls.Add(this.designerEditor);
            this.designerAccountPill = new System.Windows.Forms.Label();
            this.designerAccountPill.AutoSize = false;
            this.designerAccountPill.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerAccountPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerAccountPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerAccountPill.Location = new System.Drawing.Point(20, 16);
            this.designerAccountPill.Name = "designerAccountPill";
            this.designerAccountPill.Size = new System.Drawing.Size(82, 26);
            this.designerAccountPill.Text = "ACCOUNT";
            this.designerAccountPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerEditor.Controls.Add(this.designerAccountPill);
            this.designerAccountTitle = new System.Windows.Forms.Label();
            this.designerAccountTitle.AutoSize = false;
            this.designerAccountTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerAccountTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerAccountTitle.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerAccountTitle.Location = new System.Drawing.Point(20, 50);
            this.designerAccountTitle.Name = "designerAccountTitle";
            this.designerAccountTitle.Size = new System.Drawing.Size(320, 34);
            this.designerAccountTitle.Text = "Account Details";
            this.designerEditor.Controls.Add(this.designerAccountTitle);
            this.designerUserLabel1 = new System.Windows.Forms.Label();
            this.designerUserLabel1.AutoSize = false;
            this.designerUserLabel1.BackColor = System.Drawing.Color.Transparent;
            this.designerUserLabel1.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerUserLabel1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerUserLabel1.Location = new System.Drawing.Point(20, 86);
            this.designerUserLabel1.Name = "designerUserLabel1";
            this.designerUserLabel1.Size = new System.Drawing.Size(370, 22);
            this.designerUserLabel1.Text = "Username";
            this.designerEditor.Controls.Add(this.designerUserLabel1);
            this._txtUser = new System.Windows.Forms.TextBox();
            this._txtUser.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtUser.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtUser.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtUser.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtUser.Location = new System.Drawing.Point(20, 110);
            this._txtUser.Name = "_txtUser";
            this._txtUser.Size = new System.Drawing.Size(370, 32);
            this.designerEditor.Controls.Add(this._txtUser);
            this.designerUserLabel2 = new System.Windows.Forms.Label();
            this.designerUserLabel2.AutoSize = false;
            this.designerUserLabel2.BackColor = System.Drawing.Color.Transparent;
            this.designerUserLabel2.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerUserLabel2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerUserLabel2.Location = new System.Drawing.Point(20, 156);
            this.designerUserLabel2.Name = "designerUserLabel2";
            this.designerUserLabel2.Size = new System.Drawing.Size(370, 22);
            this.designerUserLabel2.Text = "Password / Reset Password";
            this.designerEditor.Controls.Add(this.designerUserLabel2);
            this._txtPass = new System.Windows.Forms.TextBox();
            this._txtPass.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtPass.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtPass.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtPass.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtPass.Location = new System.Drawing.Point(20, 180);
            this._txtPass.Name = "_txtPass";
            this._txtPass.Size = new System.Drawing.Size(370, 32);
            this._txtPass.PasswordChar = '●';
            this.designerEditor.Controls.Add(this._txtPass);
            this.designerUserLabel3 = new System.Windows.Forms.Label();
            this.designerUserLabel3.AutoSize = false;
            this.designerUserLabel3.BackColor = System.Drawing.Color.Transparent;
            this.designerUserLabel3.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerUserLabel3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerUserLabel3.Location = new System.Drawing.Point(20, 226);
            this.designerUserLabel3.Name = "designerUserLabel3";
            this.designerUserLabel3.Size = new System.Drawing.Size(370, 22);
            this.designerUserLabel3.Text = "Full Name";
            this.designerEditor.Controls.Add(this.designerUserLabel3);
            this._txtName = new System.Windows.Forms.TextBox();
            this._txtName.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtName.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtName.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtName.Location = new System.Drawing.Point(20, 250);
            this._txtName.Name = "_txtName";
            this._txtName.Size = new System.Drawing.Size(370, 32);
            this.designerEditor.Controls.Add(this._txtName);
            this.designerUserLabel4 = new System.Windows.Forms.Label();
            this.designerUserLabel4.AutoSize = false;
            this.designerUserLabel4.BackColor = System.Drawing.Color.Transparent;
            this.designerUserLabel4.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerUserLabel4.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerUserLabel4.Location = new System.Drawing.Point(20, 296);
            this.designerUserLabel4.Name = "designerUserLabel4";
            this.designerUserLabel4.Size = new System.Drawing.Size(370, 22);
            this.designerUserLabel4.Text = "Email";
            this.designerEditor.Controls.Add(this.designerUserLabel4);
            this._txtEmail = new System.Windows.Forms.TextBox();
            this._txtEmail.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtEmail.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtEmail.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtEmail.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtEmail.Location = new System.Drawing.Point(20, 320);
            this._txtEmail.Name = "_txtEmail";
            this._txtEmail.Size = new System.Drawing.Size(370, 32);
            this.designerEditor.Controls.Add(this._txtEmail);
            this.designerUserLabel5 = new System.Windows.Forms.Label();
            this.designerUserLabel5.AutoSize = false;
            this.designerUserLabel5.BackColor = System.Drawing.Color.Transparent;
            this.designerUserLabel5.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerUserLabel5.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerUserLabel5.Location = new System.Drawing.Point(20, 366);
            this.designerUserLabel5.Name = "designerUserLabel5";
            this.designerUserLabel5.Size = new System.Drawing.Size(370, 22);
            this.designerUserLabel5.Text = "Phone";
            this.designerEditor.Controls.Add(this.designerUserLabel5);
            this._txtPhone = new System.Windows.Forms.TextBox();
            this._txtPhone.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtPhone.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtPhone.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtPhone.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtPhone.Location = new System.Drawing.Point(20, 390);
            this._txtPhone.Name = "_txtPhone";
            this._txtPhone.Size = new System.Drawing.Size(370, 32);
            this.designerEditor.Controls.Add(this._txtPhone);
            this.designerRoleLabel = new System.Windows.Forms.Label();
            this.designerRoleLabel.AutoSize = false;
            this.designerRoleLabel.BackColor = System.Drawing.Color.Transparent;
            this.designerRoleLabel.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerRoleLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerRoleLabel.Location = new System.Drawing.Point(20, 442);
            this.designerRoleLabel.Name = "designerRoleLabel";
            this.designerRoleLabel.Size = new System.Drawing.Size(160, 22);
            this.designerRoleLabel.Text = "Role";
            this.designerEditor.Controls.Add(this.designerRoleLabel);
            this._cboRole = new System.Windows.Forms.ComboBox();
            this._cboRole.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._cboRole.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._cboRole.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._cboRole.Location = new System.Drawing.Point(20, 466);
            this._cboRole.Name = "_cboRole";
            this._cboRole.Size = new System.Drawing.Size(180, 32);
            this._cboRole.Items.AddRange(new object[] { "Customer", "Staff", "Admin" });
            this._cboRole.SelectedIndex = 0;
            this.designerEditor.Controls.Add(this._cboRole);
            this._chkActive = new System.Windows.Forms.CheckBox();
            this._chkActive.AutoSize = false;
            this._chkActive.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._chkActive.Location = new System.Drawing.Point(220, 468);
            this._chkActive.Name = "_chkActive";
            this._chkActive.Size = new System.Drawing.Size(170, 26);
            this._chkActive.Text = "Account is active";
            this._chkActive.UseVisualStyleBackColor = true;
            this.designerEditor.Controls.Add(this._chkActive);
            this.designerAdd = new System.Windows.Forms.Button();
            this.designerAdd.BackColor = System.Drawing.Color.FromArgb(72, 201, 154);
            this.designerAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerAdd.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerAdd.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerAdd.Location = new System.Drawing.Point(20, 530);
            this.designerAdd.Name = "designerAdd";
            this.designerAdd.Size = new System.Drawing.Size(75, 36);
            this.designerAdd.Text = "ADD";
            this.designerAdd.UseVisualStyleBackColor = false;
            this.designerAdd.Click += new System.EventHandler(this.Add_Click);
            this.designerEditor.Controls.Add(this.designerAdd);
            this.designerUpdate = new System.Windows.Forms.Button();
            this.designerUpdate.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerUpdate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerUpdate.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerUpdate.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerUpdate.Location = new System.Drawing.Point(105, 530);
            this.designerUpdate.Name = "designerUpdate";
            this.designerUpdate.Size = new System.Drawing.Size(82, 36);
            this.designerUpdate.Text = "UPDATE";
            this.designerUpdate.UseVisualStyleBackColor = false;
            this.designerUpdate.Click += new System.EventHandler(this.Update_Click);
            this.designerEditor.Controls.Add(this.designerUpdate);
            this.designerReset = new System.Windows.Forms.Button();
            this.designerReset.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerReset.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerReset.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerReset.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerReset.Location = new System.Drawing.Point(197, 530);
            this.designerReset.Name = "designerReset";
            this.designerReset.Size = new System.Drawing.Size(95, 36);
            this.designerReset.Text = "RESET PW";
            this.designerReset.UseVisualStyleBackColor = false;
            this.designerReset.Click += new System.EventHandler(this.ResetPassword_Click);
            this.designerEditor.Controls.Add(this.designerReset);
            this.designerDeactivate = new System.Windows.Forms.Button();
            this.designerDeactivate.BackColor = System.Drawing.Color.FromArgb(238, 93, 111);
            this.designerDeactivate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerDeactivate.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerDeactivate.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerDeactivate.Location = new System.Drawing.Point(302, 530);
            this.designerDeactivate.Name = "designerDeactivate";
            this.designerDeactivate.Size = new System.Drawing.Size(88, 36);
            this.designerDeactivate.Text = "DEACTIVATE";
            this.designerDeactivate.UseVisualStyleBackColor = false;
            this.designerDeactivate.Click += new System.EventHandler(this.Deactivate_Click);
            this.designerEditor.Controls.Add(this.designerDeactivate);
            this.designerDirectory = new System.Windows.Forms.Panel();
            this.designerDirectory.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerDirectory.Location = new System.Drawing.Point(458, 108);
            this.designerDirectory.Name = "designerDirectory";
            this.designerDirectory.Size = new System.Drawing.Size(794, 624);
            this.Controls.Add(this.designerDirectory);
            this.designerDirectoryPill = new System.Windows.Forms.Label();
            this.designerDirectoryPill.AutoSize = false;
            this.designerDirectoryPill.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerDirectoryPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerDirectoryPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerDirectoryPill.Location = new System.Drawing.Point(18, 16);
            this.designerDirectoryPill.Name = "designerDirectoryPill";
            this.designerDirectoryPill.Size = new System.Drawing.Size(68, 26);
            this.designerDirectoryPill.Text = "USERS";
            this.designerDirectoryPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerDirectory.Controls.Add(this.designerDirectoryPill);
            this.designerDirectoryTitle = new System.Windows.Forms.Label();
            this.designerDirectoryTitle.AutoSize = false;
            this.designerDirectoryTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerDirectoryTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerDirectoryTitle.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.designerDirectoryTitle.Location = new System.Drawing.Point(18, 50);
            this.designerDirectoryTitle.Name = "designerDirectoryTitle";
            this.designerDirectoryTitle.Size = new System.Drawing.Size(350, 34);
            this.designerDirectoryTitle.Text = "Account Directory";
            this.designerDirectory.Controls.Add(this.designerDirectoryTitle);
            this.designerDirectorySub = new System.Windows.Forms.Label();
            this.designerDirectorySub.AutoSize = false;
            this.designerDirectorySub.BackColor = System.Drawing.Color.Transparent;
            this.designerDirectorySub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerDirectorySub.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerDirectorySub.Location = new System.Drawing.Point(18, 82);
            this.designerDirectorySub.Name = "designerDirectorySub";
            this.designerDirectorySub.Size = new System.Drawing.Size(420, 24);
            this.designerDirectorySub.Text = "Customers, staff and administrators";
            this.designerDirectory.Controls.Add(this.designerDirectorySub);
            this._grid = new System.Windows.Forms.DataGridView();
            this._grid.AllowUserToAddRows = false;
            this._grid.AllowUserToDeleteRows = false;
            this._grid.BackgroundColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this._grid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._grid.ColumnHeadersHeight = 36;
            this._grid.Location = new System.Drawing.Point(18, 118);
            this._grid.Name = "_grid";
            this._grid.ReadOnly = true;
            this._grid.RowHeadersVisible = false;
            this._grid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._grid.Size = new System.Drawing.Size(758, 486);
            this._grid.SelectionChanged += new System.EventHandler(this.Grid_SelectionChanged);
            this.designerDirectory.Controls.Add(this._grid);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(1280, 760);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(1100, 720);
            this.Name = "UsersForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - Users & Staff";
        }

        private System.Windows.Forms.Label designerTitle;
        private System.Windows.Forms.Label designerSubtitle;
        private System.Windows.Forms.Button designerBack;
        private System.Windows.Forms.Panel designerEditor;
        private System.Windows.Forms.Label designerAccountPill;
        private System.Windows.Forms.Label designerAccountTitle;
        private System.Windows.Forms.Label designerUserLabel1;
        private System.Windows.Forms.Label designerUserLabel2;
        private System.Windows.Forms.Label designerUserLabel3;
        private System.Windows.Forms.Label designerUserLabel4;
        private System.Windows.Forms.Label designerUserLabel5;
        private System.Windows.Forms.Label designerRoleLabel;
        private System.Windows.Forms.Button designerAdd;
        private System.Windows.Forms.Button designerUpdate;
        private System.Windows.Forms.Button designerReset;
        private System.Windows.Forms.Button designerDeactivate;
        private System.Windows.Forms.Panel designerDirectory;
        private System.Windows.Forms.Label designerDirectoryPill;
        private System.Windows.Forms.Label designerDirectoryTitle;
        private System.Windows.Forms.Label designerDirectorySub;
    }
}
