namespace GameHub.Forms
{
    partial class WalletForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.designerTitle = new System.Windows.Forms.Label();
            this.designerTitle.AutoSize = false;
            this.designerTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.designerTitle.Location = new System.Drawing.Point(28, 22);
            this.designerTitle.Name = "designerTitle";
            this.designerTitle.Size = new System.Drawing.Size(520, 42);
            this.designerTitle.Text = "Wallet & Rewards";
            this.Controls.Add(this.designerTitle);
            this.designerSubtitle = new System.Windows.Forms.Label();
            this.designerSubtitle.AutoSize = false;
            this.designerSubtitle.BackColor = System.Drawing.Color.Transparent;
            this.designerSubtitle.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerSubtitle.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerSubtitle.Location = new System.Drawing.Point(30, 54);
            this.designerSubtitle.Name = "designerSubtitle";
            this.designerSubtitle.Size = new System.Drawing.Size(650, 28);
            this.designerSubtitle.Text = "Manage balance, loyalty points and membership benefits.";
            this.Controls.Add(this.designerSubtitle);
            this.designerBack = new System.Windows.Forms.Button();
            this.designerBack.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerBack.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerBack.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerBack.Location = new System.Drawing.Point(776, 20);
            this.designerBack.Name = "designerBack";
            this.designerBack.Size = new System.Drawing.Size(96, 34);
            this.designerBack.Text = "←  Back";
            this.designerBack.UseVisualStyleBackColor = false;
            this.Controls.Add(this.designerBack);
            this.designerBalance = new System.Windows.Forms.Panel();
            this.designerBalance.BackColor = System.Drawing.Color.FromArgb(104, 92, 255);
            this.designerBalance.Location = new System.Drawing.Point(28, 94);
            this.designerBalance.Name = "designerBalance";
            this.designerBalance.Size = new System.Drawing.Size(404, 142);
            this.Controls.Add(this.designerBalance);
            this.designerBalancePill = new System.Windows.Forms.Label();
            this.designerBalancePill.AutoSize = false;
            this.designerBalancePill.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerBalancePill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerBalancePill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerBalancePill.Location = new System.Drawing.Point(18, 18);
            this.designerBalancePill.Name = "designerBalancePill";
            this.designerBalancePill.Size = new System.Drawing.Size(66, 26);
            this.designerBalancePill.Text = "WALLET";
            this.designerBalancePill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerBalance.Controls.Add(this.designerBalancePill);
            this.designerBalanceSub = new System.Windows.Forms.Label();
            this.designerBalanceSub.AutoSize = false;
            this.designerBalanceSub.BackColor = System.Drawing.Color.Transparent;
            this.designerBalanceSub.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerBalanceSub.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerBalanceSub.Location = new System.Drawing.Point(18, 56);
            this.designerBalanceSub.Name = "designerBalanceSub";
            this.designerBalanceSub.Size = new System.Drawing.Size(180, 22);
            this.designerBalanceSub.Text = "Available balance";
            this.designerBalance.Controls.Add(this.designerBalanceSub);
            this._lblBalance = new System.Windows.Forms.Label();
            this._lblBalance.AutoSize = false;
            this._lblBalance.BackColor = System.Drawing.Color.Transparent;
            this._lblBalance.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._lblBalance.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
            this._lblBalance.Location = new System.Drawing.Point(18, 78);
            this._lblBalance.Name = "_lblBalance";
            this._lblBalance.Size = new System.Drawing.Size(300, 44);
            this._lblBalance.Text = "Tk 8,450.00";
            this.designerBalance.Controls.Add(this._lblBalance);
            this.designerPoints = new System.Windows.Forms.Panel();
            this.designerPoints.BackColor = System.Drawing.Color.FromArgb(166, 106, 255);
            this.designerPoints.Location = new System.Drawing.Point(450, 94);
            this.designerPoints.Name = "designerPoints";
            this.designerPoints.Size = new System.Drawing.Size(422, 142);
            this.Controls.Add(this.designerPoints);
            this.designerPointsPill = new System.Windows.Forms.Label();
            this.designerPointsPill.AutoSize = false;
            this.designerPointsPill.BackColor = System.Drawing.Color.FromArgb(13, 16, 31);
            this.designerPointsPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerPointsPill.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.designerPointsPill.Location = new System.Drawing.Point(18, 18);
            this.designerPointsPill.Name = "designerPointsPill";
            this.designerPointsPill.Size = new System.Drawing.Size(78, 26);
            this.designerPointsPill.Text = "REWARDS";
            this.designerPointsPill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.designerPoints.Controls.Add(this.designerPointsPill);
            this.designerPointsSub = new System.Windows.Forms.Label();
            this.designerPointsSub.AutoSize = false;
            this.designerPointsSub.BackColor = System.Drawing.Color.Transparent;
            this.designerPointsSub.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerPointsSub.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerPointsSub.Location = new System.Drawing.Point(18, 56);
            this.designerPointsSub.Name = "designerPointsSub";
            this.designerPointsSub.Size = new System.Drawing.Size(180, 22);
            this.designerPointsSub.Text = "Loyalty points";
            this.designerPoints.Controls.Add(this.designerPointsSub);
            this._lblPoints = new System.Windows.Forms.Label();
            this._lblPoints.AutoSize = false;
            this._lblPoints.BackColor = System.Drawing.Color.Transparent;
            this._lblPoints.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._lblPoints.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold);
            this._lblPoints.Location = new System.Drawing.Point(18, 78);
            this._lblPoints.Name = "_lblPoints";
            this._lblPoints.Size = new System.Drawing.Size(300, 44);
            this._lblPoints.Text = "1,240 pts";
            this.designerPoints.Controls.Add(this._lblPoints);
            this.designerMembership = new System.Windows.Forms.Panel();
            this.designerMembership.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerMembership.Location = new System.Drawing.Point(28, 256);
            this.designerMembership.Name = "designerMembership";
            this.designerMembership.Size = new System.Drawing.Size(844, 76);
            this.Controls.Add(this.designerMembership);
            this.designerMembershipPill = new System.Windows.Forms.Label();
            this.designerMembershipPill.AutoSize = false;
            this.designerMembershipPill.BackColor = System.Drawing.Color.Transparent;
            this.designerMembershipPill.ForeColor = System.Drawing.Color.FromArgb(235, 237, 255);
            this.designerMembershipPill.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.designerMembershipPill.Location = new System.Drawing.Point(18, 15);
            this.designerMembershipPill.Name = "designerMembershipPill";
            this.designerMembershipPill.Size = new System.Drawing.Size(220, 20);
            this.designerMembershipPill.Text = "ACTIVE MEMBERSHIP";
            this.designerMembership.Controls.Add(this.designerMembershipPill);
            this._lblPlan = new System.Windows.Forms.Label();
            this._lblPlan.AutoSize = false;
            this._lblPlan.BackColor = System.Drawing.Color.Transparent;
            this._lblPlan.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._lblPlan.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this._lblPlan.Location = new System.Drawing.Point(18, 38);
            this._lblPlan.Name = "_lblPlan";
            this._lblPlan.Size = new System.Drawing.Size(360, 28);
            this._lblPlan.Text = "GameHub Pass - Plus";
            this.designerMembership.Controls.Add(this._lblPlan);
            this.designerViewPass = new System.Windows.Forms.Button();
            this.designerViewPass.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this.designerViewPass.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerViewPass.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerViewPass.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerViewPass.Location = new System.Drawing.Point(710, 21);
            this.designerViewPass.Name = "designerViewPass";
            this.designerViewPass.Size = new System.Drawing.Size(116, 34);
            this.designerViewPass.Text = "View Pass";
            this.designerViewPass.UseVisualStyleBackColor = false;
            this.designerMembership.Controls.Add(this.designerViewPass);
            this.designerTopup = new System.Windows.Forms.Panel();
            this.designerTopup.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerTopup.Location = new System.Drawing.Point(28, 352);
            this.designerTopup.Name = "designerTopup";
            this.designerTopup.Size = new System.Drawing.Size(300, 236);
            this.Controls.Add(this.designerTopup);
            this.designerTopupTitle = new System.Windows.Forms.Label();
            this.designerTopupTitle.AutoSize = false;
            this.designerTopupTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTopupTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTopupTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.designerTopupTitle.Location = new System.Drawing.Point(18, 16);
            this.designerTopupTitle.Name = "designerTopupTitle";
            this.designerTopupTitle.Size = new System.Drawing.Size(230, 28);
            this.designerTopupTitle.Text = "Top Up Wallet";
            this.designerTopup.Controls.Add(this.designerTopupTitle);
            this.designerTopupSub = new System.Windows.Forms.Label();
            this.designerTopupSub.AutoSize = false;
            this.designerTopupSub.BackColor = System.Drawing.Color.Transparent;
            this.designerTopupSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerTopupSub.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerTopupSub.Location = new System.Drawing.Point(18, 42);
            this.designerTopupSub.Name = "designerTopupSub";
            this.designerTopupSub.Size = new System.Drawing.Size(250, 22);
            this.designerTopupSub.Text = "Add funds to use at checkout.";
            this.designerTopup.Controls.Add(this.designerTopupSub);
            this.designerAmountLabel = new System.Windows.Forms.Label();
            this.designerAmountLabel.AutoSize = false;
            this.designerAmountLabel.BackColor = System.Drawing.Color.Transparent;
            this.designerAmountLabel.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerAmountLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular);
            this.designerAmountLabel.Location = new System.Drawing.Point(18, 82);
            this.designerAmountLabel.Name = "designerAmountLabel";
            this.designerAmountLabel.Size = new System.Drawing.Size(180, 22);
            this.designerAmountLabel.Text = "Amount (BDT)";
            this.designerTopup.Controls.Add(this.designerAmountLabel);
            this._txtAmount = new System.Windows.Forms.TextBox();
            this._txtAmount.BackColor = System.Drawing.Color.FromArgb(31, 36, 66);
            this._txtAmount.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._txtAmount.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this._txtAmount.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this._txtAmount.Location = new System.Drawing.Point(18, 106);
            this._txtAmount.Name = "_txtAmount";
            this._txtAmount.Size = new System.Drawing.Size(264, 30);
            this.designerTopup.Controls.Add(this._txtAmount);
            this.designerTopupButton = new System.Windows.Forms.Button();
            this.designerTopupButton.BackColor = System.Drawing.Color.FromArgb(72, 201, 154);
            this.designerTopupButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.designerTopupButton.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTopupButton.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.designerTopupButton.Location = new System.Drawing.Point(18, 154);
            this.designerTopupButton.Name = "designerTopupButton";
            this.designerTopupButton.Size = new System.Drawing.Size(264, 38);
            this.designerTopupButton.Text = "TOP UP";
            this.designerTopupButton.UseVisualStyleBackColor = false;
            this.designerTopupButton.Click += new System.EventHandler(this.TopUp_Click);
            this.designerTopup.Controls.Add(this.designerTopupButton);
            this.designerFunds = new System.Windows.Forms.Label();
            this.designerFunds.AutoSize = false;
            this.designerFunds.BackColor = System.Drawing.Color.Transparent;
            this.designerFunds.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerFunds.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerFunds.Location = new System.Drawing.Point(18, 203);
            this.designerFunds.Name = "designerFunds";
            this.designerFunds.Size = new System.Drawing.Size(250, 22);
            this.designerFunds.Text = "Funds are added immediately.";
            this.designerTopup.Controls.Add(this.designerFunds);
            this.designerTx = new System.Windows.Forms.Panel();
            this.designerTx.BackColor = System.Drawing.Color.FromArgb(22, 26, 48);
            this.designerTx.Location = new System.Drawing.Point(348, 352);
            this.designerTx.Name = "designerTx";
            this.designerTx.Size = new System.Drawing.Size(524, 236);
            this.Controls.Add(this.designerTx);
            this.designerTxTitle = new System.Windows.Forms.Label();
            this.designerTxTitle.AutoSize = false;
            this.designerTxTitle.BackColor = System.Drawing.Color.Transparent;
            this.designerTxTitle.ForeColor = System.Drawing.Color.FromArgb(248, 249, 255);
            this.designerTxTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.designerTxTitle.Location = new System.Drawing.Point(18, 16);
            this.designerTxTitle.Name = "designerTxTitle";
            this.designerTxTitle.Size = new System.Drawing.Size(300, 28);
            this.designerTxTitle.Text = "Recent Transactions";
            this.designerTx.Controls.Add(this.designerTxTitle);
            this.designerTxSub = new System.Windows.Forms.Label();
            this.designerTxSub.AutoSize = false;
            this.designerTxSub.BackColor = System.Drawing.Color.Transparent;
            this.designerTxSub.ForeColor = System.Drawing.Color.FromArgb(158, 166, 195);
            this.designerTxSub.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Regular);
            this.designerTxSub.Location = new System.Drawing.Point(18, 42);
            this.designerTxSub.Name = "designerTxSub";
            this.designerTxSub.Size = new System.Drawing.Size(250, 22);
            this.designerTxSub.Text = "Latest wallet activity";
            this.designerTx.Controls.Add(this.designerTxSub);
            this._grid = new System.Windows.Forms.DataGridView();
            this._grid.AllowUserToAddRows = false;
            this._grid.AllowUserToDeleteRows = false;
            this._grid.BackgroundColor = System.Drawing.Color.FromArgb(24, 28, 52);
            this._grid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._grid.ColumnHeadersHeight = 36;
            this._grid.Location = new System.Drawing.Point(18, 70);
            this._grid.Name = "_grid";
            this._grid.ReadOnly = true;
            this._grid.RowHeadersVisible = false;
            this._grid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this._grid.Size = new System.Drawing.Size(488, 146);
            this.designerTx.Controls.Add(this._grid);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.FromArgb(8, 10, 20);
            this.ClientSize = new System.Drawing.Size(900, 620);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.MinimumSize = new System.Drawing.Size(850, 600);
            this.Name = "WalletForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "GameHub - My Wallet & Rewards";
        }

        private System.Windows.Forms.Label designerTitle;
        private System.Windows.Forms.Label designerSubtitle;
        private System.Windows.Forms.Button designerBack;
        private System.Windows.Forms.Panel designerBalance;
        private System.Windows.Forms.Label designerBalancePill;
        private System.Windows.Forms.Label designerBalanceSub;
        private System.Windows.Forms.Panel designerPoints;
        private System.Windows.Forms.Label designerPointsPill;
        private System.Windows.Forms.Label designerPointsSub;
        private System.Windows.Forms.Panel designerMembership;
        private System.Windows.Forms.Label designerMembershipPill;
        private System.Windows.Forms.Button designerViewPass;
        private System.Windows.Forms.Panel designerTopup;
        private System.Windows.Forms.Label designerTopupTitle;
        private System.Windows.Forms.Label designerTopupSub;
        private System.Windows.Forms.Label designerAmountLabel;
        private System.Windows.Forms.Button designerTopupButton;
        private System.Windows.Forms.Label designerFunds;
        private System.Windows.Forms.Panel designerTx;
        private System.Windows.Forms.Label designerTxTitle;
        private System.Windows.Forms.Label designerTxSub;
    }
}
